CREATE SEQUENCE SEQ_SHV_MAS_OPERACION_MASIVA INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_SHV_MAS_OPERACION_ARCH INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_SHV_MAS_REGISTRO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999 MINVALUE 1 CACHE 20;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD CANT_REGISTROS_PROCESADOS_OK NUMBER;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD CANT_REGISTROS_ERROR NUMBER;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD CANT_REGISTROS NUMBER;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD ID_MOTIVO NUMBER NOT NULL ENABLE;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD ID_ANALISTA VARCHAR2(9 BYTE) NOT NULL ENABLE;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD ID_COPROPIETARIO VARCHAR2(9 BYTE);

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD ID_SEGMENTO VARCHAR2(3 BYTE) NOT NULL ENABLE;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD ID_EMPRESA VARCHAR2(2 BYTE) NOT NULL ENABLE;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD CANT_REGISTROS_EN_PROCESO NUMBER;

ALTER TABLE SHV_MAS_REGISTRO
ADD RESULTADO_CONSULTA_DEBITO	VARCHAR2(3 BYTE);

ALTER TABLE SHV_MAS_REGISTRO
ADD CODIGO_ERROR_DEBITO	VARCHAR2(10 BYTE);

ALTER TABLE SHV_MAS_REGISTRO
ADD DESCRIPCION_ERROR_DEBITO	VARCHAR2(100 BYTE);

ALTER TABLE SHV_MAS_REGISTRO
ADD RESULTADO_CONSULTA_CREDITO	VARCHAR2(3 BYTE);

ALTER TABLE SHV_MAS_REGISTRO
ADD CODIGO_ERROR_CREDITO	VARCHAR2(10 BYTE);

ALTER TABLE SHV_MAS_REGISTRO
ADD DESCRIPCION_ERROR_CREDITO	VARCHAR2(100 BYTE);

ALTER TABLE SHV_MAS_REGISTRO
ADD RESULTADO_CONSULTA_REINTEGRO	VARCHAR2(3 BYTE);

ALTER TABLE SHV_MAS_REGISTRO
ADD CODIGO_ERROR_REINTEGRO	VARCHAR2(10 BYTE);

ALTER TABLE SHV_MAS_REGISTRO
ADD DESCRIPCION_ERROR_REINTEGRO	VARCHAR2(100 BYTE);

ALTER TABLE SHV_COB_ED_COBRO ADD ID_OPERACION_MASIVA NUMBER;

ALTER TABLE SHV_COB_ED_COBRO
ADD CONSTRAINT COBRO_OPERACION_MASIVA_FK
FOREIGN KEY (ID_OPERACION_MASIVA) REFERENCES SHV_MAS_OPER_MASIVA(ID_OPERACION_MASIVA) ENABLE;

ALTER TABLE SHV_MAS_REGISTRO ADD NOMBRE_ARCHIVO_ORIGINAL VARCHAR2(100 BYTE);



ALTER TABLE SHV_MAS_REGISTRO_CLI_SIEBEL MODIFY RES_CONSULTA_SIEBEL_DEBITO VARCHAR2 (15 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_CLI_SIEBEL MODIFY RES_CONSULTA_SIEBEL_CREDITO VARCHAR2 (15 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_CLI_SIEBEL MODIFY RES_CONSULTA_SIEBEL_ACUERDO VARCHAR2 (15 BYTE);


ALTER TABLE SHV_MAS_REGISTRO MODIFY ESTADO VARCHAR2 (30 BYTE);
ALTER TABLE SHV_MAS_REGISTRO MODIFY ID_COBRO NUMBER NULL;
ALTER TABLE SHV_MAS_REGISTRO ADD USUARIO_MODIFICACION VARCHAR2(9 BYTE);


--Ojo con esto, hacerlo en dos sql separados por si falla
ALTER TABLE SHV_MAS_OPER_MASIVA_ARCH ADD LOG_PROCESAMIENTO_AUX VARCHAR2(255 BYTE);
UPDATE SHV_MAS_OPER_MASIVA_ARCH SET LOG_PROCESAMIENTO_AUX = LOG_PROCESAMIENTO;
--esto hacerlo en otro sql
ALTER TABLE SHV_MAS_OPER_MASIVA_ARCH DROP COLUMN LOG_PROCESAMIENTO;
ALTER TABLE SHV_MAS_OPER_MASIVA_ARCH RENAME COLUMN LOG_PROCESAMIENTO_AUX TO LOG_PROCESAMIENTO;


CREATE TABLE "SHV_WF_TAREA_OPERACION_MASIVA"
  (
    "ID_TAREA"            NUMBER NOT NULL ENABLE,
    "ID_OPERACION_MASIVA" NUMBER NOT NULL ENABLE,
    CONSTRAINT "SHV_WF_TAREA_FK" FOREIGN KEY ("ID_TAREA") REFERENCES "SHV_WF_TAREA" ("ID_TAREA") ENABLE,
    CONSTRAINT "SHV_MAS_OPER_MASIVA_FK" FOREIGN KEY ("ID_OPERACION_MASIVA") REFERENCES "SHV_MAS_OPER_MASIVA" ("ID_OPERACION_MASIVA") ENABLE
  );
  
  
Exit;