CREATE OR REPLACE VIEW SHV_SOP_DESCOBROS_OPER_RELAC (SISTEMA, ID_OPERACION, ID_OPERACION_PADRE, NRO_TRANSACCION_PADRE, TIPO_COMPROBANTE, NRO_DOCUMENTO_RELACIONADO, ID_MOTIVO_COBRO, DESC_MOTIVO_COBRO, CLIENTE, ESTADO, SUB_ESTADO, FECHA_ULTIMO_ESTADO, ANALISTA, COPROPIETARIO, ANALISTA_TEAM_COMERCIAL, IMPORTE_TOTAL, FECHA_ALTA, FECHA_DERIVACION, FECHA_AUTORIZACION_REFERENTE, FECHA_IMPUTACION, ID_DOCUMENTO_CUENTAS_COBRANZA, ID_COBRANZA, ID_OPERACION_RELACIONADA, ID_DESCOBRO)
                                               AS
  SELECT SCDOR.SISTEMA                         AS SISTEMA,
    NVL(SCDOR.ID_OPERACION, SCDOR.ID_COBRANZA) AS ID_OPERACION,
    SCDOR.ID_OPERACION_PADRE                   AS ID_OPERACION_PADRE,
    SCDOR.NRO_TRANSACCION_PADRE                AS NRO_TRANSACCION_PADRE,
    SCDOR.TIPO_COMPROBANTE                     AS TIPO_COMPROBANTE,
    NVL( TO_CHAR(SCDOR.NUMERO_REFERENCIA_MIC), NVL( TO_CHAR(SCDOR.ID_DOCUMENTO_CUENTAS_COBRANZA), (SCDOR.CLASE_COMPROBANTE
    || '-'
    || SCDOR.SUCURSAL_COMPROBANTE
    || '-'
    || SCDOR.NUMERO_COMPROBANTE) ) ) AS NRO_DOCUMENTO_RELACIONADO,
    SCEC.ID_MOTIVO_COBRO             AS ID_MOTIVO_COBRO,
    SPMC.DESCRIPCION                 AS DESC_MOTIVO_COBRO,
    NVL(
    (SELECT LISTAGG(SUBSTR(CEC.ID_CLIENTE_LEGADO
      || ' '
      || CEC.RAZON_SOCIAL,0,30), '-') WITHIN GROUP (
    ORDER BY CEC.ID_CLIENTE_LEGADO )
    FROM SHV_COB_ED_CLIENTE CEC
    WHERE CEC.ID_COBRO = SCEC.ID_COBRO
    ), TO_CHAR(SCDOR.ID_CLIENTE_LEGADO) ) AS CLIENTE,
    SWWE.ESTADO                           AS ESTADO,
    (SELECT SWWM1.ID_MARCA
    FROM SHV_WF_WORKFLOW_MARCA SWWM1
    WHERE SWWM1.ID_WORKFLOW_MARCA=
      (SELECT MAX (SWWM.ID_WORKFLOW_MARCA)
      FROM SHV_WF_WORKFLOW_MARCA SWWM
      WHERE SWWM.ID_WORKFLOW_ESTADO = SWWE.ID_WORKFLOW_ESTADO
      )
    ) AS SUB_ESTADO,
    TO_CHAR(
/*    (SELECT SWWM1.FECHA_CREACION
    FROM SHV_WF_WORKFLOW_MARCA SWWM1
    WHERE SWWM1.ID_WORKFLOW_MARCA=
      (SELECT MAX (SWWM.ID_WORKFLOW_MARCA)
      FROM SHV_WF_WORKFLOW_MARCA SWWM
      WHERE SWWM.ID_WORKFLOW_ESTADO = SWWE.ID_WORKFLOW_ESTADO
      )) */  
    SCEC.FECHA_ULTIMA_MODIFICACION
    , 'DD/MM/YYYY HH24:MI:SS' ) AS FECHA_ULTIMO_ESTADO,
    SCEC.ID_ANALISTA             AS ANALISTA,
    SCEC.ID_COPROPIETARIO        AS COPROPIETARIO,
    (SELECT LISTAGG(TEAM.USER_ANALISTA_COBRANZA_DATOS, '-') WITHIN GROUP(
    ORDER BY TEAM.USER_ANALISTA_COBRANZA_DATOS)
    FROM SHV_COB_ED_CLIENTE CEC2
    JOIN SHV_PARAM_TEAM_COMERCIAL TEAM
    ON (TEAM.NRO_DE_CLIENTE=CEC2.ID_CLIENTE_LEGADO)
    WHERE CEC2.ID_COBRO    = SCEC.ID_COBRO
    )                                                              AS ANALISTA_TEAM_COMERCIAL,
    NVL( SCEC.IMPORTE_TOTAL, SCDOR.IMPORTE_COBRADO )               AS IMPORTE_TOTAL,
    TO_CHAR(SCEC.FECHA_ALTA, 'DD/MM/YYYY  HH24:MI:SS' )            AS FECHA_ALTA,
    TO_CHAR(SCEC.FECHA_DERIVACION, 'DD/MM/YYYY HH24:MI:SS' )       AS FECHA_DERIVACION,
    TO_CHAR(SCEC.FECHA_APROB_REFER_COB , 'DD/MM/YYYY HH24:MI:SS' ) AS FECHA_AUTORIZACION_REFERENTE,
    TO_CHAR(SCDOR.FECHA_COBRANZA , 'DD/MM/YYYY HH24:MI:SS' )    AS FECHA_IMPUTACION,
    SCDOR.ID_DOCUMENTO_CUENTAS_COBRANZA                            AS ID_DOCUMENTO_CUENTAS_COBRANZA,
    SCDOR.ID_COBRANZA                                              AS ID_COBRANZA,
    SCDOR.ID_OPERACION_RELACIONADA                                 AS ID_OPERACION_RELACIONADA,
    SCDOR.ID_DESCOBRO                                              AS ID_DESCOBRO
  FROM SHV_COB_DESCOBRO_OPERAC_RELAC SCDOR
  LEFT JOIN SHV_COB_COBRO SCC
  ON SCDOR.ID_OPERACION = SCC.ID_OPERACION
  LEFT JOIN SHV_COB_ED_COBRO SCEC
  ON SCC.ID_COBRO = SCEC.ID_COBRO
  LEFT JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SCEC.ID_WORKFLOW = SWWE.ID_WORKFLOW
  LEFT JOIN SHV_PARAM_MOTIVO_COBRO SPMC
  ON SCEC.ID_MOTIVO_COBRO = SPMC.ID_MOTIVO_COBRO;
  
  Exit;