ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD INTERESES_TRASLA_REGU NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD INTERESES_TRASLA_NO_REGU NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD INTERESES_BONIF_REGU NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD INTERESES_BONIF_NO_REGU NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CODIGO_CLIENTE NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD MEDIO_PAGO_CUENTA NUMBER(3,0);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD MEDIO_PAGO_TIPO_CREDITO VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD TIPO_COMPROBANTE VARCHAR2(3 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD MEDIO_PAGO_CLASE_COMPROBANTE CHAR(1 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD SUCURSAL_COMPROBANTE VARCHAR2(4 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD NUMERO_COMPROBANTE VARCHAR2(8 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD NRO_REFERENCIA_MIC NUMBER(15,0);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CODIGO_TIPO_REMANENTE NUMBER(1,0);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD IMPORTE NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD SALDO NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD FECHA_ALTA DATE;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD FECHA_EMISION DATE;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD FECHA_VENCIMIENTO DATE;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD FECHA_ULTIMO_MOVIMIENTO DATE;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_MARCA_RECLAMO VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_MARCA_CYQ VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD ESTADO_ORIGEN VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_RAZON_SOCIAL_CLIENTE VARCHAR2(200 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_TIPO_CLIENTE VARCHAR2(2 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_TAG_CUIT VARCHAR2(13 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_CICLO_FACTURACION NUMBER(2,0);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_MARKETING_CUSTOMER_GROUP VARCHAR2(4 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_TIPO_FACTURA VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD TAG_IMPORTE_ORIGINAL NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_FECHA_VENCIMIENTO_MORA DATE;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_INDICADOR_PETICION_CORTE VARCHAR2(1 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRED_CODIGO_TARIFA VARCHAR2(5 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD DATOS_CLIENTE_CODIGO NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD CRE_CODIGO_CLIENTE NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD ACUERDO_FACTURACION VARCHAR2(20 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD ACUERDO_GRAL_LINEA NUMBER(10,0);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO
ADD ESTADO_ACUERDO_FACT VARCHAR2(20 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CODIGO_CLIENTE NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD MEDIO_PAGO_CUENTA NUMBER(3,0);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD MEDIO_PAGO_TIPO_CREDITO VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD TIPO_COMPROBANTE VARCHAR2(3 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD MEDIO_PAGO_CLASE_COMPROBANTE CHAR(1 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD SUCURSAL_COMPROBANTE VARCHAR2(4 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD NUMERO_COMPROBANTE VARCHAR2(8 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD NRO_REFERENCIA_MIC NUMBER(15,0);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_TIPO_REMANENTE NUMBER(1,0);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD IMPORTE NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD SALDO NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD FECHA_ALTA DATE;

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD FECHA_EMISION DATE;

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD FECHA_VENCIMIENTO DATE;

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD FECHA_ULTIMO_MOVIMIENTO DATE;

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_MARCA_RECLAMO VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_MARCA_CYQ VARCHAR2(50 BYTE);


ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD ESTADO_ORIGEN VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_RAZON_SOCIAL_CLIENTE VARCHAR2(200 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_TIPO_CLIENTE VARCHAR2(2 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_TAG_CUIT VARCHAR2(13 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_CICLO_FACTURACION NUMBER(2,0);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_MARKETING_CUSTOMER_GROUP VARCHAR2(4 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_TIPO_FACTURA VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD TAG_IMPORTE_ORIGINAL NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_FECHA_VENCIMIENTO_MORA DATE;

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_INDICADOR_PETICION_CORTE VARCHAR2(1 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS
ADD CRED_CODIGO_TARIFA VARCHAR2(5 BYTE);

ALTER TABLE SHV_WF_TAREA_OPERACION_MASIVA
ADD IMPORTE NUMBER(15,2);

ALTER TABLE SHV_WF_TAREA_OPERACION_MASIVA
ADD REFERENCIA VARCHAR2(40);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD CODIGO_CLIENTE NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD CUENTA_DEBITO NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD TIPO_DUC VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD ESTADO_DUC VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD ACUERDO VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD CLASE_COMPROBANTE CHAR(1 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD SUCURSAL_COMPROBANTE VARCHAR2(4 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD NUMERO_COMPROBANTE VARCHAR2(8 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD NUMERO_REFERENCIA_MIC VARCHAR2(15 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD FECHA_VENCIMIENTO DATE;

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD IMPORTE_PRIMER_VENCIMIENTO NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD IMPORTE_SEGUNDO_VENCIMIENTO NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD SALDO_PRIMER_VENCIMIENTO NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD ESTADO_ACUERDO_FACTURACION VARCHAR2(20 BYTE);
 
ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD ESTADO_CONCEPTO_TERCEROS VARCHAR2(20 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD IMP_TERCEROS_TRANSFERIBLES NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD IMP_PRIMER_VENC_CON_TERCEROS NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD IMPORTE_SEG_VENC_TERCEROS NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD CODIGO_ESTADO_FACTURA VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD MARCA_RECLAMO VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD DEB_MARCA_CYQ VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD FECHA_EMISION DATE;

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD IMP_GRAL_NUMERO_CONVENIO NUMBER(3,0);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD IMP_GRAL_FECHA_ULT_PAGO_PARC DATE;

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD IMP_GRAL_FECHA_ULT_PUESTA_COB DATE;

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD RAZON_SOCIAL_CLIENTE VARCHAR2(200 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD TIPO_CLIENTE VARCHAR2(2 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD DEB_TAG_CUIT VARCHAR2(200 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD CICLO_FACTURACION NUMBER(2,0);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD MARKETING_CUSTOMER_GROUP VARCHAR2(4 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD TIPO_FACTURA VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD FECHA_VENCIMIENTO_MORA DATE;

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD INDICADOR_PETICION_CORTE VARCHAR2(1 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD CODIGO_TARIFA VARCHAR2(5 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD SALDO_TER_FINANCIA_NO_TRANSF NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD SALDO_TER_FINANCIA_TRANSF NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD SALDO_TER_NO_FINANCIA_TRANSF NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD CLIENTE_CODIGO_CLIENTE NUMBER;


ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD INTERESES_TRASLA_REGU NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD INTERESES_TRASLA_NO_REGU NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD INTERESES_BONIF_REGU NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD INTERESES_BONIF_NO_REGU NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_IMPUTADO_COD_CLIENTE NUMBER(20,0);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_IMPUTADO_GRAL_CUENTA_DEB NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_IMPUTADO_GRAL_TIPO_DOC VARCHAR2(8 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_IMPUTADO_GRAL_TIPO_DUC VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_IMPUTADO_GRAL_ESTADO_DUC VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_IMPUTADO_GRAL_ACUERDO VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_IMPUTADO_GRAL_CLASE_COMP CHAR(1 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_IMPUTADO_GRAL_SUC_COMP VARCHAR2(4 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_IMPUTADO_GRAL_NUM_COMP VARCHAR2(8 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_IMPUTADO_GRAL_NUM_REF_MIC VARCHAR2(15 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD FECHA_VENCIMIENTO DATE;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMPORTE_PRIMER_VENCIMIENTO NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMPORTE_SEGUNDO_VENCIMIENTO NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD SALDO_PRIMER_VENCIMIENTO NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_ESTADO_ACUERDO_FACT VARCHAR2(20 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD ESTADO_CONCEPTO_TERCEROS VARCHAR2(20 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD POSIBILIDAD_DESTRANFERENCIA VARCHAR2(2 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMP_TERCEROS_TRANSFERIBLES NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMP_PRIMER_VENC_CON_TERCEROS NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMPORTE_SEG_VENC_TERCEROS NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CODIGO_ESTADO_FACTURA VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_MARCA_RECLAMO VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_MARCA_CYQ VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMP_GRAL_FECHA_EMISION DATE;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMP_GRAL_NUMERO_CONVENIO NUMBER(3,0);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMP_GRAL_CUOTA NUMBER(3,0);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMP_GRAL_FECHA_ULT_PAGO_PARC DATE;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMP_GRAL_FECHA_ULT_PUESTA_COB DATE;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_RAZON_SOCIAL_CLIENTE VARCHAR2(200 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_TIPO_CLIENTE VARCHAR2(2 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_TAG_CUIT VARCHAR2(200 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_CICLO_FACTURACION NUMBER(2,0);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_MARKETING_CUSTOMER_GROUP VARCHAR2(4 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_TIPO_FACTURA VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_FECHA_VENCIMIENTO_MORA DATE;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_INDICADOR_PETICION_CORTE VARCHAR2(1 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DEB_CODIGO_TARIFA VARCHAR2(5 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD SALDO_TER_FINANCIA_NO_TRANSF NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD SALDO_TER_FINANCIA_TRANSF NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD SALDO_TER_NO_FINANCIA_TRANSF NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD MEDIO_PAGO_CUENTA NUMBER(3,0);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD MEDIO_PAGO_TIPO_CREDITO VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD TIPO_COMPROBANTE VARCHAR2(3 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD MEDIO_PAGO_CLASE_COMPROBANTE CHAR(1 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD SUCURSAL_COMPROBANTE VARCHAR2(4 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD NUMERO_COMPROBANTE VARCHAR2(8 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD NRO_REFERENCIA_MIC NUMBER(15,0);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_TIPO_REMANENTE NUMBER(1,0);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD IMPORTE NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD SALDO NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD FECHA_ALTA DATE;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD FECHA_EMISION DATE;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRE_FECHA_VENCIMIENTO DATE;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD FECHA_ULTIMO_MOVIMIENTO DATE;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_MARCA_RECLAMO VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_MARCA_CYQ VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD ESTADO_ORIGEN VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_RAZON_SOCIAL_CLIENTE VARCHAR2(200 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_TIPO_CLIENTE VARCHAR2(2 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_TAG_CUIT VARCHAR2(13 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_CICLO_FACTURACION NUMBER(2,0);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_MARKETING_CUSTOMER_GROUP VARCHAR2(4 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_TIPO_FACTURA VARCHAR2(50 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD TAG_IMPORTE_ORIGINAL NUMBER(17,4);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_FECHA_VENCIMIENTO_MORA DATE;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_INDICADOR_PETICION_CORTE VARCHAR2(1 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CRED_CODIGO_TARIFA VARCHAR2(5 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD DATOS_CLIENTE_CODIGO NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CODIGO_CLIENTE NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD ACUERDO_FACTURACION VARCHAR2(20 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD ACUERDO_GRAL_LINEA NUMBER(10,0);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD ESTADO_ACUERDO_FACT VARCHAR2(20 BYTE);

ALTER TABLE SHV_MAS_REGISTRO
ADD ID_TRANSACCION NUMBER;

ALTER TABLE SHV_MAS_REGISTRO
ADD ID_COBRANZA NUMBER;

ALTER TABLE SHV_MAS_REGISTRO
ADD FECHA_VALOR_COBRANZA DATE;

--- Se agrego para las correcciones luego de las pruebas previas a la implementacion

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA
ADD CREDITO_MIGRADO VARCHAR2(2 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD NUMERO_CONVENIO NUMBER(3,0);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD IMP_GRAL_CUOTA NUMBER(15,2);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO
ADD POSIBILIDAD_DESTRANFERENCIA VARCHAR2(2 BYTE);

Exit;
