--SupervisorOperacionMasiva
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (253, 46 , 2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (254, 45 , 2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (255, 44 , 2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (256, 43 , 2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (257, 42 , 2);

--AnalistaOperacionMasiva
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (258, 41 , 2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (259, 40 , 2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (260, 39 , 2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (261, 38 , 2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (262, 37 , 2);

insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO,TIPO_WORKFLOW,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN) values ('MAS_CONFIGURACION','OPERACION_MASIVA','Operacion Masiva en Configuracion','SHIVA');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO,TIPO_WORKFLOW,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN) values ('MAS_PENDIENTE_PROCESAR','OPERACION_MASIVA','Operacion Masiva en Proceso de Imputacion','SHIVA');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO,TIPO_WORKFLOW,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN) values ('MAS_PROCESADA','OPERACION_MASIVA','Operacion Masiva Procesada','SHIVA');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO,TIPO_WORKFLOW,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN) values ('MAS_ERROR','OPERACION_MASIVA','Operacion Masiva en Error','SHIVA');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO,TIPO_WORKFLOW,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN) values ('MAS_PENDIENTE_APROBACION','OPERACION_MASIVA','Operacion Masiva Pendiente de Aprobacion','SHIVA');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO,TIPO_WORKFLOW,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN) values ('MAS_APROBACION_RECHAZADA','OPERACION_MASIVA','Aprobacion Operacion Masiva Rechazada','SHIVA');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO,TIPO_WORKFLOW,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN) values ('MAS_CANCELADA','OPERACION_MASIVA','Operacion Masiva Cancelada','SHIVA');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO,TIPO_WORKFLOW,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN) values ('MAS_PROCESADA_PARCIALMENTE','OPERACION_MASIVA','Operacion Masiva Procesada Parcialmente','SHIVA');


commit;

Exit;