INSERT INTO SHV_PARAM_SEGMENTO_EMPRESA VALUES (1, 'TA', 'OGC');
INSERT INTO SHV_PARAM_SEGMENTO_EMPRESA VALUES (2, 'TA', 'OYP');
INSERT INTO SHV_PARAM_SEGMENTO_EMPRESA VALUES (3, 'TA', 'OGE');
INSERT INTO SHV_PARAM_SEGMENTO_EMPRESA VALUES (4, 'TA', 'OTP');
INSERT INTO SHV_PARAM_SEGMENTO_EMPRESA VALUES (5, 'TA', 'OCO');

INSERT INTO SHV_PARAM_ACUERDO VALUES (28,1,'Acuerdo 28','1', '1');
INSERT INTO SHV_PARAM_ACUERDO VALUES (29,3,'Acuerdo 29','2', '1');
INSERT INTO SHV_PARAM_ACUERDO VALUES (33,2,'Acuerdo 33','3', '1');
INSERT INTO SHV_PARAM_ACUERDO VALUES (34,4,'Acuerdo 34','4', '1');
INSERT INTO SHV_PARAM_ACUERDO VALUES (125,5,'Acuerdo 125','5', '1');
INSERT INTO SHV_PARAM_ACUERDO VALUES (107,6,'Acuerdo 107','6', '0');

INSERT INTO SHV_PARAM_BANCO_CUENTA VALUES (1,'0072', '3063945373800428');
INSERT INTO SHV_PARAM_BANCO_CUENTA VALUES (2,'0072', '3063945373800433');
INSERT INTO SHV_PARAM_BANCO_CUENTA VALUES (3,'0072', '3063945373800429');
INSERT INTO SHV_PARAM_BANCO_CUENTA VALUES (4,'0072', '3063945373800434');
INSERT INTO SHV_PARAM_BANCO_CUENTA VALUES (5,'0072', '3063945373800125');
INSERT INTO SHV_PARAM_BANCO_CUENTA VALUES (6,'0072', '3063945373800107');

INSERT INTO SHV_PARAM_BANCO VALUES ('0072','SANTANDER RIO','20-31605259-7','234234','TA');

INSERT INTO SHV_PARAM_TIPO_GESTION VALUES (1, 1,null,28,1);
INSERT INTO SHV_PARAM_TIPO_GESTION VALUES (2, 3,null,28,1);
INSERT INTO SHV_PARAM_TIPO_GESTION VALUES (3, 5,null,29,2);
INSERT INTO SHV_PARAM_TIPO_GESTION VALUES (4, 3,null,29,2);
INSERT INTO SHV_PARAM_TIPO_GESTION VALUES (5, 4,null,29,2);
INSERT INTO SHV_PARAM_TIPO_GESTION VALUES (6, 2,null,33,2);
INSERT INTO SHV_PARAM_TIPO_GESTION VALUES (7, 1,null,33,2);

INSERT INTO SHV_PARAM_TIPO_GESTION VALUES (8, 1,null,29,1);

INSERT INTO SHV_PARAM_ORIGEN VALUES (1, 'Cajero Pagador');
INSERT INTO SHV_PARAM_ORIGEN VALUES (2, 'Cliente');

INSERT INTO SHV_SEG_PERFIL_APLICATIVO VALUES ('1', 'Analista');
INSERT INTO SHV_SEG_PERFIL_APLICATIVO VALUES ('2', 'Supervisor');
INSERT INTO SHV_SEG_PERFIL_APLICATIVO VALUES ('3', 'AdminAVC');
INSERT INTO SHV_SEG_PERFIL_APLICATIVO VALUES ('4', 'AdminTalonario');
INSERT INTO SHV_SEG_PERFIL_APLICATIVO VALUES ('5', 'Conciliador');

INSERT INTO SHV_PARAM_EMPRESA VALUES ('TA', 'Telecom Argentina');

INSERT INTO SHV_PARAM_SEGMENTO VALUES ('OGC', 'Grandes Clientes');
INSERT INTO SHV_PARAM_SEGMENTO VALUES ('OYP', 'Whole Sale');
INSERT INTO SHV_PARAM_SEGMENTO VALUES ('OGE', 'PyME');
INSERT INTO SHV_PARAM_SEGMENTO VALUES ('OTP', 'Telefonía Pública');
INSERT INTO SHV_PARAM_SEGMENTO VALUES ('OCO', 'Residencial');

INSERT INTO SHV_PARAM_MOTIVO VALUES (1, 'Concursos y Quiebras');
INSERT INTO SHV_PARAM_MOTIVO VALUES (2, 'Postbaja');
INSERT INTO SHV_PARAM_MOTIVO VALUES (3, 'Cobranza Regular');
INSERT INTO SHV_PARAM_MOTIVO VALUES (4, 'Cheque Rechazado');
INSERT INTO SHV_PARAM_MOTIVO VALUES (5, 'Pago a Cuenta');
INSERT INTO SHV_PARAM_MOTIVO VALUES (6, 'Cobro Plan de Financiación');
INSERT INTO SHV_PARAM_MOTIVO VALUES (7, 'Cheque de Garantía Corriente');

INSERT INTO SHV_SEG_PERFIL VALUES (1, 'Analista - Telecom Argentina - Grandes Clientes','1','TA','OGC');
INSERT INTO SHV_SEG_PERFIL VALUES (2, 'Analista - Telecom Argentina - Whole Sale','1','TA','OYP');
INSERT INTO SHV_SEG_PERFIL VALUES (3, 'Analista - Telecom Argentina - PyME','1','TA','OGE');
INSERT INTO SHV_SEG_PERFIL VALUES (4, 'Analista - Telecom Argentina - Telefonia Publica','1','TA','OTP');
INSERT INTO SHV_SEG_PERFIL VALUES (5, 'Analista - Telecom Argentina - Residencial','1','TA','OCO');
INSERT INTO SHV_SEG_PERFIL VALUES (6, 'Supervisor - Telecom Argentina - Grandes Clientes','2','TA','OGC');
INSERT INTO SHV_SEG_PERFIL VALUES (7, 'Supervisor - Telecom Argentina - Whole Sale','2','TA','OYP');
INSERT INTO SHV_SEG_PERFIL VALUES (8, 'Supervisor - Telecom Argentina - PyME','2','TA','OGE');
INSERT INTO SHV_SEG_PERFIL VALUES (9, 'Supervisor - Telecom Argentina - Telefonia Publica','2','TA','OTP');
INSERT INTO SHV_SEG_PERFIL VALUES (10, 'Supervisor - Telecom Argentina - Residencial','2','TA','OCO');
INSERT INTO SHV_SEG_PERFIL VALUES (11, 'Administrador de AVC','3',null,null);
INSERT INTO SHV_SEG_PERFIL VALUES (12, 'Administrador de Talonarios','4',null,null);
INSERT INTO SHV_SEG_PERFIL VALUES (13, 'Conciliador','5',null,null);

--Menu Inicio
INSERT INTO SHV_MNU_MENU VALUES (1,'Inicio','',1,null);
INSERT INTO SHV_MNU_MENU VALUES (2,'Bandeja de Entrada','bandeja-de-entrada',1,1);
--Menu Boletas Sin Valor
INSERT INTO SHV_MNU_MENU VALUES (3,'Boletas sin Valor','',2,null);
INSERT INTO SHV_MNU_MENU VALUES (4,'Alta de boletas','boletas-alta',1,3);
INSERT INTO SHV_MNU_MENU VALUES (5,'Búsqueda de boletas','boletas-busqueda',2,3);
--Menu Valores
INSERT INTO SHV_MNU_MENU VALUES (6,'Valores','',3,null);
INSERT INTO SHV_MNU_MENU VALUES (7,'Alta de valores','valores-alta',1,6);
INSERT INTO SHV_MNU_MENU VALUES (8,'Búsqueda de valores','valores-busqueda',2,6);
INSERT INTO SHV_MNU_MENU VALUES (9,'Autorización de valores','valores-autorizacion',3,6);
--Menu Recibos Preimpresos
INSERT INTO SHV_MNU_MENU VALUES (10,'Talonarios','',4,null);
INSERT INTO SHV_MNU_MENU VALUES (11,'Alta de talonarios','talonario-alta',1,10);
INSERT INTO SHV_MNU_MENU VALUES (12,'Búsqueda de talonarios','talonario-busqueda',2,10);
INSERT INTO SHV_MNU_MENU VALUES (13,'Autorización de Rendición de talonarios','talonario-autorizacion-rendicion',3,10);
--Menu Conciliacion
INSERT INTO SHV_MNU_MENU VALUES (14,'Conciliación','',5,null);
INSERT INTO SHV_MNU_MENU VALUES (15,'Procesar archivos de valores a conciliar','procesar-archivo-registros-avc',1,14);
INSERT INTO SHV_MNU_MENU VALUES (16,'Resultado conciliación','resultado-conciliacion',2,14);
INSERT INTO SHV_MNU_MENU VALUES (17,'Creación de valores a partir de registros AVC','creacion-valores-a-partir-registros-avc',3,14);
INSERT INTO SHV_MNU_MENU VALUES (18,'Confirmación de anulación de registros AVC','confirmar-anulacion-registro-avc',4,14);

--Menu para el perfil [Analista_*]
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (1,1,4);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (2,1,5);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (3,2,4);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (4,2,5);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (5,3,4);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (6,3,5);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (7,4,4);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (8,5,5);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (9,5,4);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (10,5,5);

--Menu para el perfil [Supervisor_*]
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (11,6,5);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (12,7,5);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (13,8,5);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (14,9,5);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (15,10,5);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (20,6,12);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (23,7,12);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (26,8,12);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (29,9,12);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (32,10,12);

-- Menu para el perfil [Administrador de Talonarios_*]
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (16,12,11);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (17,12,12);
INSERT INTO SHV_MNU_MENU_PERFIL VALUES (18,12,13);

