CREATE OR REPLACE VIEW SHV_SOP_BUSQUEDA_VALORES(ID_VALOR, EMPRESA, SEGMENTO, ID_CLIENTE_LEGADO, RAZON_SOCIAL_CLIENTE_AGRUPADOR, TIPO_VALOR, ESTADO_VALOR, ORIGEN, ACUERDO, NRO_VALOR, IMPORTE, BD_IMPRESA, BD_ENVIADA_MAIL, FECHA_ALTA, ID_ANALISTA, NRO_RECIBO, ID_CONSTANCIA_RECEPCION, OPERACION_ASOCIADA, FACTURA_RELACIONADA, DOCUMENTACION_ORIG_RECIBIDA, MOTIVO, BANCO_DEPOSITO, ID_COPROPIETARIO, USUARIO_AUTORIZACION, NUMERO_DOCUMENTO_CONTABLE, MOTIVO_SUSPENSION, EJECUTIVO, ASISTENTE, SALDO_DISPONIBLE, FECHA_INGRESO_RECIBO, FECHA_EMISION, FECHA_TRANSFERENCIA, VALOR_PADRE, ARCHIVO_DE_VALORES_A_CONCILIAR, FECHA_DEPOSITO, FECHA_ULTIMO_ESTADO, FECHA_DISPONIBLE, NRO_BOLETA, DESCRIPCION_BANCO_ORIGEN, FECHA_VENCIMIENTO, ID_TIPO_RETENCION, DESCRIPCION_TIPO_RETENCION, NRO_CUIT_RETENCION, PROVINCIA_RETENCION, REFERENCIA_VALOR, ID_ANALISTA_TEAM_COMERCIAL, ID_SUPERVISOR_TEAM_COMERCIAL,
  ID_GERENTE_REG_TEAM_COMERCIAL, CODIGO_ORGANISMO, OBSERVACIONES, ID_ESTADO_VALOR, ID_TIPO_VALOR, ID_ORIGEN, ID_EMPRESA, ID_SEGMENTO, FECHA_VALOR, COBRO_FORMATEADO, ID_BOLETA)
AS
  (
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO EFECTIVO Sprint3, incluye defecto 133
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL AS FACTURA_RELACIONADA ,
    NVL (SVVE.DOCUMENTACION_ORIG_RECIBIDA, 'NO') DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVVE.FECHA_DEPOSITO                            AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SVVE.NUMERO_BOLETA                  AS NRO_BOLETA ,
    NULL                                AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    TO_CHAR(SVVE.NUMERO_BOLETA)         AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR) AS COBRO_FORMATEADO,
    NULL                               AS ID_BOLETA
  FROM SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_EFECTIVO SVVE
  ON SVV.ID_VALOR = SVVE.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO CHEQUE
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL AS FACTURA_RELACIONADA ,
    NVL (SVVC.DOCUMENTACION_ORIG_RECIBIDA, 'NO') DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVVC.FECHA_DEPOSITO                            AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SVVC.NUMERO_BOLETA                  AS NRO_BOLETA ,
    SPBORIGEN.DESCRIPCION               AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    TO_CHAR(SVVC.NUMERO_CHEQUE)         AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR) AS COBRO_FORMATEADO,
    NULL                               AS ID_BOLETA
  FROM SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_CHEQUE SVVC
  ON SVV.ID_VALOR = SVVC.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPBORIGEN
  ON SVVC.ID_BANCO_ORIGEN = SPBORIGEN.ID_BANCO
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO CHEQUE DIFERIDO
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL AS FACTURA_RELACIONADA ,
    NVL (SVVCPD.DOCUMENTACION_ORIG_RECIBIDA, 'NO') DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVVCPD.FECHA_DEPOSITO                          AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SVVCPD.NUMERO_BOLETA                AS NRO_BOLETA ,
    SPBORIGEN.DESCRIPCION               AS DESCRIPCION_BANCO_ORIGEN ,
    SVVCPD.FECHA_VENCIMIENTO            AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    TO_CHAR(SVVCPD.NUMERO_CHEQUE)       AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR) AS COBRO_FORMATEADO,
    NULL                               AS ID_BOLETA
  FROM
    --FABIO.GIAQUINTA.RUIZ 13/08/2014
    --JOINS ORDENADOS POR TABLA CON MAYOR CANTIDAD DE REGISTROS
    SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_CHEQUE_PD SVVCPD
  ON SVV.ID_VALOR = SVVCPD.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO SPBORIGEN
  ON SVVCPD.ID_BANCO_ORIGEN = SPBORIGEN.ID_BANCO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO TRANSFERENCIAS
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL AS FACTURA_RELACIONADA ,
    NVL (SVVT.DOCUMENTACION_ORIG_RECIBIDA, 'NO') DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    SVVT.FECHA_TRANSFERENCIA                       AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    NULL                                           AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    NULL                                AS NRO_BOLETA ,
    NULL                                AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    TO_CHAR(SVVT.NUMERO_REFERENCIA)     AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR) AS COBRO_FORMATEADO,
    NULL                               AS ID_BOLETA
  FROM
    --FABIO.GIAQUINTA.RUIZ 13/08/2014
    --JOINS ORDENADOS POR TABLA CON MAYOR CANTIDAD DE REGISTROS
    SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_TRANSFERENCIA SVVT
  ON SVV.ID_VALOR = SVVT.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO SPBORIGEN
  ON SVVT.ID_BANCO_ORIGEN = SPBORIGEN.ID_BANCO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO INTERDEPOSITO
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL                 AS FACTURA_RELACIONADA ,
    NULL                 AS DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    NULL                                           AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    NULL                                AS NRO_BOLETA ,
    NULL                                AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    TO_CHAR(SVVI.NUMERO_INTERDEPOSITO)  AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    SVVI.CODIGO_ORGANISMO               AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR) AS COBRO_FORMATEADO,
    NULL                               AS ID_BOLETA
  FROM
    --FABIO.GIAQUINTA.RUIZ 13/08/2014
    --JOINS ORDENADOS POR TABLA CON MAYOR CANTIDAD DE REGISTROS
    SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_INTERDEPOSITO SVVI
  ON SVV.ID_VALOR = SVVI.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO RETENCIONES
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    NULL             AS ORIGEN ,
    NULL             AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    DECODE (SVVR.ID_TIPO_COMPROBANTE, NULL, NULL, (SPTC.DESCRIPCION
    ||' '
    ||SPTLC.DESCRIPCION
    ||' '
    ||SVVR.SUCURSAL_COMPROBANTE
    ||'-'
    ||SVVR.NUMERO_COMPROBANTE)) AS FACTURA_RELACIONADA -- >> PARA RETENCIONES
    ,
    NULL                 AS DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    NULL                 AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    TO_CHAR(SVVR.FECHA_EMISION, 'DD/MM/YYYY')      AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    NULL                                           AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    NULL                                   AS NRO_BOLETA ,
    NULL                                   AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                   AS FECHA_VENCIMIENTO ,
    SPTRI.ID_TIPO_RETENCION_IMPUESTO       AS ID_TIPO_RETENCION,
    SPTRI.DESCRIPCION                      AS DESCRIPCION_TIPO_RETENCION,
    SVVR.CUIT                              AS NRO_CUIT_RETENCION,
    SPJ.DESCRIPCION                        AS PROVINCIA_RETENCION,
    TO_CHAR(SVVR.NRO_CONSTANCIA_RETENCION) AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS      AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS    AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL             AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                   AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                      AS OBSERVACIONES,
    --DATOS DE USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR) AS COBRO_FORMATEADO,
    NULL                               AS ID_BOLETA
  FROM
    --FABIO.GIAQUINTA.RUIZ 13/08/2014
    --JOINS ORDENADOS POR TABLA CON MAYOR CANTIDAD DE REGISTROS
    SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_RETENCION SVVR
  ON SVV.ID_VALOR = SVVR.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_TIPO_COMPROBANTE SPTC
  ON SVVR.ID_TIPO_COMPROBANTE = SPTC.ID_TIPO_COMPROBANTE
  LEFT JOIN SHV_PARAM_TIPO_LETRA_COMP SPTLC
  ON SVVR.ID_TIPO_LETRA_COMPROBANTE = SPTLC.ID_TIPO_LETRA_COMPROBANTE
  LEFT JOIN SHV_PARAM_JURISDICCION SPJ
  ON SVVR.ID_JURISDICCION = SPJ.ID_JURISDICCION
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  LEFT JOIN SHV_PARAM_TIPO_RET_IMPUESTO SPTRI
  ON SVVR.ID_TIPO_RETENCION_IMPUESTO = SPTRI.ID_TIPO_RETENCION_IMPUESTO
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- BOLETA DEPOSITO EFECTIVO
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    SBB.IMPRESION_ESTADO                          AS BD_IMPRESA ,
    SBB.EMAIL_ENVIO_ESTADO                        AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    STRP.NUMERO_RECIBO                            AS NRO_RECIBO ,
    SVCRV.ID_CONSTANCIA_RECEPCION                 AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL                 AS FACTURA_RELACIONADA ,
    NULL                 AS DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    SVBDE.FECHA_RECIBO                             AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVBDE.FECHA_DEPOSITO                           AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SBB.NUMERO_BOLETA                   AS NRO_BOLETA ,
    NULL                                AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL      							AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    TO_CHAR(SBB.NUMERO_BOLETA)          AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR) AS COBRO_FORMATEADO,
    SBB.ID_BOLETA                      AS ID_BOLETA
  FROM
    --FABIO.GIAQUINTA.RUIZ 13/08/2014
    --JOINS ORDENADOS POR TABLA CON MAYOR CANTIDAD DE REGISTROS
    SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_BOLETA_DEP_EFECTIVO SVBDE
  ON SVV.ID_VALOR = SVBDE.ID_VALOR
  INNER JOIN SHV_BOL_BOLETA SBB
  ON SVBDE.ID_BOLETA = SBB.ID_BOLETA
  LEFT JOIN SHV_TAL_RECIBO_PREIMPRESO STRP
  ON STRP.ID_RECIBO_PREIMPRESO = SVBDE.ID_RECIBO_PREIMPRESO
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_VAL_CONSTANCIA_RECEP_VALOR SVCRV
  ON SVV.ID_VALOR = SVCRV.ID_VALOR
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- BOLETA DEPOSITO CHEQUE
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    SBB.IMPRESION_ESTADO                          AS BD_IMPRESA ,
    SBB.EMAIL_ENVIO_ESTADO                        AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    STRP.NUMERO_RECIBO                            AS NRO_RECIBO ,
    SVCRV.ID_CONSTANCIA_RECEPCION                 AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL                 AS FACTURA_RELACIONADA ,
    NULL                 AS DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    SVBDC.FECHA_RECIBO                             AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVBDC.FECHA_DEPOSITO                           AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SBB.NUMERO_BOLETA                   AS NRO_BOLETA ,
    SPBORIGEN.DESCRIPCION               AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL      							AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    TO_CHAR(SVBDC.NUMERO_CHEQUE)        AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR) AS COBRO_FORMATEADO,
    SBB.ID_BOLETA                      AS ID_BOLETA
  FROM SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  LEFT JOIN SHV_VAL_BOLETA_DEP_CHEQUE SVBDC
  ON SVV.ID_VALOR = SVBDC.ID_VALOR
  INNER JOIN SHV_BOL_BOLETA SBB
  ON SVBDC.ID_BOLETA = SBB.ID_BOLETA
  LEFT JOIN SHV_TAL_RECIBO_PREIMPRESO STRP
  ON STRP.ID_RECIBO_PREIMPRESO = SVBDC.ID_RECIBO_PREIMPRESO
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_VAL_CONSTANCIA_RECEP_VALOR SVCRV
  ON SVV.ID_VALOR = SVCRV.ID_VALOR
  LEFT JOIN SHV_PARAM_BANCO SPBORIGEN
  ON SVBDC.ID_BANCO_ORIGEN = SPBORIGEN.ID_BANCO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- BOLETA DEPOSITO CHEQUE DIFERIDO
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    SBB.IMPRESION_ESTADO                          AS BD_IMPRESA ,
    SBB.EMAIL_ENVIO_ESTADO                        AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    STRP.NUMERO_RECIBO                            AS NRO_RECIBO ,
    SVCRV.ID_CONSTANCIA_RECEPCION                 AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL                 AS FACTURA_RELACIONADA ,
    NULL                 AS DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    SVBDCPD.FECHA_RECIBO                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVBDCPD.FECHA_DEPOSITO                         AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SBB.NUMERO_BOLETA                   AS NRO_BOLETA ,
    SPBORIGEN.DESCRIPCION               AS DESCRIPCION_BANCO_ORIGEN ,
    SVBDCPD.FECHA_VENCIMIENTO           AS FECHA_VENCIMIENTO ,
    NULL      							AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    TO_CHAR(SVBDCPD.NUMERO_CHEQUE)      AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR) AS COBRO_FORMATEADO,
    SBB.ID_BOLETA                      AS ID_BOLETA
  FROM SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_BOLETA_DEP_CHEQUE_PD SVBDCPD
  ON SVV.ID_VALOR = SVBDCPD.ID_VALOR
  INNER JOIN SHV_BOL_BOLETA SBB
  ON SVBDCPD.ID_BOLETA = SBB.ID_BOLETA
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_TAL_RECIBO_PREIMPRESO STRP
  ON STRP.ID_RECIBO_PREIMPRESO = SVBDCPD.ID_RECIBO_PREIMPRESO
  LEFT JOIN SHV_VAL_CONSTANCIA_RECEP_VALOR SVCRV
  ON SVV.ID_VALOR = SVCRV.ID_VALOR
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO SPBORIGEN
  ON SVBDCPD.ID_BANCO_ORIGEN = SPBORIGEN.ID_BANCO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  );