ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO ADD CLASE_COMPROBANTE CHAR(1 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO ADD SUCURSAL_COMPROBANTE VARCHAR2(4 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO ADD NUMERO_COMPROBANTE VARCHAR2(8 BYTE);

Exit;