package ar.com.telecom.shiva.presentacion.wsdl.deimos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:49.957-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "ShivaWebService", 
                  wsdlLocation = "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/deimos/WebServiceDeimos.wsdl",
                  targetNamespace = "http://shiva.ws.intelap.com/") 
public class ShivaWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://shiva.ws.intelap.com/", "ShivaWebService");
    public final static QName ShivaWebServicePort = new QName("http://shiva.ws.intelap.com/", "ShivaWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/deimos/WebServiceDeimos.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ShivaWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/deimos/WebServiceDeimos.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ShivaWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ShivaWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShivaWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ShivaWebService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ShivaWebService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ShivaWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ShivaWebService
     */
    @WebEndpoint(name = "ShivaWebServicePort")
    public ShivaWebService getShivaWebServicePort() {
        return super.getPort(ShivaWebServicePort, ShivaWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShivaWebService
     */
    @WebEndpoint(name = "ShivaWebServicePort")
    public ShivaWebService getShivaWebServicePort(WebServiceFeature... features) {
        return super.getPort(ShivaWebServicePort, ShivaWebService.class, features);
    }

}
