package ar.com.telecom.shiva.presentacion.wsdl.deimos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:49.949-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://shiva.ws.intelap.com/", name = "ShivaWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ShivaWebService {

    @WebResult(name = "RespuestaDesapropiacionDeimos", targetNamespace = "")
    @RequestWrapper(localName = "DesapropiacionDocumento", targetNamespace = "http://shiva.ws.intelap.com/", className = "ar.com.telecom.shiva.presentacion.wsdl.deimos.DesapropiacionDocumento")
    @WebMethod(operationName = "DesapropiacionDocumento")
    @ResponseWrapper(localName = "DesapropiacionDocumentoResponse", targetNamespace = "http://shiva.ws.intelap.com/", className = "ar.com.telecom.shiva.presentacion.wsdl.deimos.DesapropiacionDocumentoResponse")
    public ar.com.telecom.shiva.presentacion.wsdl.deimos.RespuestaDesapropiacionDeimos desapropiacionDocumento(
        @WebParam(name = "DesapropiacionDeimos", targetNamespace = "")
        ar.com.telecom.shiva.presentacion.wsdl.deimos.DesapropiacionDeimos desapropiacionDeimos
    );

    @WebResult(name = "ResultadoConsultaEstadoDeuda", targetNamespace = "")
    @RequestWrapper(localName = "ConsultaEstadoDocumento", targetNamespace = "http://shiva.ws.intelap.com/", className = "ar.com.telecom.shiva.presentacion.wsdl.deimos.ConsultaEstadoDocumento")
    @WebMethod(operationName = "ConsultaEstadoDocumento")
    @ResponseWrapper(localName = "ConsultaEstadoDocumentoResponse", targetNamespace = "http://shiva.ws.intelap.com/", className = "ar.com.telecom.shiva.presentacion.wsdl.deimos.ConsultaEstadoDocumentoResponse")
    public ar.com.telecom.shiva.presentacion.wsdl.deimos.ResultadoConsultaEstadoDeuda consultaEstadoDocumento(
        @WebParam(name = "ConsultaEstadoDeudaFiltroDeimos", targetNamespace = "")
        ar.com.telecom.shiva.presentacion.wsdl.deimos.ConsultaEstadoDeudaFiltroDeimos consultaEstadoDeudaFiltroDeimos
    );

    @WebResult(name = "RespuestaApropiacionDeimos", targetNamespace = "")
    @RequestWrapper(localName = "ApropiacionDocumento", targetNamespace = "http://shiva.ws.intelap.com/", className = "ar.com.telecom.shiva.presentacion.wsdl.deimos.ApropiacionDocumento")
    @WebMethod(operationName = "ApropiacionDocumento")
    @ResponseWrapper(localName = "ApropiacionDocumentoResponse", targetNamespace = "http://shiva.ws.intelap.com/", className = "ar.com.telecom.shiva.presentacion.wsdl.deimos.ApropiacionDocumentoResponse")
    public ar.com.telecom.shiva.presentacion.wsdl.deimos.RespuestaApropiacionDeimos apropiacionDocumento(
        @WebParam(name = "ApropiacionDeimos", targetNamespace = "")
        ar.com.telecom.shiva.presentacion.wsdl.deimos.ApropiacionDeimos apropiacionDeimos
    );
}
