--UPDATES PARA SETEAR TODOS LOS CAMPOS NUEVOS Y NO QUEDEN EN NULL

UPDATE SHV_COB_DESCOBRO SET MONEDA_OPERACION ='PES' WHERE MONEDA_OPERACION IS NULL;

--SET MONEDA OPERACION NOT NULL

ALTER TABLE SHV_COB_DESCOBRO MODIFY MONEDA_OPERACION VARCHAR2(3) NOT NULL;

Exit;