	--UPDATES PARA SETEAR TODOS LOS CAMPOS NUEVOS Y NO QUEDEN EN NULL
UPDATE SHV_COB_ED_COBRO set MONEDA_OPERACION ='PES' WHERE MONEDA_OPERACION IS NULL;

UPDATE SHV_COB_COBRO SET MONEDA_OPERACION ='PES' WHERE MONEDA_OPERACION IS NULL;

--UPDATE SHV_COB_DESCOBRO SET MONEDA_OPERACION ='PES' WHERE MONEDA_OPERACION IS NULL;

UPDATE SHV_COB_OPERACION SET MONEDA_OPERACION ='PES' WHERE MONEDA_OPERACION IS NULL;

UPDATE SHV_COB_FACTURA SET MONEDA_IMPORTE_COBRAR ='PES' WHERE MONEDA_IMPORTE_COBRAR IS NULL;

UPDATE SHV_COB_MED_PAGO SET MONEDA_IMPORTE ='PES' WHERE MONEDA_IMPORTE IS NULL;

UPDATE SHV_COB_ED_DEBITO SET MONEDA_IMPORTE_A_COBRAR ='PES' WHERE MONEDA_IMPORTE_A_COBRAR IS NULL;

UPDATE SHV_COB_ED_CREDITO SET MONEDA_IMPORTE_A_UTILIZAR ='PES' WHERE MONEDA_IMPORTE_A_UTILIZAR IS NULL;

UPDATE SHV_COB_ED_OTROS_MEDIO_PAGO SET MONEDA_IMPORTE_A_UTILIZAR ='PES' WHERE MONEDA_IMPORTE_A_UTILIZAR IS NULL;

UPDATE SHV_WF_TAREA_COBRO SET MONEDA_IMPORTE ='PES' WHERE MONEDA_IMPORTE IS NULL;

--UPDATE SHV_WF_TAREA_DESCOBRO SET MONEDA_IMPORTE ='PES' WHERE MONEDA_IMPORTE IS NULL;

--SET MONEDA OPERACION NOT NULL
ALTER TABLE SHV_COB_ED_COBRO MODIFY MONEDA_OPERACION VARCHAR2(3) NOT NULL;

ALTER TABLE SHV_COB_COBRO MODIFY MONEDA_OPERACION VARCHAR2(3) NOT NULL;

--ALTER TABLE SHV_COB_DESCOBRO MODIFY MONEDA_OPERACION VARCHAR2(3) NOT NULL;

ALTER TABLE SHV_COB_OPERACION MODIFY MONEDA_OPERACION VARCHAR2(3) NOT NULL;

ALTER TABLE SHV_COB_FACTURA MODIFY MONEDA_IMPORTE_COBRAR VARCHAR2(3) NOT NULL;

ALTER TABLE SHV_COB_MED_PAGO MODIFY MONEDA_IMPORTE VARCHAR2(3) NOT NULL;

ALTER TABLE SHV_COB_ED_DEBITO MODIFY MONEDA_IMPORTE_A_COBRAR VARCHAR2(3) NOT NULL;

ALTER TABLE SHV_COB_ED_CREDITO MODIFY MONEDA_IMPORTE_A_UTILIZAR VARCHAR2(3) NOT NULL;

ALTER TABLE SHV_COB_ED_OTROS_MEDIO_PAGO MODIFY MONEDA_IMPORTE_A_UTILIZAR VARCHAR2(3) NOT NULL;

ALTER TABLE SHV_WF_TAREA_COBRO MODIFY MONEDA_IMPORTE VARCHAR2(3) NOT NULL;

--ALTER TABLE SHV_WF_TAREA_DESCOBRO MODIFY MONEDA_IMPORTE VARCHAR2(3) NOT NULL;

Exit;