package ar.com.telecom.shiva.base.enumeradores;



public enum AccionesDeUsuarioEnum {
	MODIFICAR_BOLETA_SIN_VALOR,
	ANULAR_BOLETA_SIN_VALOR,
	IMPRIMIR_BOLETA_SIN_VALOR,
	ENVIAR_MAIL_BOLETA_SIN_VALOR, 
	MODIFICAR_TALONARIO, 
	RECHAZAR_TALONARIO, 
	ANULAR_TALONARIO, 
	RENDIR_TALONARIO, 
	MODIFICAR_RECIBO_PRE_IMPRESO,
	MODIFICAR_COBRO,
	ANULAR_COBRO;
	
	
}
