--Grant para funcion loguearse con el usuario que no es owner del schema	
	CREATE OR REPLACE SYNONYM SEQ_SHV_WF_WF_MARCA FOR A002018.SEQ_SHV_WF_WF_MARCA;
	CREATE OR REPLACE SYNONYM SEQ_SHV_WF_WF_MARCA_HIST FOR A002018.SEQ_SHV_WF_WF_MARCA_HIST;

	CREATE OR REPLACE SYNONYM SHV_WF_WORKFLOW_MARCA FOR A002018.SHV_WF_WORKFLOW_MARCA;
	CREATE OR REPLACE SYNONYM SHV_WF_WORKFLOW_MARCA_HIST FOR A002018.SHV_WF_WORKFLOW_MARCA;
	