ALTER TABLE SHV_COB_ED_COBRO ADD CHECKSUM_AL_SIMULAR VARCHAR2(128);

ALTER TABLE SHV_COB_ED_CLIENTE DROP COLUMN ID_SEGMENTO_AGENCIA_NEGOCIO;
ALTER TABLE SHV_COB_ED_CLIENTE ADD SEGMENTO_AGENCIA_NEGOCIO VARCHAR2(30);

/
Exit;
