------------------------------------------------------------------------------------
--Secuencias para gestion de marcas
------------------------------------------------------------------------------------
CREATE SEQUENCE SEQ_SHV_WF_WF_MARCA 
	MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEQ_SHV_WF_WF_MARCA_HIST 
	MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

------------------------------------------------------------------------------------
--Tablas para gestion de marcas
------------------------------------------------------------------------------------

DROP TABLE SHV_WF_WORKFLOW_MARCA;
CREATE TABLE SHV_WF_WORKFLOW_MARCA
  (
    "ID_WORKFLOW_MARCA"   	NUMBER NOT NULL ENABLE,
    "ID_WORKFLOW_ESTADO"   	NUMBER NOT NULL ENABLE,
    "ID_MARCA"              VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "USUARIO_CREACION" 		VARCHAR2(9 BYTE) NOT NULL ENABLE,
    "FECHA_CREACION" 		TIMESTAMP (6) NOT NULL ENABLE,
    CONSTRAINT "WORKFLOW_MARCA_PK" PRIMARY KEY ("ID_WORKFLOW_MARCA") ENABLE,
    CONSTRAINT "WORKFLOW_MARCA_WF_EST_FK" FOREIGN KEY ("ID_WORKFLOW_ESTADO") REFERENCES "SHV_WF_WORKFLOW_ESTADO" ("ID_WORKFLOW_ESTADO") ENABLE
  )
  TABLESPACE "SHIVATS";

DROP TABLE SHV_WF_WORKFLOW_MARCA_HIST;
CREATE TABLE SHV_WF_WORKFLOW_MARCA_HIST
  (
    "ID_WORKFLOW_MARCA_HIST"   	NUMBER NOT NULL ENABLE,
    "ID_WORKFLOW_ESTADO_HIST"   NUMBER NOT NULL ENABLE,
    "ID_MARCA"              	VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "USUARIO_CREACION" 			VARCHAR2(9 BYTE) NOT NULL ENABLE,
    "FECHA_CREACION" 			TIMESTAMP (6) NOT NULL ENABLE,
    CONSTRAINT "WORKFLOW_MARCA_HIST_PK" PRIMARY KEY ("ID_WORKFLOW_MARCA_HIST") ENABLE,
    CONSTRAINT "WORKFLOW_MARCA_WF_EST_HIST_FK" FOREIGN KEY ("ID_WORKFLOW_ESTADO_HIST") REFERENCES "SHV_WF_WORKFLOW_ESTADO_HIST" ("ID_WORKFLOW_ESTADO_HIST") ENABLE
  )
  TABLESPACE "SHIVATS";

------------------------------------------------------------------------------------
--Actualizaciones en tablas de cobros
------------------------------------------------------------------------------------

-- SHV_COB_FACTURA
ALTER TABLE SHV_COB_FACTURA ADD IMPORTE_BONIF_INTERESES NUMBER(17,4);
ALTER TABLE SHV_COB_FACTURA ADD SISTEMA_ORIGEN VARCHAR2(7 BYTE);
ALTER TABLE SHV_COB_FACTURA ADD MONTO_ACUMULADO_SIMULACION NUMBER(17,4);
ALTER TABLE SHV_COB_FACTURA ADD FECHA_ACUMULADO_SIMULACION DATE;
ALTER TABLE SHV_COB_FACTURA ADD CHECK_TRASLADAR_INTERESES VARCHAR2(2 BYTE);
ALTER TABLE SHV_COB_FACTURA ADD MIGRADO_DEIMOS VARCHAR2(2 BYTE);
ALTER TABLE SHV_COB_FACTURA ADD ESTADO_DEIMOS VARCHAR2(50 BYTE);
ALTER TABLE SHV_COB_FACTURA ADD FECHA_ACTUALIZACION_DEIMOS DATE;
ALTER TABLE SHV_COB_FACTURA ADD MENSAJE_ESTADO VARCHAR2(300);
ALTER TABLE SHV_COB_FACTURA ADD TIPO_MENSAJE_ESTADO VARCHAR2(3 BYTE);
ALTER TABLE SHV_COB_FACTURA ADD FECHA_EMISION DATE;
ALTER TABLE SHV_COB_FACTURA RENAME COLUMN INTERESES_GENERADOS TO COBRADOR_INTERESES_GENERADOS;
ALTER TABLE SHV_COB_FACTURA ADD ID_COBRO NUMBER;
ALTER TABLE SHV_COB_FACTURA ADD ID_DEBITO_ORIGEN NUMBER;
ALTER TABLE SHV_COB_FACTURA ADD ESTADO_ACUERDO_TRASLADO_CARGO VARCHAR2(20 BYTE);
ALTER TABLE SHV_COB_FACTURA ADD ID_CLIENTE_ACUERDO_TRAS_CARGO NUMBER;

-- SHV_COB_FACTURA_MIC
ALTER TABLE SHV_COB_FACTURA_MIC ADD COBRAR_SEGUNDO_VENCIMIENTO VARCHAR2(2 BYTE);
ALTER TABLE SHV_COB_FACTURA_MIC RENAME COLUMN QUE_HACER_CON_TERCEROS TO CHECK_DESTRANSFERIR_TERCEROS;
ALTER TABLE SHV_COB_FACTURA_MIC ADD FECHA_PUESTA_COBRO DATE;
ALTER TABLE SHV_COB_FACTURA_MIC ADD FECHA_ULTIMO_PAGO_PARCIAL DATE;
--UPDATE SHV_COB_FACTURA_MIC SET DESTRANSFERIR_TERCEROS = 'SI' WHERE DESTRANSFERIR_TERCEROS = 'S';
--UPDATE SHV_COB_FACTURA_MIC SET DESTRANSFERIR_TERCEROS = 'NO' WHERE DESTRANSFERIR_TERCEROS = 'N';
--COMMIT;

ALTER TABLE SHV_COB_FACTURA_MIC RENAME COLUMN INTERES_BONIFICADO_REGULADO TO COBRADOR_INTERES_BONIF_REGU;
ALTER TABLE SHV_COB_FACTURA_MIC RENAME COLUMN INTERES_BONIFICADO_NO_REGULADO TO COBRADOR_INTERES_BONIF_NO_REGU;

ALTER TABLE SHV_COB_FACTURA_MIC ADD FECHA_SEGUNDO_VENCIMIENTO DATE;


-- SHV_COB_FACTURA_CALIPSO
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD TIPO_DE_CAMBIO_FECHA_EMISION NUMBER(8,7);
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD TIPO_DE_CAMBIO_FECHA_COBRO NUMBER(8,7);
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD IMPORTE_APLIC_FEC_EMIS_MON_PES NUMBER(17,4);
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD IMPORTE_APLIC_FEC_EMIS_MON_ORI NUMBER(17,4);
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD CHECK_SIN_DIFERENCIA_CAMBIO VARCHAR2(2 BYTE);

UPDATE SHV_COB_FACTURA_CALIPSO SET MONEDA = 'PES' WHERE MONEDA = '$';
UPDATE SHV_COB_FACTURA_CALIPSO SET MONEDA = 'DOL' WHERE MONEDA = 'U$D';
COMMIT;

ALTER TABLE SHV_COB_FACTURA_CALIPSO RENAME COLUMN IMPORTE_ORIGINAL_PESOS TO IMPORTE_ORIGINAL_MONEDA_ORIGEN;
ALTER TABLE SHV_COB_FACTURA_CALIPSO RENAME COLUMN SALDO_ACTUAL_PESOS TO SALDO_ACTUAL_MONEDA_ORIGEN;
ALTER TABLE SHV_COB_FACTURA_CALIPSO RENAME COLUMN INTERESES_BONIFICADOS TO COBRADOR_INTERESES_BONIFICADOS;
ALTER TABLE SHV_COB_FACTURA_CALIPSO RENAME COLUMN MONTO_A_CUENTA TO COBRADOR_MONTO_A_CUENTA;

ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD IMPORTE_CAPITAL NUMBER(17,4);
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD IMPORTE_IMPUESTOS NUMBER(17,4);
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD IMPORTE_APLICADO NUMBER(17,4);
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD ORIGEN_DOCUMENTO VARCHAR2(20 BYTE);
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD UNIDAD_OPERATIVA VARCHAR2(20 BYTE);
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD SUBTIPO VARCHAR2(3 BYTE);
ALTER TABLE SHV_COB_FACTURA_CALIPSO ADD HOLDING VARCHAR2(20 BYTE);


-- SHV_COB_MEDIO_PAGO 
ALTER TABLE SHV_COB_MED_PAGO ADD MONEDA VARCHAR2(3 BYTE);
ALTER TABLE SHV_COB_MED_PAGO ADD MONTO_ACUMULADO_SIMULACION NUMBER(17,4);
ALTER TABLE SHV_COB_MED_PAGO ADD MIGRADO_DEIMOS VARCHAR2(2 BYTE);
ALTER TABLE SHV_COB_MED_PAGO ADD ESTADO_DEIMOS VARCHAR2(50 BYTE);
ALTER TABLE SHV_COB_MED_PAGO ADD FECHA_ACTUALIZACION_DEIMOS DATE;
ALTER TABLE SHV_COB_MED_PAGO ADD MENSAJE_ESTADO VARCHAR2(300);
ALTER TABLE SHV_COB_MED_PAGO ADD TIPO_MENSAJE_ESTADO VARCHAR2(3 BYTE);
ALTER TABLE SHV_COB_MED_PAGO ADD SISTEMA_ORIGEN VARCHAR2(7 BYTE);
ALTER TABLE SHV_COB_MED_PAGO ADD ID_CLIENTE_LEGADO NUMBER;
ALTER TABLE SHV_COB_MED_PAGO ADD ID_COBRO NUMBER;
ALTER TABLE SHV_COB_MED_PAGO ADD ID_CREDITO_ORIGEN NUMBER;

-- Armar el update para sistema origen!!!!

-- SHV_COB_TRANSACCION
ALTER TABLE SHV_COB_TRANSACCION ADD MENSAJE_ESTADO VARCHAR2(300);
ALTER TABLE SHV_COB_TRANSACCION ADD TIPO_MENSAJE_ESTADO VARCHAR2(3 BYTE);
ALTER TABLE SHV_COB_TRANSACCION ADD ID_TRANSACCION_PADRE NUMBER;

-- SHV_COB_MED_PAG_COMPENSACION, cambio columna fecha_firma_acta de number a tipo fecha y nombre FECHA 
ALTER TABLE SHV_COB_MED_PAG_COMPENSACION ADD FECHA_AUX DATE;
UPDATE SHV_COB_MED_PAG_COMPENSACION SET FECHA_AUX = TO_DATE(FECHA_FIRMA_ACTA, 'YYYYMMDD'); 
COMMIT;
ALTER TABLE SHV_COB_MED_PAG_COMPENSACION DROP COLUMN FECHA_FIRMA_ACTA;
ALTER TABLE SHV_COB_MED_PAG_COMPENSACION RENAME COLUMN FECHA_AUX TO FECHA;

-- SHV_COB_MED_PAG_COMPENSACION, cambio columna numero_acta a numero_compensacion
ALTER TABLE SHV_COB_MED_PAG_COMPENSACION RENAME COLUMN NUMERO_ACTA TO NUMERO_COMPENSACION;
ALTER TABLE SHV_COB_MED_PAG_COMPENSACION ADD NUMERO_AUX VARCHAR2(25 BYTE);
UPDATE SHV_COB_MED_PAG_COMPENSACION SET NUMERO_AUX = TO_CHAR(NUMERO_COMPENSACION); 
COMMIT;
ALTER TABLE SHV_COB_MED_PAG_COMPENSACION DROP COLUMN NUMERO_COMPENSACION;
ALTER TABLE SHV_COB_MED_PAG_COMPENSACION RENAME COLUMN NUMERO_AUX TO NUMERO_COMPENSACION;

-- SHV_COB_MED_PAG_NOTA_CRED_MIC, cambio columna fecha_emision de number a tipo fecha  
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_MIC ADD FECHA_AUX DATE;
UPDATE SHV_COB_MED_PAG_NOTA_CRED_MIC SET FECHA_AUX = TO_DATE(FECHA_EMISION, 'YYYYMMDD');
COMMIT;
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_MIC DROP COLUMN FECHA_EMISION;
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_MIC RENAME COLUMN FECHA_AUX TO FECHA_EMISION;
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_MIC ADD NUMERO_COMPROBANTE VARCHAR2(8 BYTE);
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_MIC ADD CLASE_COMPROBANTE CHAR(1 BYTE);
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_MIC ADD TIPO_COMPROBANTE VARCHAR2(3 BYTE);
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_MIC ADD SUCURSAL_COMPROBANTE VARCHAR2(4 BYTE);


-- SHV_COB_MED_PAG_NOTA_CRED_CLP, cambio columna fecha_emision de number a tipo fecha  
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_CLP ADD FECHA_AUX DATE;
UPDATE SHV_COB_MED_PAG_NOTA_CRED_CLP SET FECHA_AUX = TO_DATE(FECHA_EMISION, 'YYYYMMDD');
COMMIT;
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_CLP DROP COLUMN FECHA_EMISION;
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_CLP RENAME COLUMN FECHA_AUX TO FECHA_EMISION;

ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_CLP ADD IMPORTE_CAPITAL NUMBER(17,4);
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_CLP ADD IMPORTE_IMPUESTOS NUMBER(17,4);
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_CLP ADD IMPORTE_APLICADO NUMBER(17,4);
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_CLP ADD ORIGEN_DOCUMENTO VARCHAR2(20 BYTE);
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_CLP ADD UNIDAD_OPERATIVA VARCHAR2(20 BYTE);
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_CLP ADD SUBTIPO VARCHAR2(3 BYTE);
ALTER TABLE SHV_COB_MED_PAG_NOTA_CRED_CLP ADD HOLDING VARCHAR2(20 BYTE);

-- SHV_COB_MED_PAG_CTA, cambio columna fecha_emision de number a tipo fecha  
ALTER TABLE SHV_COB_MED_PAG_CTA ADD FECHA_AUX DATE;
UPDATE SHV_COB_MED_PAG_CTA SET FECHA_AUX = TO_DATE(FECHA_EMISION, 'YYYYMMDD');
COMMIT;
ALTER TABLE SHV_COB_MED_PAG_CTA DROP COLUMN FECHA_EMISION;
ALTER TABLE SHV_COB_MED_PAG_CTA RENAME COLUMN FECHA_AUX TO FECHA_EMISION;

ALTER TABLE SHV_COB_MED_PAG_CTA ADD IMPORTE_CAPITAL NUMBER(17,4);
ALTER TABLE SHV_COB_MED_PAG_CTA ADD IMPORTE_IMPUESTOS NUMBER(17,4);
ALTER TABLE SHV_COB_MED_PAG_CTA ADD IMPORTE_APLICADO NUMBER(17,4);
ALTER TABLE SHV_COB_MED_PAG_CTA ADD ORIGEN_DOCUMENTO VARCHAR2(20 BYTE);
ALTER TABLE SHV_COB_MED_PAG_CTA ADD UNIDAD_OPERATIVA VARCHAR2(20 BYTE);
ALTER TABLE SHV_COB_MED_PAG_CTA ADD SUBTIPO VARCHAR2(3 BYTE);
ALTER TABLE SHV_COB_MED_PAG_CTA ADD HOLDING VARCHAR2(20 BYTE);

-- SHV_COB_MED_PAG_PLAN_PAGO
ALTER TABLE SHV_COB_MED_PAG_PLAN_PAGO ADD FECHA DATE;

-- SHV_COB_MED_PAG_SHIVA
ALTER TABLE SHV_COB_MED_PAG_SHIVA ADD FECHA_VALOR DATE;
ALTER TABLE SHV_COB_MED_PAG_SHIVA ADD REFERENCIA_VALOR VARCHAR2(25);
ALTER TABLE SHV_COB_MED_PAG_SHIVA ADD ID_TIPO_VALOR NUMBER;
ALTER TABLE SHV_COB_MED_PAG_SHIVA ADD ID_TIPO_RETENCION_IMPUESTO NUMBER;

-- SHV_COB_FACTURA_MIC, cambio columna fecha_emision de number a tipo fecha  
ALTER TABLE SHV_COB_FACTURA_MIC ADD FECHA_AUX DATE;
UPDATE SHV_COB_FACTURA_MIC SET FECHA_AUX = TO_DATE(FECHA_EMISION, 'YYYYMMDD');
COMMIT;
ALTER TABLE SHV_COB_FACTURA_MIC DROP COLUMN FECHA_EMISION;
ALTER TABLE SHV_COB_FACTURA_MIC RENAME COLUMN FECHA_AUX TO FECHA_EMISION;
ALTER TABLE SHV_COB_FACTURA_MIC ADD TIPO_DUC VARCHAR2(2 BYTE);

--ALTER TABLE SHV_COB_FACTURA_MIC ADD TIPO_FACTURA_AUX VARCHAR2(2 BYTE);
--UPDATE SHV_COB_FACTURA_MIC SET TIPO_FACTURA_AUX = TO_CHAR(TIPO_FACTURA);
--COMMIT;
--ALTER TABLE SHV_COB_FACTURA_MIC DROP COLUMN TIPO_FACTURA;
--ALTER TABLE SHV_COB_FACTURA_MIC RENAME COLUMN TIPO_FACTURA_AUX TO TIPO_FACTURA;




-- SHV_COB_MED_PAG_REMANENTE
ALTER TABLE SHV_COB_MED_PAG_REMANENTE ADD FECHA_ALTA DATE;

-- SHV_COB_MED_PAG_DESISTIMIENTO
ALTER TABLE SHV_COB_MED_PAG_DESISTIMIENTO MODIFY NUMERO_ACTA VARCHAR2(25 BYTE);
ALTER TABLE SHV_COB_MED_PAG_DESISTIMIENTO ADD FECHA DATE;

-- Secuencia para SEQ_SHV_COB_MED_PAG_CLIENTE
CREATE SEQUENCE SEQ_SHV_COB_MED_PAG_CLIENTE MINVALUE 1 MAXVALUE 99999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

-- SHV_COB_MED_PAG_CLIENTE
DROP TABLE SHV_COB_MED_PAG_CLIENTE;
CREATE TABLE SHV_COB_MED_PAG_CLIENTE (
	ID_MEDIO_PAGO_CLIENTE                          NUMBER NOT NULL,
	ID_MEDIO_PAGO                                  NUMBER NOT NULL,
	ID_CLIENTE_LEGADO                              NUMBER(20) NOT NULL,
	CONSTRAINT MED_PAG_CLIENTE_PK PRIMARY KEY (ID_MEDIO_PAGO_CLIENTE) ENABLE,
  CONSTRAINT MED_PAG_CLIENTE_MED_PAG_USU_FK FOREIGN KEY (ID_MEDIO_PAGO) REFERENCES SHV_COB_MED_PAG_USUARIO(ID_MEDIO_PAGO) ENABLE
	) 
  TABLESPACE "SHIVATS";
  
-- (aun no impactado!) Armar Script para mover los clientes actuales de los medios de pago de usuario a esta tabla de clientes, y luego eliminar la columa de cliente!!!

-- SHV_COB_MED_PAG_COMP_INTERCOM
DROP TABLE SHV_COB_MED_PAG_COMP_INTERCOM;
CREATE TABLE SHV_COB_MED_PAG_COMP_INTERCOM
  (
    "ID_MEDIO_PAGO"       NUMBER NOT NULL ENABLE,
    "NUMERO_COMPENSACION" VARCHAR2(25 BYTE) NOT NULL ENABLE,
    "FECHA"  DATE,
    CONSTRAINT "SHV_COB_MEDIO_PAG_INTERCOM_PK" PRIMARY KEY ("ID_MEDIO_PAGO") ENABLE,
    CONSTRAINT "MP_COMP_INTERCO_MP_USUARIO_FK" FOREIGN KEY ("ID_MEDIO_PAGO") REFERENCES SHV_COB_MED_PAG_USUARIO ("ID_MEDIO_PAGO") ENABLE
  )
  TABLESPACE "SHIVATS";

-- SHV_COB_MED_PAG_COMP_LIQUIDO
DROP TABLE SHV_COB_MED_PAG_COMP_LIQUIDO;
CREATE TABLE SHV_COB_MED_PAG_COMP_LIQUIDO
  (
    "ID_MEDIO_PAGO"       NUMBER NOT NULL ENABLE,
    "NUMERO_COMPENSACION" VARCHAR2(25 BYTE) NOT NULL ENABLE,
    "FECHA"  DATE,
    CONSTRAINT "SHV_COB_MEDIO_PAG_LIQUIDO_PK" PRIMARY KEY ("ID_MEDIO_PAGO") ENABLE,
    CONSTRAINT "MP_COMP_LIQUIDO_MP_USUARIO_FK" FOREIGN KEY ("ID_MEDIO_PAGO") REFERENCES SHV_COB_MED_PAG_USUARIO ("ID_MEDIO_PAGO") ENABLE
  )
  TABLESPACE "SHIVATS";

-- SHV_COB_MED_PAG_DEB_PROX_MIC
DROP TABLE SHV_COB_MED_PAG_DEB_PROX_MIC;
CREATE TABLE SHV_COB_MED_PAG_DEB_PROX_MIC
  (
    "ID_MEDIO_PAGO"                   NUMBER NOT NULL ENABLE,
    "FECHA"                           DATE, 
    "ACUERDO_TRASLADO_CARGO"          VARCHAR2(20),
    "ESTADO_ACUERDO_TRASLADO_CARGO"   VARCHAR2(20 BYTE),
    "ID_CLIENTE_ACUERDO_TRAS_CARGO"  NUMBER,
    "FECHA_VENCIMIENTO_FACTURA"       DATE, 
    "CALCULAR_FECHA_HASTA"            VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "QUE_HACER_CON_INTERESES"         VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "CHECK_TRASLADAR_INTERESES"       VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "PORCENTAJE_BONIF_INTERESES"      NUMBER(2),
    "IMPORTE_BONIF_INTERESES"         NUMBER(17,4),
    "ORIGEN_CARGO"                    VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "LEYENDA_FACTURA_CARGO"           VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "LEYENDA_FACTURA_INTERES"         VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "COBRADOR_INTERESES_GENERADOS"    NUMBER(17,4),
    "COBRADOR_INTERESES_BONIFICADOS"  NUMBER(17,4),
    CONSTRAINT "SHV_COB_MED_PAG_DEB_PRO_MIC_PK" PRIMARY KEY ("ID_MEDIO_PAGO") ENABLE,
    CONSTRAINT "SHV_COB_MED_PAG_DEB_PRO_MIC_FK" FOREIGN KEY ("ID_MEDIO_PAGO") REFERENCES SHV_COB_MED_PAG_USUARIO ("ID_MEDIO_PAGO") ENABLE
  )
  TABLESPACE "SHIVATS";

-- SHV_COB_MED_PAG_DEB_PROX_CLP
DROP TABLE SHV_COB_MED_PAG_DEB_PROX_CLP;
CREATE TABLE SHV_COB_MED_PAG_DEB_PROX_CLP
  (
    "ID_MEDIO_PAGO"                   NUMBER NOT NULL ENABLE,
    "FECHA"                           DATE, 
    "ACUERDO_TRASLADO_CARGO"          VARCHAR2(20 BYTE),
    "ESTADO_ACUERDO_TRASLADO_CARGO"   VARCHAR2(20 BYTE),
    "ID_CLIENTE_ACUERDO_TRAS_CARGO"  NUMBER,
    "FECHA_VENCIMIENTO_FACTURA"       DATE, 
    "CALCULAR_FECHA_HASTA"            VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "QUE_HACER_CON_INTERESES"         VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "CHECK_TRASLADAR_INTERESES"       VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "PORCENTAJE_BONIF_INTERESES"      NUMBER(2),
    "IMPORTE_BONIF_INTERESES"         NUMBER(17,4),
    "ORIGEN_CARGO"                    VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "LEYENDA_FACTURA_CARGO"           VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "LEYENDA_FACTURA_INTERES"         VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "COBRADOR_INTERESES_GENERADOS"    NUMBER(17,4),
    "COBRADOR_INTERESES_BONIFICADOS"  NUMBER(17,4),
    "COBRADOR_MONTO_A_CUENTA"         NUMBER(17,4),
    "COBRADOR_ID_MOV_MER"             NUMBER(10,0),
    CONSTRAINT "SHV_COB_MED_PAG_DEB_PRO_CLP_PK" PRIMARY KEY ("ID_MEDIO_PAGO") ENABLE,
    CONSTRAINT "SHV_COB_MED_PAG_DEB_PRO_CLP_FK" FOREIGN KEY ("ID_MEDIO_PAGO") REFERENCES SHV_COB_MED_PAG_USUARIO ("ID_MEDIO_PAGO") ENABLE
  )
  TABLESPACE "SHIVATS";

-- Secuencia para SEQ_SHV_COB_TRATAMIENTO_DIFERENCIA
CREATE SEQUENCE SEQ_SHV_COB_TRATAMIENTO_DIFER
	MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

-- SHV_COB_TRATAMIENTO_DIFERENCIA 
DROP TABLE SHV_COB_TRATAMIENTO_DIFERENCIA;
CREATE TABLE SHV_COB_TRATAMIENTO_DIFERENCIA
  (
    "ID_TRATAMIENTO_DIFERENCIA"       NUMBER NOT NULL ENABLE,
    "ID_TRANSACCION"                  NUMBER NOT NULL ENABLE,
    "ESTADO"                          VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "TIPO_TRATAMIENTO_DIFERENCIA"     VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "IMPORTE"                         NUMBER(17,4) NOT NULL ENABLE,
    "NUMERO_TRAMITE_REINTEGRO"        NUMBER, 
    "FECHA_TRAMITE_REINTEGRO"         DATE, 
    "ACUERDO_TRASLADO_CARGO"          VARCHAR2(20 BYTE),
    "ESTADO_ACUERDO_TRASLADO_CARGO"   VARCHAR2(20 BYTE),
    "ID_CLIENTE_ACUERDO_TRAS_CARGO"  NUMBER,
    "CALCULAR_FECHA_HASTA"            VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "QUE_HACER_CON_INTERESES"         VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "CHECK_TRASLADAR_INTERESES"       VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "PORCENTAJE_BONIF_INTERESES"      NUMBER(2),
    "IMPORTE_BONIF_INTERESES"         NUMBER(17,4),
    "ORIGEN_CARGO"                    VARCHAR2(30 BYTE) NOT NULL ENABLE,
    "LEYENDA_FACTURA_CARGO"           VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "LEYENDA_FACTURA_INTERES"         VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "COBRADOR_INTERESES_GENERADOS"    NUMBER(17,4),
    "COBRADOR_INTERESES_BONIFICADOS"  NUMBER(17,4),
    "COBRADOR_MONTO_A_CUENTA"         NUMBER(17,4),
    "COBRADOR_ID_MOV_MER"             NUMBER(10,0),
    "MENSAJE_ESTADO"                  VARCHAR2(100 BYTE),
    "TIPO_MENSAJE_ESTADO"             VARCHAR2(3 BYTE),
    CONSTRAINT "SHV_COB_TRATAMIENTO_DIFER_PK" PRIMARY KEY ("ID_TRATAMIENTO_DIFERENCIA") ENABLE,
    CONSTRAINT TRATA_DIFE_TRANS_FK FOREIGN KEY (ID_TRANSACCION) REFERENCES SHV_COB_TRANSACCION(ID_TRANSACCION) ENABLE
  )
  TABLESPACE "SHIVATS";  



------------------------------------------------------------------------------------
--Actualizaciones en tablas parametricas
------------------------------------------------------------------------------------

-- Secuencia para SHV_PARAM_TIPO_MEDIO_PAGO_USO
CREATE SEQUENCE SEQ_SHV_PARAM_TIP_MED_PAGO_USO
	MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

-- SHV_PARAM_TIPO_MEDIO_PAGO_USO
CREATE TABLE SHV_PARAM_TIPO_MEDIO_PAGO_USO
  (
    "ID_TIPO_MEDIO_PAGO_USO"   NUMBER NOT NULL ENABLE,
    "ID_TIPO_MEDIO_PAGO"       VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "ID_MONEDA"				         VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "PERMITE_USO_REINTEGRO"    VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "PERMITE_USO_DUC"          VARCHAR2(2 BYTE) NOT NULL ENABLE, 
    "PERMITE_USO_COBRO"        VARCHAR2(2 BYTE) NOT NULL ENABLE,
    "ESTADO"                   VARCHAR2(8 BYTE) NOT NULL ENABLE,
    "AUD_REQUERIMIENTO_ORIGEN" VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CONSTRAINT "SHV_PARAM_TIPO_MED_PAGO_USO_PK" PRIMARY KEY ("ID_TIPO_MEDIO_PAGO_USO") ENABLE
  )
  TABLESPACE "SHIVATS";
  
-- SHV_PARAM_TIPO_MEDIO_PAGO_USO FK SHV_PARAM_TIPO_MEDIO_PAGO
ALTER TABLE SHV_PARAM_TIPO_MEDIO_PAGO_USO
ADD CONSTRAINT TIPO_MP_USO_TIPO_MP_FK
FOREIGN KEY (ID_TIPO_MEDIO_PAGO) REFERENCES SHV_PARAM_TIPO_MEDIO_PAGO(ID_TIPO_MEDIO_PAGO) ENABLE;  

------------------------------------------------------------------------------------
--Actualizaciones en tablas de cobros online
------------------------------------------------------------------------------------

-- SHV_COB_ED_COBRO
ALTER TABLE SHV_COB_ED_COBRO ADD ANALISTA VARCHAR2(50 BYTE);
ALTER TABLE SHV_COB_ED_COBRO ADD COPROPIETARIO VARCHAR2(50 BYTE);
ALTER TABLE SHV_COB_ED_COBRO ADD ID_ANALISTA_TEAM_COMERCIAL VARCHAR2(9 BYTE);
ALTER TABLE SHV_COB_ED_COBRO ADD ANALISTA_TEAM_COMERCIAL VARCHAR2(50 BYTE);
ALTER TABLE SHV_COB_ED_COBRO ADD IMPORTE_TOTAL NUMBER(17,4);
ALTER TABLE SHV_COB_ED_COBRO ADD ID_COBRO_PADRE NUMBER;

-- SHV_COB_ED_CLIENTE
ALTER TABLE SHV_COB_ED_CLIENTE ADD RAZON_SOCIAL VARCHAR2(200 BYTE);
ALTER TABLE SHV_COB_ED_CLIENTE ADD CUIT VARCHAR2(13 BYTE);
ALTER TABLE SHV_COB_ED_CLIENTE ADD ID_HOLDING NUMBER;
ALTER TABLE SHV_COB_ED_CLIENTE ADD DESCRIPCION_HOLDING VARCHAR2(200 BYTE);
ALTER TABLE SHV_COB_ED_CLIENTE ADD ID_AGENCIA_NEGOCIO NUMBER;
ALTER TABLE SHV_COB_ED_CLIENTE ADD DESCRIPCION_AGENCIA_NEGOCIO VARCHAR2(200 BYTE);
ALTER TABLE SHV_COB_ED_CLIENTE ADD ID_SEGMENTO_AGENCIA_NEGOCIO VARCHAR2(3 BYTE);
ALTER TABLE SHV_COB_ED_CLIENTE ADD CONSTRAINT "COBRO_ED_SEGMENTO_FK" FOREIGN KEY ("ID_SEGMENTO_AGENCIA_NEGOCIO") REFERENCES "SHV_PARAM_SEGMENTO" ("ID_SEGMENTO") ENABLE;

--ALTER TABLE SHV_COB_ED_CLIENTE ADD ID_CLIENTE_PERFIL NUMBER;
--ALTER TABLE SHV_COB_ED_CLIENTE ADD DESCRIPCION_CLIENTE_PERFIL VARCHAR2(200 BYTE);

-- SHV_COB_ED_MEDIO_PAGO_CLIENTE
ALTER TABLE SHV_COB_ED_MEDIO_PAGO_CLIENTE
ADD CONSTRAINT MED_PAG_CLIENTE_MED_PAG_FK
FOREIGN KEY (ID_MEDIO_PAGO, ID_COBRO) REFERENCES SHV_COB_ED_OTROS_MEDIO_PAGO(ID_MEDIO_PAGO, ID_COBRO) ENABLE;

ALTER TABLE SHV_COB_MED_PAG_CLIENTE
ADD CONSTRAINT MED_PAG_CLIENTE_MED_PAG_USU_FK
FOREIGN KEY (ID_MEDIO_PAGO) REFERENCES SHV_COB_MED_PAG_USUARIO(ID_MEDIO_PAGO) ENABLE;


------------------------------------------------------------------------------------
--Actualizacion de tarea
------------------------------------------------------------------------------------

-- SHV_WF_TAREA
ALTER TABLE SHV_WF_TAREA MODIFY PERFIL_ASIGNACION VARCHAR2(50 BYTE) NULL;
  
-- SHV_WF_TAREA_COBRO
ALTER TABLE SHV_WF_TAREA_COBRO ADD ID_CLIENTE_LEGADO NUMBER;
ALTER TABLE SHV_WF_TAREA_COBRO ADD RAZON_SOCIAL_CLIENTE VARCHAR2(200 BYTE);

  