delete from SHV_MNU_MENU_PERFIL where ID_PERFIL = 42 AND ID_MENU = 27;
delete from SHV_MNU_MENU_PERFIL where ID_PERFIL = 43 AND ID_MENU = 27;
delete from SHV_MNU_MENU_PERFIL where ID_PERFIL = 44 AND ID_MENU = 27;
delete from SHV_MNU_MENU_PERFIL where ID_PERFIL = 45 AND ID_MENU = 27;
delete from SHV_MNU_MENU_PERFIL where ID_PERFIL = 46 AND ID_MENU = 27;

delete from SHV_MNU_MENU_PERFIL where ID_PERFIL = 42 AND ID_MENU = 23;
delete from SHV_MNU_MENU_PERFIL where ID_PERFIL = 43 AND ID_MENU = 23;
delete from SHV_MNU_MENU_PERFIL where ID_PERFIL = 44 AND ID_MENU = 23;
delete from SHV_MNU_MENU_PERFIL where ID_PERFIL = 45 AND ID_MENU = 23;
delete from SHV_MNU_MENU_PERFIL where ID_PERFIL = 46 AND ID_MENU = 23;


Commit;

Exit;