-- Actualizaciones para SHV_PARAM_PARAMETRO - Version
--
UPDATE SHV_PARAM_PARAMETRO
SET VALOR_TEXTO = '2.01.00'
WHERE CLAVE = 'version';
--
-- Creacion del perfil aplicativo 'Referente de Cobranza'
Insert into SHV_SEG_PERFIL_APLICATIVO (ID_PERFIL_APLICATIVO,DESCRIPCION) values ('12','ReferenteCobranza');
-- Creacion del perfil aplicativo 'Analista Operacion Masiva' 
insert into shv_seg_perfil_aplicativo (id_perfil_aplicativo, descripcion) values ('13', 'AnalistaOperacionMasiva');
-- Creacion del perfil aplicativo 'Supervisor Operacion Masiva' 
insert into shv_seg_perfil_aplicativo (id_perfil_aplicativo, descripcion) values ('14', 'SupervisorOperacionMasiva');

-- Creacion de perfil 'Supervisor de Cobranza'
Insert into SHV_SEG_PERFIL (ID_PERFIL,NOMBRE,ID_PERFIL_APLICATIVO,ID_EMPRESA,ID_SEGMENTO) values ('31','Supervisor Cobranza - Telecom Argentina - Grandes Clientes','11','TA','OGC');
Insert into SHV_SEG_PERFIL (ID_PERFIL,NOMBRE,ID_PERFIL_APLICATIVO,ID_EMPRESA,ID_SEGMENTO) values ('32','Supervisor Cobranza - Telecom Argentina - Whole Sale','11','TA','OYP');
Insert into SHV_SEG_PERFIL (ID_PERFIL,NOMBRE,ID_PERFIL_APLICATIVO,ID_EMPRESA,ID_SEGMENTO) values ('33','Supervisor Cobranza - Telecom Argentina - PyME','11','TA','OGE');
Insert into SHV_SEG_PERFIL (ID_PERFIL,NOMBRE,ID_PERFIL_APLICATIVO,ID_EMPRESA,ID_SEGMENTO) values ('34','Supervisor Cobranza - Telecom Argentina - Telefonia Publica','11','TA','OTP');
Insert into SHV_SEG_PERFIL (ID_PERFIL,NOMBRE,ID_PERFIL_APLICATIVO,ID_EMPRESA,ID_SEGMENTO) values ('35','Supervisor Cobranza - Telecom Argentina - Residencial','11','TA','OCO');

-- Creacion de perfil 'Referente de Cobranza'
Insert into SHV_SEG_PERFIL (ID_PERFIL,NOMBRE,ID_PERFIL_APLICATIVO,ID_EMPRESA,ID_SEGMENTO) values ('36','Referente de Cobranza','12','TA','');

-- Creacion de perfil 'Analista Operacion Masiva'
insert into shv_seg_perfil (id_perfil,nombre, id_perfil_aplicativo, id_empresa, id_segmento) values ('37','Analista Operacion Masiva - Telecom Argentina - Grandes Clientes',13,'TA','OGC');
insert into shv_seg_perfil (id_perfil,nombre, id_perfil_aplicativo, id_empresa, id_segmento) values ('38','Analista Operacion Masiva - Telecom Argentina - Whole Sale',13,'TA','OYP');
insert into shv_seg_perfil (id_perfil,nombre, id_perfil_aplicativo, id_empresa, id_segmento) values ('39','Analista Operacion Masiva - Telecom Argentina - PyME',13,'TA','OGE');
insert into shv_seg_perfil (id_perfil,nombre, id_perfil_aplicativo, id_empresa, id_segmento) values ('40','Analista Operacion Masiva - Telecom Argentina - Telefonia Publica',13,'TA','OTP');
insert into shv_seg_perfil (id_perfil,nombre, id_perfil_aplicativo, id_empresa, id_segmento) values ('41','Analista Operacion Masiva - Telecom Argentina - Residencial',13,'TA','OCO');

-- Creacion de perfil 'Supervisor Operacion Masiva'
insert into shv_seg_perfil (id_perfil,nombre, id_perfil_aplicativo, id_empresa, id_segmento) values ('42','Supervisor Operacion Masiva - Telecom Argentina - Grandes Clientes',14,'TA','OGC');
insert into shv_seg_perfil (id_perfil,nombre, id_perfil_aplicativo, id_empresa, id_segmento) values ('43','Supervisor Operacion Masiva - Telecom Argentina - Whole Sale',14,'TA','OYP');
insert into shv_seg_perfil (id_perfil,nombre, id_perfil_aplicativo, id_empresa, id_segmento) values ('44','Supervisor Operacion Masiva - Telecom Argentina - PyME',14,'TA','OGE');
insert into shv_seg_perfil (id_perfil,nombre, id_perfil_aplicativo, id_empresa, id_segmento) values ('45','Supervisor Operacion Masiva - Telecom Argentina - Telefonia Publica',14,'TA','OTP');
insert into shv_seg_perfil (id_perfil,nombre, id_perfil_aplicativo, id_empresa, id_segmento) values ('46','Supervisor Operacion Masiva - Telecom Argentina - Residencial',14,'TA','OCO');

-- Creacion de la opcion de menu 'Cobros'
-- Insert into SHV_MNU_MENU (ID_MENU,DESCRIPCION,URL_ACCESO,ORDEN,MENU_ID_MENU) values ('22','Cobros','','8','0');
-- Creacion de la opcion de menu 'Configuración de Cobro'
-- Insert into SHV_MNU_MENU (ID_MENU,DESCRIPCION,URL_ACCESO,ORDEN,MENU_ID_MENU) values ('23','Configuración de Cobro','cobros-configuracion','1','22');
-- Creacion de la opcion de menu 'Busqueda de cobros'
Insert into SHV_MNU_MENU (ID_MENU,DESCRIPCION,URL_ACCESO,ORDEN,MENU_ID_MENU) values ('24','Búsqueda de cobros','cobro-busqueda','2','22');

-- Asocio el menu con el perfil de Supervisor de Cobranza para los diferentes segmentos
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (150,31,24);
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (151,32,24);
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (152,33,24);
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (153,34,24);
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (154,35,24);

-- Asocio el menu con el perfil de Referente de Cobranza
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (155,36,24);

-- Asocio el menu con el perfil de Analista Cobranza
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (156,26,24);
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (157,27,24);
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (158,28,24);
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (159,29,24);
Insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (160,30,24);

-- Op Masiva Viejo (Bandeja de entrada)
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (161,37,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (162,38,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (163,39,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (164,40,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (165,41,2);

insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (166,42,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (167,43,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (168,44,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (169,45,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (170,46,2);

-- Acceso a bandeja de entrada para Analista Cobranza
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (171,26,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (172,27,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (173,28,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (174,29,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (175,30,2);

-- Acceso a bandeja de entrada para Supervisor Cobranza
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (176,31,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (177,32,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (178,33,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (179,34,2);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (180,35,2);

-- Acceso a bandeja de entrada para Referente de Cobranza
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (181,36,2);

-- Op Masiva Spring 5 (Busqueda de Cobros)
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (182,37,24);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (183,38,24);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (184,39,24);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (185,40,24);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (186,41,24);

insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (187,42,24);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (188,43,24);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (189,44,24);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (190,45,24);
insert into SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) values (191,46,24);

-- Actualizacion de estados de workflows SHV_PARAM_WORKFLOW_ESTADO

insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO, TIPO_WORKFLOW, DESCRIPCION, AUD_REQUERIMIENTO_ORIGEN) values ('COB_PEND_REFERENTE_COBRANZA', 'COBRO', 'Pend. Referente Cobranza', 'SPRINT 5');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO, TIPO_WORKFLOW, DESCRIPCION, AUD_REQUERIMIENTO_ORIGEN) values ('COB_PEND_SUPERVISOR_COBRANZA', 'COBRO', 'Pend. Supervisor Cobranza', 'SPRINT 5');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO, TIPO_WORKFLOW, DESCRIPCION, AUD_REQUERIMIENTO_ORIGEN) values ('COB_MEDIO_PAGO_EN_PROCESO', 'COBRO', 'Medio de Pago en Proceso', 'SPRINT 5');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO, TIPO_WORKFLOW, DESCRIPCION, AUD_REQUERIMIENTO_ORIGEN) values ('COB_RECHAZADO', 'COBRO', 'Cobro Rechazado', 'SPRINT 5');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO, TIPO_WORKFLOW, DESCRIPCION, AUD_REQUERIMIENTO_ORIGEN) values ('COB_ERROR_DESAPROPIACION', 'COBRO', 'Error en desapropiación', 'SPRINT 5');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO, TIPO_WORKFLOW, DESCRIPCION, AUD_REQUERIMIENTO_ORIGEN) values ('COB_REEDITADO', 'COBRO', 'Cobro reeditado', 'SPRINT 5');
insert into SHV_PARAM_WORKFLOW_ESTADO (ID_ESTADO, TIPO_WORKFLOW, DESCRIPCION, AUD_REQUERIMIENTO_ORIGEN) values ('COB_ANULADO', 'COBRO', 'Cobro anulado', 'SPRINT 5');

-- Actualizaciones para SHV_PARAM_PARAMETRO - validaciones en cobros 
--
INSERT INTO SHV_PARAM_PARAMETRO (CLAVE, VALOR_TEXTO, VALOR_NUMERICO, AUD_REQUERIMIENTO_ORIGEN) 
VALUES ('cobros.validacion.porcentajeMaximoMontoProximaFact', null, 50, 'SPRINT 5');

INSERT INTO SHV_PARAM_PARAMETRO (CLAVE, VALOR_TEXTO, VALOR_NUMERICO, AUD_REQUERIMIENTO_ORIGEN) 
VALUES ('cobros.validacion.importeMaximoMontoProximaFact', null, 150, 'SPRINT 5');

INSERT INTO SHV_PARAM_PARAMETRO (CLAVE, VALOR_TEXTO, VALOR_NUMERICO, AUD_REQUERIMIENTO_ORIGEN) 
VALUES ('cobros.validacion.cantTransacMaximoOnlinePermitido', null, 10, 'SPRINT 5');
 
-- Actualizaciones de accciones para seguridad

INSERT INTO SHV_SEG_PERFIL_APLICATIVO_ACCS (ID_PERFIL_APLICATIVO, TIENE_PERMISO, DESCRIPCION, ID_ACCION)
VALUES (10,'SI','MODIFICAR_COBRO',23); 

INSERT INTO SHV_SEG_PERFIL_APLICATIVO_ACCS (ID_PERFIL_APLICATIVO, TIENE_PERMISO, DESCRIPCION, ID_ACCION)
VALUES (10,'SI','ANULAR_COBRO',24);

-- Actualizaciones en SHV_PARAM_TIPO_MED_PAGO_USO - indica como se pueden usar los medios de pago de acuerdo a sus monedas
--
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '01', 'PES', 'SI', 'SI', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '02', 'PES', 'SI', 'SI', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '03', 'PES', 'SI', 'SI', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '05', 'PES', 'SI', 'SI', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '06', 'PES', 'NO', 'NO', 'NO', 'INACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '07', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '08', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '09', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '10', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '11', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '12', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '13', 'PES', 'NO', 'NO', 'NO', 'INACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '14', 'PES', 'SI', 'NO', 'NO', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '15', 'PES', 'SI', 'NO', 'NO', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '16', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '17', 'PES', 'SI', 'SI', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '19', 'PES', 'SI', 'SI', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '20', 'PES', 'SI', 'SI', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '21', 'PES', 'SI', 'SI', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '21', 'DOL', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '22', 'PES', 'SI', 'SI', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '22', 'DOL', 'SI', 'SI', 'SI', 'ACTIVO', 'SPRINT 5');
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '23', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '24', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '25', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '26', 'PES', 'SI', 'NO', 'NO', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '27', 'PES', 'SI', 'NO', 'NO', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '28', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '29', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '30', 'PES', 'SI', 'NO', 'NO', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '31', 'PES', 'SI', 'NO', 'NO', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '32', 'PES', 'SI', 'NO', 'NO', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '33', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '34', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '35', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	
INSERT INTO SHV_PARAM_TIPO_MEDIO_PAGO_USO (ID_TIPO_MEDIO_PAGO_USO, ID_TIPO_MEDIO_PAGO, ID_MONEDA, PERMITE_USO_REINTEGRO, PERMITE_USO_DUC, PERMITE_USO_COBRO, ESTADO, AUD_REQUERIMIENTO_ORIGEN) VALUES (SEQ_SHV_PARAM_TIP_MED_PAGO_USO.NEXTVAL, '36', 'PES', 'NO', 'NO', 'SI', 'ACTIVO', 'SPRINT 5');	


INSERT INTO SHV_PARAM_TIPO_ORIGEN_CONTABLE VALUES ('004', 'Confirmacion de cobro DUC','SHIVA');
INSERT INTO SHV_PARAM_TIPO_ORIGEN_CONTABLE VALUES ('009', 'Revesion del cobro DUC','SHIVA');

COMMIT;