
ALTER TABLE SHV_COB_DESCOBRO ADD ORIGEN_DESCOBRO VARCHAR2(7);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA MODIFY DEB_IMPU_GRAL_ESTAD_CONCEP_TER VARCHAR2(30);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO MODIFY DEB_IMPU_GRAL_EST_CONC_TER VARCHAR2(30);

Exit;