--Grant para funcion loguearse con el usuario que no es owner del schema	
	CREATE OR REPLACE SYNONYM SEQ_SHV_COB_DESCOBRO_OP_REL FOR A002018.SEQ_SHV_COB_DESCOBRO_OP_REL;
	
	CREATE OR REPLACE SYNONYM SHV_COB_DESCOBRO_OPERAC_RELAC FOR A002018.SHV_COB_DESCOBRO_OPERAC_RELAC;
	
	CREATE OR REPLACE SYNONYM SHV_SOP_DESCOBROS_OPER_RELAC FOR A002018.SHV_SOP_DESCOBROS_OPER_RELAC;

	CREATE OR REPLACE SYNONYM SHV_WF_TAREA_DESCOBRO FOR A002018.SHV_WF_TAREA_DESCOBRO;
	
	CREATE OR REPLACE SYNONYM SHV_COB_DESCOBRO_DOC_RELAC FOR A002018.SHV_COB_DESCOBRO_DOC_RELAC;
     
  	CREATE OR REPLACE SYNONYM SEQ_SHV_COB_DESCOBRO_DOC_REL FOR A002018.SEQ_SHV_COB_DESCOBRO_DOC_REL;
  	
  	Exit;