package ar.com.telecom.shiva.presentacion.wsdl.ice.consultaCheques;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:51.803-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://service.ws.ice.teco.com.ar", name = "ConsultaChequesPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultaChequesPortType {

    @WebResult(name = "return", targetNamespace = "http://service.ws.ice.teco.com.ar")
    @Action(input = "urn:consultaCheques", output = "urn:consultaChequesResponse")
    @RequestWrapper(localName = "consultaCheques", targetNamespace = "http://service.ws.ice.teco.com.ar", className = "ar.com.telecom.shiva.presentacion.wsdl.ice.consultaCheques.ConsultaCheques")
    @WebMethod(action = "urn:consultaCheques")
    @ResponseWrapper(localName = "consultaChequesResponse", targetNamespace = "http://service.ws.ice.teco.com.ar", className = "ar.com.telecom.shiva.presentacion.wsdl.ice.consultaCheques.ConsultaChequesResponse")
    public ar.com.telecom.shiva.presentacion.wsdl.ice.consultaCheques.ConsultaChequesSalida consultaCheques(
        @WebParam(name = "consultaChequesEntrada", targetNamespace = "http://service.ws.ice.teco.com.ar")
        ar.com.telecom.shiva.presentacion.wsdl.ice.consultaCheques.ConsultaChequesEntrada consultaChequesEntrada
    );
}
