package ar.com.telecom.shiva.presentacion.wsdl.ice.consultaCheques;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:51.810-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "ConsultaCheques", 
                  wsdlLocation = "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/ice/ConsultaCheques.wsdl",
                  targetNamespace = "http://service.ws.ice.teco.com.ar") 
public class ConsultaCheques_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.ice.teco.com.ar", "ConsultaCheques");
    public final static QName ConsultaChequesHttpEndpoint = new QName("http://service.ws.ice.teco.com.ar", "ConsultaChequesHttpEndpoint");
    public final static QName ConsultaChequesHttpsEndpoint = new QName("http://service.ws.ice.teco.com.ar", "ConsultaChequesHttpsEndpoint");
    public final static QName ConsultaChequesHttpsSoap11Endpoint = new QName("http://service.ws.ice.teco.com.ar", "ConsultaChequesHttpsSoap11Endpoint");
    public final static QName ConsultaChequesHttpSoap11Endpoint = new QName("http://service.ws.ice.teco.com.ar", "ConsultaChequesHttpSoap11Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/ice/ConsultaCheques.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaCheques_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/ice/ConsultaCheques.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaCheques_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaCheques_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCheques_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaCheques_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaCheques_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaCheques_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaChequesPortType
     */
    @WebEndpoint(name = "ConsultaChequesHttpEndpoint")
    public ConsultaChequesPortType getConsultaChequesHttpEndpoint() {
        return super.getPort(ConsultaChequesHttpEndpoint, ConsultaChequesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaChequesPortType
     */
    @WebEndpoint(name = "ConsultaChequesHttpEndpoint")
    public ConsultaChequesPortType getConsultaChequesHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(ConsultaChequesHttpEndpoint, ConsultaChequesPortType.class, features);
    }
    /**
     *
     * @return
     *     returns ConsultaChequesPortType
     */
    @WebEndpoint(name = "ConsultaChequesHttpsEndpoint")
    public ConsultaChequesPortType getConsultaChequesHttpsEndpoint() {
        return super.getPort(ConsultaChequesHttpsEndpoint, ConsultaChequesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaChequesPortType
     */
    @WebEndpoint(name = "ConsultaChequesHttpsEndpoint")
    public ConsultaChequesPortType getConsultaChequesHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(ConsultaChequesHttpsEndpoint, ConsultaChequesPortType.class, features);
    }
    /**
     *
     * @return
     *     returns ConsultaChequesPortType
     */
    @WebEndpoint(name = "ConsultaChequesHttpsSoap11Endpoint")
    public ConsultaChequesPortType getConsultaChequesHttpsSoap11Endpoint() {
        return super.getPort(ConsultaChequesHttpsSoap11Endpoint, ConsultaChequesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaChequesPortType
     */
    @WebEndpoint(name = "ConsultaChequesHttpsSoap11Endpoint")
    public ConsultaChequesPortType getConsultaChequesHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(ConsultaChequesHttpsSoap11Endpoint, ConsultaChequesPortType.class, features);
    }
    /**
     *
     * @return
     *     returns ConsultaChequesPortType
     */
    @WebEndpoint(name = "ConsultaChequesHttpSoap11Endpoint")
    public ConsultaChequesPortType getConsultaChequesHttpSoap11Endpoint() {
        return super.getPort(ConsultaChequesHttpSoap11Endpoint, ConsultaChequesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaChequesPortType
     */
    @WebEndpoint(name = "ConsultaChequesHttpSoap11Endpoint")
    public ConsultaChequesPortType getConsultaChequesHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(ConsultaChequesHttpSoap11Endpoint, ConsultaChequesPortType.class, features);
    }

}
