alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column INTERESES_TRASLA_REGU to COBR_APROP_INTER_TRAS_REGU;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column INTERESES_TRASLA_NO_REGU to COBR_APROP_INTER_TRAS_N_REGU;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column INTERESES_BONIF_REGU to COBR_APROP_INTER_BONIF_REGU;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column INTERESES_BONIF_NO_REGU to COBR_APROP_INTER_BONIF_N_REGU;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column FECHA_VENCIMIENTO to DEB_IMPU_GRAL_FECHA_VENC;
  
alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMPORTE_PRIMER_VENCIMIENTO to DEB_IMPU_GRAL_IMPOR_PRIM_VENC;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMPORTE_SEGUNDO_VENCIMIENTO to DEB_IMPU_GRAL_IMPOR_SEG_VENC;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column SALDO_PRIMER_VENCIMIENTO to DEB_IMPU_GRAL_SALDO_PRIM_VENC;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_ESTADO_ACUERDO_FACT to DEB_IMPU_GRAL_ESTAD_ACUER_FACT;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column ESTADO_CONCEPTO_TERCEROS to DEB_IMPU_GRAL_ESTAD_CONCEP_TER;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column POSIBILIDAD_DESTRANFERENCIA to DEB_IMPU_GRAL_POSIB_DESTRANF;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMP_TERCEROS_TRANSFERIBLES to DEB_IMPU_GRAL_IMP_TER_TRANSF;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMP_PRIMER_VENC_CON_TERCEROS to DEB_IMPU_IMP_PRIM_VEN_C_TER;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMPORTE_SEG_VENC_TERCEROS to DEB_IMPU_IMP_SEG_VEN_C_TER;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CODIGO_ESTADO_FACTURA to DEB_IMPU_GRAL_COD_EST_FAC;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_MARCA_RECLAMO to DEB_IMPU_GRAL_MARCA_RECLAMO;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_MARCA_CYQ to DEB_IMPU_GRAL_MARCA_CYQ;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMP_GRAL_FECHA_EMISION to DEB_IMPU_GRAL_FECHA_EMISION;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMP_GRAL_NUMERO_CONVENIO to DEB_IMPU_GRAL_NUMERO_CONVENIO;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMP_GRAL_CUOTA to DEB_IMPU_GRAL_CUOTA;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMP_GRAL_FECHA_ULT_PAGO_PARC to DEB_IMPU_FECHA_ULT_PAGO_PARC;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMP_GRAL_FECHA_ULT_PUESTA_COB to DEB_IMPU_FECHA_ULT_PUESTA_COB;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_RAZON_SOCIAL_CLIENTE to DEB_TAG_RAZON_SOC_CLI;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_TIPO_CLIENTE to DEB_TAG_TIPO_CLIENTE;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_CICLO_FACTURACION to DEB_TAG_CICLO_FACTURACION;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_MARKETING_CUSTOMER_GROUP to DEB_TAG_MARKET_CUSTOM_GROUP;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_TIPO_FACTURA to DEB_TAG_TIPO_FACTURA;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_FECHA_VENCIMIENTO_MORA to DEB_DAK_FECHA_VENC_MORA;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_INDICADOR_PETICION_CORTE to DEB_DAK_INDIC_PETIC_CORTE;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DEB_CODIGO_TARIFA to DEB_DAK_CODIGO_TARIFA;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column SALDO_TER_FINANCIA_NO_TRANSF to DEB_SALD_TER_FINANC_NO_TRANSF;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column SALDO_TER_FINANCIA_TRANSF to DEB_SALD_TER_FINANC_TRANSF;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column SALDO_TER_NO_FINANCIA_TRANSF to DEB_SALD_TER_N_FINANC_TRANSF;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column MEDIO_PAGO_CUENTA to CRED_MED_PAG_CUEN;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column MEDIO_PAGO_TIPO_CREDITO to CRED_MED_PAG_TIPO_CRED;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column TIPO_COMPROBANTE to CRED_MED_PAG_TIPO_COMPR;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column MEDIO_PAGO_CLASE_COMPROBANTE to CRED_MED_PAG_CLASE_COMPR;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column SUCURSAL_COMPROBANTE to CRED_MED_PAG_SUC_COMPR;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column NUMERO_COMPROBANTE to CRED_MED_PAG_NUM_COMPR;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column NRO_REFERENCIA_MIC to CRED_MED_PAGO_NRO_REF_MIC;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column IMPORTE to CRED_GRAL_IMPORTE;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column SALDO to CRED_GRAL_SALDO;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column FECHA_ALTA to CRED_GRAL_FECHA_ALTA;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column FECHA_EMISION to CRED_GRAL_FECHA_EMISION;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRE_FECHA_VENCIMIENTO to CRED_GRAL_FECHA_VENC;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column FECHA_ULTIMO_MOVIMIENTO to CRED_GRAL_FECHA_ULT_MOV;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRED_MARCA_RECLAMO to CRED_GRAL_MARCA_RECLAMO;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRED_MARCA_CYQ to CRED_GRAL_MARCA_CYQ;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRED_RAZON_SOCIAL_CLIENTE to CRED_TAG_RAZ_SOC_CLI;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRED_TIPO_CLIENTE to CRED_TAG_TIPO_CLI;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRED_CICLO_FACTURACION to CRED_TAG_CICLO_FAC;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRED_MARKETING_CUSTOMER_GROUP to CRED_TAG_MARKET_CUSTOM_GROUP;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRED_TIPO_FACTURA to CRED_TAG_TIPO_FAC;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column TAG_IMPORTE_ORIGINAL to CRED_TAG_IMP_ORIG;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRED_FECHA_VENCIMIENTO_MORA to CRED_DAK_FECHA_VENC_MORA;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRED_INDICADOR_PETICION_CORTE to CRED_DAK_INDIC_PETIC_CORTE;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CRED_CODIGO_TARIFA to CRED_DAK_COD_TARIFA;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column DATOS_CLIENTE_CODIGO to ACUER_DATOS_CLI_COD_CLI;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column CODIGO_CLIENTE to ACUER_GRAL_COD_CLI;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column ACUERDO_FACTURACION to ACUER_GRAL_ACUER_FAC;

alter table SHV_MAS_REGISTRO_APLICAR_DEUDA rename column ESTADO_ACUERDO_FACT to ACUER_GRAL_EST_ACUER_FACT;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column CODIGO_CLIENTE to DEB_IMP_COD_CLI;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column CUENTA_DEBITO to DEB_IMP_GRAL_CUEN_DEB;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column TIPO_DUC to DEB_IMP_GRAL_TIPO_DUC;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column ESTADO_DUC to DEB_IMP_GRAL_ESTADO_DUC;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column ACUERDO to DEB_IMP_GRAL_ACUERDO;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column CLASE_COMPROBANTE to DEB_IMP_GRAL_CLASE_COMPR;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column SUCURSAL_COMPROBANTE to DEB_IMP_GRAL_SUC_COMPR;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column NUMERO_COMPROBANTE to DEB_IMP_GRAL_NUM_COMPR;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column NUMERO_REFERENCIA_MIC to DEB_IMP_GRAL_NUM_REF_MIC;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column FECHA_VENCIMIENTO to DEB_IMP_GRAL_FECHA_VENC;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column IMPORTE_PRIMER_VENCIMIENTO to DEB_IMPU_GRAL_IMP_PRIM_VENC;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column IMPORTE_SEGUNDO_VENCIMIENTO to DEB_IMPU_GRAL_IMP_SEG_VENC;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column SALDO_PRIMER_VENCIMIENTO to DEB_IMPU_GRAL_SAL_PRI_VENC;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column ESTADO_ACUERDO_FACTURACION to DEB_IMPU_GRAL_EST_ACUER_FACT;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column ESTADO_CONCEPTO_TERCEROS to DEB_IMPU_GRAL_EST_CONC_TER;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column POSIBILIDAD_DESTRANFERENCIA to DEB_IMPU_GRAL_POS_DEST;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column IMP_TERCEROS_TRANSFERIBLES to DEB_IMPU_GRAL_IMP_TER_TRANS;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column IMP_PRIMER_VENC_CON_TERCEROS to DEB_IMPU_IMP_PRI_VENC_C_TER;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column IMPORTE_SEG_VENC_TERCEROS to DEB_IMPU_IMP_SEG_VENC_c_TER;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column CODIGO_ESTADO_FACTURA to DEB_IMPU_GRAL_COD_EST_FACT;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column MARCA_RECLAMO to DEB_IMPU_GRAL_MARC_RECL;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column DEB_MARCA_CYQ to DEB_IMPU_GRAL_MARCA_CYQ;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column FECHA_EMISION to DEB_IMPU_GRAL_FECHA_EMIS;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column NUMERO_CONVENIO to DEB_IMPU_GRAL_NUM_CONV;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column IMP_GRAL_CUOTA to DEB_IMPU_GRAL_CUOTA;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column IMP_GRAL_FECHA_ULT_PAGO_PARC to DEB_IMP_FECHA_ULT_PAGO_PARC;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column IMP_GRAL_FECHA_ULT_PUESTA_COB to DEB_IMP_FECHA_ULT_PUES_COB;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column RAZON_SOCIAL_CLIENTE to DEB_TAG_RAZ_SOC_CLI;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column TIPO_CLIENTE to DEB_TAG_TIPO_CLI;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column CICLO_FACTURACION to DEB_TAG_CICLO_FACT;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column MARKETING_CUSTOMER_GROUP to DEB_TAG_MARK_CUSTOM_GROUP;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column TIPO_FACTURA to DEB_TAG_TIPO_FACT;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column FECHA_VENCIMIENTO_MORA to DEB_DAK_FECHA_VENC_MORA;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column INDICADOR_PETICION_CORTE to DEB_DAK_INDIC_PETIC_CORTE;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column CODIGO_TARIFA to DEB_DAK_COD_TARIFA;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column SALDO_TER_FINANCIA_NO_TRANSF to DEB_SALD_TER_FIN_N_TRANSF;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column SALDO_TER_FINANCIA_TRANSF to DEB_SALD_TER_FIN_TRANSF;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column SALDO_TER_NO_FINANCIA_TRANSF to DEB_SALD_TER_NO_FIN_TRANSF;

alter table SHV_MAS_REGISTRO_DESESTIMIENTO rename column CLIENTE_CODIGO_CLIENTE to ACUER_DAT_CLI_COD_CLI;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CODIGO_CLIENTE to CRED_CODIGO_CLIENTE;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column MEDIO_PAGO_CUENTA to CRED_MEDIO_PAGO_CUENTA;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column MEDIO_PAGO_TIPO_CREDITO to CRED_MED_PAG_TIPO_CRED;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column TIPO_COMPROBANTE to CRED_MED_PAG_TIPO_COMPR;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column MEDIO_PAGO_CLASE_COMPROBANTE to CRED_MED_PAGO_CLASE_COMPR;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column SUCURSAL_COMPROBANTE to CRED_PAG_SUC_COMPR;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column NUMERO_COMPROBANTE to CRED_MED_PAGO_NUM_COMPR;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column NRO_REFERENCIA_MIC to CRED_MED_PAGO_NRO_REF_MIC;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_TIPO_REMANENTE to REMANENTE_TIPO_REMANENTE;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column IMPORTE to CRED_GRAL_IMP;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column SALDO to CRED_GRAL_SALDO;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column FECHA_ALTA to CRED_GRAL_FECHA_ALTA;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column FECHA_EMISION to CRED_GRAL_FECHA_EMISION;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column FECHA_VENCIMIENTO to CRED_GRAL_FECHA_VENC;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column FECHA_ULTIMO_MOVIMIENTO to CRED_GRAL_FECHA_ULT_MOV;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_MARCA_RECLAMO to CRED_GRAL_MARCA_RECLAMO;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_MARCA_CYQ to CRED_GRAL_MARCA_CYQ;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_RAZON_SOCIAL_CLIENTE to CRED_TA_RAZ_SOC_CLI;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_TIPO_CLIENTE to CRED_TAG_TIPO_CLI;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_CICLO_FACTURACION to CRED_TAG_CICLO_FACT;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_MARKETING_CUSTOMER_GROUP to CRED_MARKET_CUSTOM_GROUP;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_TIPO_FACTURA to CRED_TAG_TIPO_FACT;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column TAG_IMPORTE_ORIGINAL to CRED_TAG_IMP_ORIG;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_FECHA_VENCIMIENTO_MORA to CRED_DAK_FECHA_VENC_MORA;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_INDICADOR_PETICION_CORTE to CRED_DAK_INDIC_PETIC_CORTE;

alter table SHV_MAS_REGISTRO_GANANCIAS rename column CRED_CODIGO_TARIFA to CRED_DAK_COD_TARIFA;

alter table SHV_MAS_REGISTRO_REINTEGRO rename column INTERESES_TRASLA_REGU to COB_CAR_INT_TRASLA_REGU;

alter table SHV_MAS_REGISTRO_REINTEGRO rename column INTERESES_TRASLA_NO_REGU to COB_CAR_INT_TRASLA_N_REGU;

alter table SHV_MAS_REGISTRO_REINTEGRO rename column INTERESES_BONIF_REGU to COB_CAR_INT_BONIF_REGU;

alter table SHV_MAS_REGISTRO_REINTEGRO rename column INTERESES_BONIF_NO_REGU to COB_CAR_INT_BONIF_N_REGU;

alter table SHV_MAS_REGISTRO_REINTEGRO rename column MEDIO_PAGO_CUENTA to CRED_MED_PAGO_CUENTA;

alter table SHV_MAS_REGISTRO_REINTEGRO rename column MEDIO_PAGO_TIPO_CREDITO to CRED_MED_PAGO_TIPO_CRED; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column TIPO_COMPROBANTE to CRED_MED_PAGO_TIPO_COMPR; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column MEDIO_PAGO_CLASE_COMPROBANTE to CRED_MED_PAGO_CLASE_COMPR; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column SUCURSAL_COMPROBANTE to CRED_MED_PAGO_SUC_COMPR; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column NUMERO_COMPROBANTE to CRED_MED_PAGO_NUM_COMPR; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column NRO_REFERENCIA_MIC to CRED_MED_PAGO_NRO_REF_MIC; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column IMPORTE to CRED_GRAL_IMP; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column SALDO to CRED_GRAL_SALDO; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column FECHA_ALTA to CRED_GRAL_FECHA_ALTA; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column FECHA_EMISION to CRED_GRAL_FECHA_EMISION; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column FECHA_VENCIMIENTO to CRED_GRAL_FECHA_VENC; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column FECHA_ULTIMO_MOVIMIENTO to CRED_GRAL_FECHA_ULT_MOV; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column CRED_MARCA_RECLAMO to CRED_GRAL_MARCA_RECLAMO; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column CRED_RAZON_SOCIAL_CLIENTE to CRED_TAG_RAZ_SOC_CLI; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column CRED_TIPO_CLIENTE to CRED_TAG_TIPO_CLI; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column CRED_CICLO_FACTURACION to CRED_TAG_CICLO_FACT; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column CRED_MARKETING_CUSTOMER_GROUP to CRED_MARKET_CUSTOM_GROUP; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column TAG_IMPORTE_ORIGINAL to CRED_TAG_IMP_ORIG; 

alter table SHV_MAS_REGISTRO_REINTEGRO rename column CODIGO_CLIENTE to ACUER_COD_CLI; 

exit;