LOAD DATA
CHARACTERSET WE8ISO8859P1
INSERT
INTO TABLE SHV_MIG_VALOR_INTERDEPOSITO
 FIELDS TERMINATED BY '|'
 TRAILING NULLCOLS
(
 ID_SEGMENTO CHAR TERMINATED BY '|',
 ID_BANCO_DEPOSITO CHAR TERMINATED BY '|',
 IMPORTE DECIMAL EXTERNAL,
 SALDO_DISPONIBLE DECIMAL EXTERNAL,
 OBSERVACIONES CHAR TERMINATED BY '|',
 NUMERO_PARTIDA_CONTABLE INTEGER EXTERNAL,
 OPERACION_ASOCIADA INTEGER EXTERNAL,
 ID_MOTIVO INTEGER EXTERNAL,
 FECHA_ALTA DATE "DD/MM/YYYY HH24:MI:SS",
 USUARIO_AUTORIZACION CHAR TERMINATED BY '|',
 USUARIO_EJECUTIVO CHAR TERMINATED BY '|',
 USUARIO_ASISTENTE CHAR TERMINATED BY '|',
 ID_ORIGEN INTEGER EXTERNAL,
 NUMERO_INTERDEPOSITO INTEGER EXTERNAL,
 CODIGO_ORGANISMO CHAR TERMINATED BY '|',
 FECHA_INTERDEPOSITO DATE "DD/MM/YYYY HH24:MI:SS",
 ID "SEQ_SHV_MIG_ID.NEXTVAL"
)

