
ALTER TABLE SHV_COB_DESCOBRO ADD ID_EMPRESA VARCHAR2(2 BYTE);
ALTER TABLE SHV_COB_DESCOBRO ADD ID_SEGMENTO VARCHAR2(3 BYTE);
ALTER TABLE SHV_COB_DESCOBRO ADD ID_ANALISTA VARCHAR2(9 BYTE);
ALTER TABLE SHV_COB_DESCOBRO ADD ANALISTA VARCHAR2(50 BYTE);
ALTER TABLE SHV_COB_DESCOBRO ADD ID_COPROPIETARIO VARCHAR2(9 BYTE);
ALTER TABLE SHV_COB_DESCOBRO ADD COPROPIETARIO VARCHAR2(50 BYTE);
ALTER TABLE SHV_COB_DESCOBRO ADD ID_MOTIVO_DESCOBRO NUMBER;
ALTER TABLE SHV_COB_DESCOBRO ADD IMPORTE_TOTAL NUMBER(17,4);
ALTER TABLE SHV_COB_DESCOBRO ADD FECHA_ALTA DATE;
ALTER TABLE SHV_COB_DESCOBRO ADD USUARIO_ALTA VARCHAR2(9 BYTE);
ALTER TABLE SHV_COB_DESCOBRO ADD FECHA_DERIVACION DATE;
ALTER TABLE SHV_COB_DESCOBRO ADD USUARIO_DERIVACION VARCHAR2(9 BYTE);
ALTER TABLE SHV_COB_DESCOBRO ADD FECHA_REVERSION DATE;
ALTER TABLE SHV_COB_DESCOBRO ADD USUARIO_REVERSION VARCHAR2(9 BYTE);
ALTER TABLE SHV_COB_DESCOBRO ADD FECHA_ULTIMA_MODIFICACION DATE;
ALTER TABLE SHV_COB_DESCOBRO ADD USUARIO_ULTIMA_MODIFICACION VARCHAR2(9 BYTE);
ALTER TABLE SHV_COB_DESCOBRO ADD ID_DESCOBRO_PADRE VARCHAR2(25 BYTE);

--u573005, fabio.giaquinta.ruiz, agrego el campo observacion para visualizarlo en la exportacion excel
ALTER TABLE SHV_COB_DESCOBRO ADD OBSERVACION VARCHAR2(250 BYTE);


ALTER TABLE SHV_COB_DESCOBRO
ADD CONSTRAINT DESCOBRO_EMPRESA_FK
FOREIGN KEY (ID_EMPRESA) REFERENCES SHV_PARAM_EMPRESA(ID_EMPRESA) ENABLE;

ALTER TABLE SHV_COB_DESCOBRO
ADD CONSTRAINT DESCOBRO_SEGMENTO_FK
FOREIGN KEY (ID_SEGMENTO) REFERENCES SHV_PARAM_SEGMENTO(ID_SEGMENTO) ENABLE;

ALTER TABLE SHV_COB_DESCOBRO
ADD CONSTRAINT DESCOBRO_MOTIVO_FK
FOREIGN KEY (ID_MOTIVO_DESCOBRO) REFERENCES SHV_PARAM_MOTIVO_DESCOBRO(ID_MOTIVO_DESCOBRO) ENABLE;

ALTER TABLE SHV_COB_DESCOBRO ADD ID_COBRO NUMBER;

-- u573005, fabio.giaquinta.ruiz
-- agrego la columna id_operacion_original para trabajar con descobros en la simulacion/imputacion
ALTER TABLE SHV_COB_OPERACION ADD ID_OPERACION_ORIGINAL NUMBER;

--
--u573005, fabio.giaquinta.ruiz, se agregan columnas para manejar la informacion de los cargos generados para el tratamiento a la diferencia credito a proxima factura
--
ALTER TABLE SHV_COB_TRATAMIENTO_DIFERENCIA ADD ESTADO_CARGO_GENERADO VARCHAR2(20);
ALTER TABLE SHV_COB_TRATAMIENTO_DIFERENCIA ADD COBRADOR_INTERES_REAL_TRAS NUMBER(17,4);
ALTER TABLE SHV_COB_TRATAMIENTO_DIFERENCIA ADD COBRADOR_INTERES_REAL_NRG_TRAS NUMBER(17,4);
ALTER TABLE SHV_COB_TRATAMIENTO_DIFERENCIA ADD COBRADOR_INTERES_REAL_RG_TRAS NUMBER(17,4);
ALTER TABLE SHV_COB_TRATAMIENTO_DIFERENCIA ADD SISTEMA_ACUERDO_CONTRACARGO VARCHAR2(7);
ALTER TABLE SHV_COB_TRATAMIENTO_DIFERENCIA ADD ACUERDO_CONTRACARGO VARCHAR2(20);
ALTER TABLE SHV_COB_TRATAMIENTO_DIFERENCIA ADD ESTADO_ACUERDO_CONTRACARGO VARCHAR2(20);
ALTER TABLE SHV_COB_TRATAMIENTO_DIFERENCIA ADD ID_CLIENTE_ACUERDO_CONTRACARGO NUMBER;

--
--u573005, fabio.giaquinta.ruiz, se agregan columnas para manejar la informacion de los cargos generados para el debito a proxima factura de mic
--
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_MIC ADD ESTADO_CARGO_GENERADO VARCHAR2(20);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_MIC ADD COBRADOR_INTERES_REAL_NRG_TRAS NUMBER(17,4);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_MIC ADD COBRADOR_INTERES_REAL_RG_TRAS NUMBER(17,4);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_MIC ADD SISTEMA_ACUERDO_CONTRACARGO VARCHAR2(7);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_MIC ADD ACUERDO_CONTRACARGO VARCHAR2(20);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_MIC ADD ESTADO_ACUERDO_CONTRACARGO VARCHAR2(20);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_MIC ADD ID_CLIENTE_ACUERDO_CONTRACARGO NUMBER;

--
--u573005, fabio.giaquinta.ruiz, se agregan columnas para manejar la informacion de los cargos generados para el debito a proxima factura de calipso
--
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_CLP ADD ESTADO_CARGO_GENERADO VARCHAR2(20);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_CLP ADD COBRADOR_INTERES_REAL_TRAS NUMBER(17,4);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_CLP ADD SISTEMA_ACUERDO_CONTRACARGO VARCHAR2(7);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_CLP ADD ACUERDO_CONTRACARGO VARCHAR2(20);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_CLP ADD ESTADO_ACUERDO_CONTRACARGO VARCHAR2(20);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_CLP ADD ID_CLIENTE_ACUERDO_CONTRACARGO NUMBER;

--
--u573005, fabio.giaquinta.ruiz, se agregan columnas para manejar la informacion de los cargos generados para las facturas
--
ALTER TABLE SHV_COB_FACTURA ADD ESTADO_CARGO_GENERADO VARCHAR2(20);
ALTER TABLE SHV_COB_FACTURA ADD SISTEMA_ACUERDO_CONTRACARGO VARCHAR2(7);
ALTER TABLE SHV_COB_FACTURA ADD ACUERDO_CONTRACARGO VARCHAR2(20);
ALTER TABLE SHV_COB_FACTURA ADD ESTADO_ACUERDO_CONTRACARGO VARCHAR2(20);
ALTER TABLE SHV_COB_FACTURA ADD ID_CLIENTE_ACUERDO_CONTRACARGO NUMBER;

--
-- u573005, fabio.giaquinta.ruiz, Se agregan columnas para manejar el contracargo cruzado del interes de la factura
--
ALTER TABLE SHV_COB_FACTURA ADD ORIGEN_CARGO VARCHAR2(30);
ALTER TABLE SHV_COB_FACTURA ADD LEYENDA_FACTURA_INTERES VARCHAR2(50);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_CLP ADD ORIGEN_INTERES VARCHAR2(30);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_MIC ADD ORIGEN_INTERES VARCHAR2(30);
ALTER TABLE SHV_COB_TRATAMIENTO_DIFERENCIA ADD ORIGEN_INTERES VARCHAR2(30);

--
-- u573005, fabio.giaquinta.ruiz, Se agregan columnas para manejar el interes dividido de la factura de mic
--
ALTER TABLE SHV_COB_FACTURA_MIC ADD COBRADOR_INTERES_TRASLA_NO_REG NUMBER(17,4);
ALTER TABLE SHV_COB_FACTURA_MIC ADD COBRADOR_INTERES_TRASLA_REGU NUMBER(17,4);


ALTER TABLE SHV_COB_DESCOBRO MODIFY ID_DESCOBRO_PADRE NUMBER;

ALTER TABLE SHV_COB_DESCOBRO ADD TIPO_ID_REVERSION_PADRE VARCHAR2 (8 BYTE);

ALTER TABLE SHV_COB_DESCOBRO_DOC_RELAC ADD FECHA_IMPUTACION DATE;
ALTER TABLE SHV_COB_DESCOBRO_DOC_RELAC ADD SISTEMA_ORIGEN VARCHAR2(7 BYTE);


Exit;
