LOAD DATA
CHARACTERSET WE8ISO8859P1
INSERT
INTO TABLE SHV_MIG_BOLETA_DEP_CHEQUE_PD
 FIELDS TERMINATED BY '|'
 TRAILING NULLCOLS
(
 ID_SEGMENTO CHAR TERMINATED BY '|',
 ID_CLIENTE_LEGADO INTEGER EXTERNAL,
 ID_ANALISTA CHAR TERMINATED BY '|',
 ID_COPROPIETARIO CHAR TERMINATED BY '|',
 NUMERO_ACUERDO	INTEGER EXTERNAL,
 IMPORTE DECIMAL EXTERNAL,
 SALDO_DISPONIBLE DECIMAL EXTERNAL,
 OBSERVACIONES CHAR TERMINATED BY '|',
 NUMERO_PARTIDA_CONTABLE INTEGER EXTERNAL,
 OPERACION_ASOCIADA INTEGER EXTERNAL,
 ID_MOTIVO INTEGER EXTERNAL,
 USUARIO_AUTORIZACION CHAR TERMINATED BY '|',
 USUARIO_EJECUTIVO CHAR TERMINATED BY '|',
 USUARIO_ASISTENTE CHAR TERMINATED BY '|',
 ID_ORIGEN INTEGER EXTERNAL,
 NUMERO_BOLETA INTEGER EXTERNAL,
 EMAIL CHAR TERMINATED BY '|',
 FECHA_ALTA DATE "DD/MM/YYYY HH24:MI:SS",
 NUMERO_CHEQUE INTEGER EXTERNAL,
 ID_BANCO_ORIGEN CHAR TERMINATED BY '|',
 FECHA_DEPOSITO	DATE "DD/MM/YYYY HH24:MI:SS",
 FECHA_RECIBO DATE "DD/MM/YYYY HH24:MI:SS",
 FECHA_VENCIMIENTO DATE "DD/MM/YYYY HH24:MI:SS",
 ID_RECIBO_PREIMPRESO INTEGER EXTERNAL,
 NRO_CONSTANCIA_RECEPCION INTEGER EXTERNAL,
 ESTADO CHAR TERMINATED BY '|',
 ID "SEQ_SHV_MIG_ID.NEXTVAL"
)

