--Grant para funcion loguearse con el usuario que no es owner del schema	
	create or replace synonym SHV_COB_ED_ADJUNTO for A002018.SHV_COB_ED_ADJUNTO;
	create or replace synonym SHV_COB_ED_CLIENTE for A002018.SHV_COB_ED_CLIENTE;
	CREATE OR REPLACE SYNONYM SHV_COB_ED_COBRO FOR A002018.SHV_COB_ED_COBRO;
	CREATE OR REPLACE SYNONYM SHV_COB_ED_CREDITO FOR A002018.SHV_COB_ED_CREDITO;
	CREATE OR REPLACE SYNONYM SHV_COB_ED_DEBITO FOR A002018.SHV_COB_ED_DEBITO;
	CREATE OR REPLACE SYNONYM SHV_COB_ED_MEDIO_PAGO_CLIENTE FOR A002018.SHV_COB_ED_MEDIO_PAGO_CLIENTE;
	CREATE OR REPLACE SYNONYM SHV_COB_ED_OTROS_MEDIO_PAGO FOR A002018.SHV_COB_ED_OTROS_MEDIO_PAGO;
	create or replace synonym SHV_COB_ED_TRATAMIENTO_DIF for A002018.SHV_COB_ED_TRATAMIENTO_DIF;
	create or replace synonym SHV_WF_TAREA_COBRO for A002018.SHV_WF_TAREA_COBRO;
	create or replace synonym SHV_PARAM_MOTIVO_COBRO for A002018.SHV_PARAM_MOTIVO_COBRO;
	create or replace synonym SEQ_SHV_COB_ED_MED_PAG_CLIENTE for A002018.SEQ_SHV_COB_ED_MED_PAG_CLIENTE;