ALTER TABLE SHV_MAS_REGISTRO MODIFY DESCRIPCION_ERROR_REGISTRO VARCHAR2(325 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA MODIFY TIPO_REMANENTE VARCHAR2(40 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS MODIFY CRED_TIPO_REMANENTE VARCHAR2(40 BYTE);

exit;