----------------------
-- Vista de busqueda 
----------------------

CREATE OR REPLACE VIEW SHV_SOP_BUSQUEDA_VALORES (ID_VALOR, EMPRESA, SEGMENTO, ID_CLIENTE_LEGADO, RAZON_SOCIAL_CLIENTE_AGRUPADOR, TIPO_VALOR, ESTADO_VALOR, ORIGEN, ACUERDO, NRO_VALOR, IMPORTE, BD_IMPRESA, BD_ENVIADA_MAIL, FECHA_ALTA, ID_ANALISTA, NRO_RECIBO, ID_CONSTANCIA_RECEPCION, OPERACION_ASOCIADA, FACTURA_RELACIONADA, DOCUMENTACION_ORIG_RECIBIDA, MOTIVO, BANCO_DEPOSITO, ID_COPROPIETARIO, USUARIO_AUTORIZACION, NUMERO_DOCUMENTO_CONTABLE, MOTIVO_SUSPENSION, EJECUTIVO, ASISTENTE, SALDO_DISPONIBLE, FECHA_INGRESO_RECIBO, FECHA_EMISION, FECHA_TRANSFERENCIA, VALOR_PADRE, ARCHIVO_DE_VALORES_A_CONCILIAR, FECHA_DEPOSITO, FECHA_ULTIMO_ESTADO, FECHA_DISPONIBLE, NRO_BOLETA, DESCRIPCION_BANCO_ORIGEN, FECHA_VENCIMIENTO, ID_TIPO_RETENCION, DESCRIPCION_TIPO_RETENCION, 
NRO_CUIT_RETENCION, PROVINCIA_RETENCION, ID_PROVINCIA_RETENCION, REFERENCIA_VALOR, ID_ANALISTA_TEAM_COMERCIAL, ID_SUPERVISOR_TEAM_COMERCIAL, 
  ID_GERENTE_REG_TEAM_COMERCIAL, CODIGO_ORGANISMO, OBSERVACIONES, ID_ESTADO_VALOR, ID_TIPO_VALOR, ID_ORIGEN, ID_EMPRESA, ID_SEGMENTO, FECHA_VALOR, COBRO_FORMATEADO, ID_BOLETA, FECHA_BUSQUEDA, NRO_CUIT_TRANSACCION)
AS
  (
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO EFECTIVO Sprint3, incluye defecto 133
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL AS FACTURA_RELACIONADA ,
    NVL (SVVE.DOCUMENTACION_ORIG_RECIBIDA, 'NO') DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVVE.FECHA_DEPOSITO                            AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SVVE.NUMERO_BOLETA                  AS NRO_BOLETA ,
    NULL                                AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    --FERNANDO.FORMENTO 01/04/2016 - mejora de contabilidad
    NULL                                AS ID_PROVINCIA_RETENCION,
    TO_CHAR(SVVE.NUMERO_BOLETA)         AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR)                 AS COBRO_FORMATEADO,
    NULL                                               AS ID_BOLETA,
    TO_CHAR(SVVE.FECHA_DEPOSITO, 'DD/MM/YYYY HH24:MI') AS FECHA_BUSQUEDA,
    --FERNANDO.FORMENTO 18/02/2016 - mejora de performance de contabilidad
    NULL AS NRO_CUIT_TRANSACCION
  FROM SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_EFECTIVO SVVE
  ON SVV.ID_VALOR = SVVE.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO CHEQUE
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL AS FACTURA_RELACIONADA ,
    NVL (SVVC.DOCUMENTACION_ORIG_RECIBIDA, 'NO') DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVVC.FECHA_DEPOSITO                            AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SVVC.NUMERO_BOLETA                  AS NRO_BOLETA ,
    SPBORIGEN.DESCRIPCION               AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    --FERNANDO.FORMENTO 01/04/2016 - mejora de contabilidad
    NULL                                AS ID_PROVINCIA_RETENCION,
    TO_CHAR(SVVC.NUMERO_CHEQUE)         AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR)                 AS COBRO_FORMATEADO,
    NULL                                               AS ID_BOLETA,
    TO_CHAR(SVVC.FECHA_DEPOSITO, 'DD/MM/YYYY HH24:MI') AS FECHA_BUSQUEDA,
    --FERNANDO.FORMENTO 18/02/2016 - mejora de performance de contabilidad
    NULL AS NRO_CUIT_TRANSACCION
  FROM SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_CHEQUE SVVC
  ON SVV.ID_VALOR = SVVC.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPBORIGEN
  ON SVVC.ID_BANCO_ORIGEN = SPBORIGEN.ID_BANCO
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO CHEQUE DIFERIDO
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL AS FACTURA_RELACIONADA ,
    NVL (SVVCPD.DOCUMENTACION_ORIG_RECIBIDA, 'NO') DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVVCPD.FECHA_DEPOSITO                          AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SVVCPD.NUMERO_BOLETA                AS NRO_BOLETA ,
    SPBORIGEN.DESCRIPCION               AS DESCRIPCION_BANCO_ORIGEN ,
    SVVCPD.FECHA_VENCIMIENTO            AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    --FERNANDO.FORMENTO 01/04/2016 - mejora de contabilidad
    NULL                                AS ID_PROVINCIA_RETENCION,
    TO_CHAR(SVVCPD.NUMERO_CHEQUE)       AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR)                      AS COBRO_FORMATEADO,
    NULL                                                    AS ID_BOLETA,
    TO_CHAR(SVVCPD.FECHA_VENCIMIENTO, 'DD/MM/YYYY HH24:MI') AS FECHA_BUSQUEDA,
    --FERNANDO.FORMENTO 18/02/2016 - mejora de performance de contabilidad
    NULL AS NRO_CUIT_TRANSACCION
  FROM
    --FABIO.GIAQUINTA.RUIZ 13/08/2014
    --JOINS ORDENADOS POR TABLA CON MAYOR CANTIDAD DE REGISTROS
    SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_CHEQUE_PD SVVCPD
  ON SVV.ID_VALOR = SVVCPD.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO SPBORIGEN
  ON SVVCPD.ID_BANCO_ORIGEN = SPBORIGEN.ID_BANCO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO TRANSFERENCIAS
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL AS FACTURA_RELACIONADA ,
    NVL (SVVT.DOCUMENTACION_ORIG_RECIBIDA, 'NO') DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    SVVT.FECHA_TRANSFERENCIA                       AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    NULL                                           AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    NULL                                AS NRO_BOLETA ,
    NULL                                AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    --FERNANDO.FORMENTO 01/04/2016 - mejora de contabilidad
    NULL                                AS ID_PROVINCIA_RETENCION,
    TO_CHAR(SVVT.NUMERO_REFERENCIA)     AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR)                      AS COBRO_FORMATEADO,
    NULL                                                    AS ID_BOLETA,
    TO_CHAR(SVVT.FECHA_TRANSFERENCIA, 'DD/MM/YYYY HH24:MI') AS FECHA_BUSQUEDA,
    --FERNANDO.FORMENTO 18/02/2016 - mejora de performance de contabilidad
    SVVT.CUIT AS NRO_CUIT_TRANSACCION
  FROM
    --FABIO.GIAQUINTA.RUIZ 13/08/2014
    --JOINS ORDENADOS POR TABLA CON MAYOR CANTIDAD DE REGISTROS
    SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_TRANSFERENCIA SVVT
  ON SVV.ID_VALOR = SVVT.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO SPBORIGEN
  ON SVVT.ID_BANCO_ORIGEN = SPBORIGEN.ID_BANCO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO INTERDEPOSITO
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL                 AS FACTURA_RELACIONADA ,
    NULL                 AS DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    NULL                                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVVI.FECHA_INTERDEPOSITO                       AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    NULL                                AS NRO_BOLETA ,
    NULL                                AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    --FERNANDO.FORMENTO 01/04/2016 - mejora de contabilidad
    NULL                                AS ID_PROVINCIA_RETENCION,
    TO_CHAR(SVVI.NUMERO_INTERDEPOSITO)  AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    SVVI.CODIGO_ORGANISMO               AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR)                      AS COBRO_FORMATEADO,
    NULL                                                    AS ID_BOLETA,
    TO_CHAR(SVVI.FECHA_INTERDEPOSITO, 'DD/MM/YYYY HH24:MI') AS FECHA_BUSQUEDA,
    --FERNANDO.FORMENTO 18/02/2016 - mejora de performance de contabilidad
    NULL AS NRO_CUIT_TRANSACCION
  FROM
    --FABIO.GIAQUINTA.RUIZ 13/08/2014
    --JOINS ORDENADOS POR TABLA CON MAYOR CANTIDAD DE REGISTROS
    SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_INTERDEPOSITO SVVI
  ON SVV.ID_VALOR = SVVI.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- AVISO DE PAGO RETENCIONES
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    NULL             AS ORIGEN ,
    NULL             AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    NULL                                          AS BD_IMPRESA ,
    NULL                                          AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    NULL                                          AS NRO_RECIBO ,
    NULL                                          AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    DECODE (SVVR.ID_TIPO_COMPROBANTE, NULL, NULL, (SPTC.DESCRIPCION
    ||' '
    ||SPTLC.DESCRIPCION
    ||' '
    ||SVVR.SUCURSAL_COMPROBANTE
    ||'-'
    ||SVVR.NUMERO_COMPROBANTE)) AS FACTURA_RELACIONADA -- >> PARA RETENCIONES
    ,
    NULL                 AS DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    NULL                 AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    SVVR.FECHA_RECIBO                              AS FECHA_INGRESO_RECIBO ,
    TO_CHAR(SVVR.FECHA_EMISION, 'DD/MM/YYYY')      AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    NULL                                           AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    NULL                                   AS NRO_BOLETA ,
    NULL                                   AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                   AS FECHA_VENCIMIENTO ,
    SPTRI.ID_TIPO_RETENCION_IMPUESTO       AS ID_TIPO_RETENCION,
    SPTRI.DESCRIPCION                      AS DESCRIPCION_TIPO_RETENCION,
    SVVR.CUIT                              AS NRO_CUIT_RETENCION,
    SPJ.DESCRIPCION                        AS PROVINCIA_RETENCION,
    --FERNANDO.FORMENTO 01/04/2016 - mejora de contabilidad
    SPJ.ID_PROVINCIA                       AS ID_PROVINCIA_RETENCION,
    TO_CHAR(SVVR.NRO_CONSTANCIA_RETENCION) AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS      AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS    AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL             AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                   AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                      AS OBSERVACIONES,
    --DATOS DE USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR)                AS COBRO_FORMATEADO,
    NULL                                              AS ID_BOLETA,
    TO_CHAR(SVVR.FECHA_EMISION, 'DD/MM/YYYY HH24:MI') AS FECHA_BUSQUEDA,
    --FERNANDO.FORMENTO 18/02/2016 - mejora de performance de contabilidad
    NULL AS NRO_CUIT_TRANSACCION
  FROM
    --FABIO.GIAQUINTA.RUIZ 13/08/2014
    --JOINS ORDENADOS POR TABLA CON MAYOR CANTIDAD DE REGISTROS
    SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_VALOR_RETENCION SVVR
  ON SVV.ID_VALOR = SVVR.ID_VALOR
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_TIPO_COMPROBANTE SPTC
  ON SVVR.ID_TIPO_COMPROBANTE = SPTC.ID_TIPO_COMPROBANTE
  LEFT JOIN SHV_PARAM_TIPO_LETRA_COMP SPTLC
  ON SVVR.ID_TIPO_LETRA_COMPROBANTE = SPTLC.ID_TIPO_LETRA_COMPROBANTE
  LEFT JOIN SHV_PARAM_JURISDICCION SPJ
  ON SVVR.ID_JURISDICCION = SPJ.ID_JURISDICCION
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  LEFT JOIN SHV_PARAM_TIPO_RET_IMPUESTO SPTRI
  ON SVVR.ID_TIPO_RETENCION_IMPUESTO = SPTRI.ID_TIPO_RETENCION_IMPUESTO
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- BOLETA DEPOSITO EFECTIVO
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    SBB.IMPRESION_ESTADO                          AS BD_IMPRESA ,
    SBB.EMAIL_ENVIO_ESTADO                        AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    STRP.NUMERO_RECIBO                            AS NRO_RECIBO ,
    SVCRV.ID_CONSTANCIA_RECEPCION                 AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL                 AS FACTURA_RELACIONADA ,
    NULL                 AS DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    SVBDE.FECHA_RECIBO                             AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVBDE.FECHA_DEPOSITO                           AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SBB.NUMERO_BOLETA                   AS NRO_BOLETA ,
    NULL                                AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    --FERNANDO.FORMENTO 01/04/2016 - mejora de contabilidad
    NULL                                AS ID_PROVINCIA_RETENCION,
    TO_CHAR(SBB.NUMERO_BOLETA)          AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR)                  AS COBRO_FORMATEADO,
    SBB.ID_BOLETA                                       AS ID_BOLETA,
    TO_CHAR(SVBDE.FECHA_DEPOSITO, 'DD/MM/YYYY HH24:MI') AS FECHA_BUSQUEDA,
    --FERNANDO.FORMENTO 18/02/2016 - mejora de performance de contabilidad
    NULL AS NRO_CUIT_TRANSACCION
  FROM
    --FABIO.GIAQUINTA.RUIZ 13/08/2014
    --JOINS ORDENADOS POR TABLA CON MAYOR CANTIDAD DE REGISTROS
    SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_BOLETA_DEP_EFECTIVO SVBDE
  ON SVV.ID_VALOR = SVBDE.ID_VALOR
  INNER JOIN SHV_BOL_BOLETA SBB
  ON SVBDE.ID_BOLETA = SBB.ID_BOLETA
  LEFT JOIN SHV_TAL_RECIBO_PREIMPRESO STRP
  ON STRP.ID_RECIBO_PREIMPRESO = SVBDE.ID_RECIBO_PREIMPRESO
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_VAL_CONSTANCIA_RECEP_VALOR SVCRV
  ON SVV.ID_VALOR = SVCRV.ID_VALOR
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- BOLETA DEPOSITO CHEQUE
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    SBB.IMPRESION_ESTADO                          AS BD_IMPRESA ,
    SBB.EMAIL_ENVIO_ESTADO                        AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    STRP.NUMERO_RECIBO                            AS NRO_RECIBO ,
    SVCRV.ID_CONSTANCIA_RECEPCION                 AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL                 AS FACTURA_RELACIONADA ,
    NULL                 AS DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    SVBDC.FECHA_RECIBO                             AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVBDC.FECHA_DEPOSITO                           AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SBB.NUMERO_BOLETA                   AS NRO_BOLETA ,
    SPBORIGEN.DESCRIPCION               AS DESCRIPCION_BANCO_ORIGEN ,
    NULL                                AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    --FERNANDO.FORMENTO 01/04/2016 - mejora de contabilidad
    NULL                                AS ID_PROVINCIA_RETENCION,
    TO_CHAR(SVBDC.NUMERO_CHEQUE)        AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR)                  AS COBRO_FORMATEADO,
    SBB.ID_BOLETA                                       AS ID_BOLETA,
    TO_CHAR(SVBDC.FECHA_DEPOSITO, 'DD/MM/YYYY HH24:MI') AS FECHA_BUSQUEDA,
    --FERNANDO.FORMENTO 18/02/2016 - mejora de performance de contabilidad
    NULL AS NRO_CUIT_TRANSACCION
  FROM SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  LEFT JOIN SHV_VAL_BOLETA_DEP_CHEQUE SVBDC
  ON SVV.ID_VALOR = SVBDC.ID_VALOR
  INNER JOIN SHV_BOL_BOLETA SBB
  ON SVBDC.ID_BOLETA = SBB.ID_BOLETA
  LEFT JOIN SHV_TAL_RECIBO_PREIMPRESO STRP
  ON STRP.ID_RECIBO_PREIMPRESO = SVBDC.ID_RECIBO_PREIMPRESO
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_VAL_CONSTANCIA_RECEP_VALOR SVCRV
  ON SVV.ID_VALOR = SVCRV.ID_VALOR
  LEFT JOIN SHV_PARAM_BANCO SPBORIGEN
  ON SVBDC.ID_BANCO_ORIGEN = SPBORIGEN.ID_BANCO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  ---------------------------------------------------------------------------------------
  UNION
  ---------------------------------------------------------------------------------------
  -- BOLETA DEPOSITO CHEQUE DIFERIDO
  ---------------------------------------------------------------------------------------
  SELECT
    -- DATOS GENERALES DE LA VISTA, MODELO ORIGINAL
    SVV.ID_VALOR ,
    SPE.DESCRIPCION       AS EMPRESA ,
    SPS.DESCRIPCION       AS SEGMENTO ,
    SVV.ID_CLIENTE_LEGADO AS ID_CLIENTE_LEGADO ,
    SVV.RAZON_SOCIAL_CLIENTE_AGRUPADOR ,
    SPTV.DESCRIPCION AS TIPO_VALOR ,
    SPWE.DESCRIPCION AS ESTADO_VALOR ,
    SPO.DESCRIPCION  AS ORIGEN ,
    SVV.ID_ACUERDO   AS ACUERDO ,
    SVV.NUMERO_VALOR AS NRO_VALOR ,
    SVV.IMPORTE ,
    SBB.IMPRESION_ESTADO                          AS BD_IMPRESA ,
    SBB.EMAIL_ENVIO_ESTADO                        AS BD_ENVIADA_MAIL ,
    TO_CHAR(SVV.FECHA_ALTA, 'DD/MM/YYYY HH24:MI') AS FECHA_ALTA ,
    SVV.ID_ANALISTA                               AS ID_ANALISTA ,
    STRP.NUMERO_RECIBO                            AS NRO_RECIBO ,
    SVCRV.ID_CONSTANCIA_RECEPCION                 AS ID_CONSTANCIA_RECEPCION ,
    SVV.OPERACION_ASOCIADA ,
    NULL                 AS FACTURA_RELACIONADA ,
    NULL                 AS DOCUMENTACION_ORIG_RECIBIDA ,
    SPM.DESCRIPCION      AS MOTIVO ,
    SPB.DESCRIPCION      AS BANCO_DEPOSITO ,
    SVV.ID_COPROPIETARIO AS ID_COPROPIETARIO ,
    SVV.USUARIO_AUTORIZACION ,
    SVV.NUMERO_DOCUMENTO_CONTABLE ,
    SPMS.DESCRIPCION                AS MOTIVO_SUSPENSION ,
    SPTC.USER_EJECUTIVO_CUENTA      AS EJECUTIVO ,
    SPTC.USER_ANALISTA_CONTRATO_VOZ AS ASISTENTE ,
    SVV.SALDO_DISPONIBLE ,
    SVBDCPD.FECHA_RECIBO                           AS FECHA_INGRESO_RECIBO ,
    NULL                                           AS FECHA_EMISION ,
    NULL                                           AS FECHA_TRANSFERENCIA ,
    UDF_SHV_OBTENER_NRO_CHEQUE(SVV.ID_VALOR_PADRE) AS VALOR_PADRE ,
    SAAA.NOMBRE_ARCHIVO                            AS ARCHIVO_DE_VALORES_A_CONCILIAR ,
    SVBDCPD.FECHA_DEPOSITO                         AS FECHA_DEPOSITO ,
    SVV.FECHA_ULTIMO_ESTADO ,
    SVV.FECHA_DISPONIBLE ,
    -- DATOS SEPARACION VIEJO CAMPO NRO. VALOR REQ 11 SPRINT 3
    SBB.NUMERO_BOLETA                   AS NRO_BOLETA ,
    SPBORIGEN.DESCRIPCION               AS DESCRIPCION_BANCO_ORIGEN ,
    SVBDCPD.FECHA_VENCIMIENTO           AS FECHA_VENCIMIENTO ,
    NULL                                AS ID_TIPO_RETENCION,
    NULL                                AS DESCRIPCION_TIPO_RETENCION,
    NULL                                AS NRO_CUIT_RETENCION,
    NULL                                AS PROVINCIA_RETENCION,
    --FERNANDO.FORMENTO 01/04/2016 - mejora de contabilidad
    NULL                                AS ID_PROVINCIA_RETENCION,
    TO_CHAR(SVBDCPD.NUMERO_CHEQUE)      AS REFERENCIA_VALOR,
    SPTC.USER_ANALISTA_COBRANZA_DATOS   AS ID_ANALISTA_TEAM_COMERCIAL,
    SPTC.USER_SUPERVISOR_COBRANZA_DATOS AS ID_SUPERVISOR_TEAM_COMERCIAL,
    SPTC.USER_GERENTE_REGIONAL          AS ID_GERENTE_REG_TEAM_COMERCIAL,
    NULL                                AS CODIGO_ORGANISMO,
    SVV.OBSERVACIONES                   AS OBSERVACIONES,
    -- DATOS ADICIONALES PARA USO INTERNO
    SWWE.ESTADO AS ID_ESTADO_VALOR ,
    SVV.ID_TIPO_VALOR ,
    SVV.ID_ORIGEN ,
    SVV.ID_EMPRESA ,
    SVV.ID_SEGMENTO ,
    SVV.FECHA_VALOR,
    GET_COBRO_FORMATEADO(SVV.ID_VALOR)                       AS COBRO_FORMATEADO,
    SBB.ID_BOLETA                                            AS ID_BOLETA,
    TO_CHAR(SVBDCPD.FECHA_VENCIMIENTO, 'DD/MM/YYYY HH24:MI') AS FECHA_BUSQUEDA,
    --FERNANDO.FORMENTO 18/02/2016 - mejora de performance de contabilidad
    NULL AS NRO_CUIT_TRANSACCION
  FROM SHV_VAL_VALOR SVV
  INNER JOIN SHV_WF_WORKFLOW_ESTADO SWWE
  ON SVV.ID_WORKFLOW = SWWE.ID_WORKFLOW
  INNER JOIN SHV_PARAM_WORKFLOW_ESTADO SPWE
  ON SWWE.ESTADO = SPWE.ID_ESTADO
  INNER JOIN SHV_VAL_BOLETA_DEP_CHEQUE_PD SVBDCPD
  ON SVV.ID_VALOR = SVBDCPD.ID_VALOR
  INNER JOIN SHV_BOL_BOLETA SBB
  ON SVBDCPD.ID_BOLETA = SBB.ID_BOLETA
  LEFT JOIN SHV_AVC_REG_AVC_VALOR SARAV
  ON SVV.ID_VALOR = SARAV.ID_VALOR
  LEFT JOIN SHV_AVC_REGISTRO_AVC SARA
  ON SARAV.ID_REGISTRO_AVC = SARA.ID_REGISTRO_AVC
  LEFT JOIN SHV_AVC_ARCHIVO_AVC SAAA
  ON SARA.ID_ARCHIVO_AVC = SAAA.ID_ARCHIVO_AVC
  LEFT JOIN SHV_TAL_RECIBO_PREIMPRESO STRP
  ON STRP.ID_RECIBO_PREIMPRESO = SVBDCPD.ID_RECIBO_PREIMPRESO
  LEFT JOIN SHV_VAL_CONSTANCIA_RECEP_VALOR SVCRV
  ON SVV.ID_VALOR = SVCRV.ID_VALOR
  LEFT JOIN SHV_PARAM_ACUERDO SPA
  ON SVV.ID_ACUERDO = SPA.ID_ACUERDO
  LEFT JOIN SHV_PARAM_BANCO SPBORIGEN
  ON SVBDCPD.ID_BANCO_ORIGEN = SPBORIGEN.ID_BANCO
  LEFT JOIN SHV_PARAM_BANCO_CUENTA SPBC
  ON SPA.ID_BANCO_CUENTA = SPBC.ID_BANCO_CUENTA
  LEFT JOIN SHV_PARAM_BANCO SPB
  ON SPBC.ID_BANCO = SPB.ID_BANCO
  INNER JOIN SHV_PARAM_TIPO_VALOR SPTV
  ON SVV.ID_TIPO_VALOR = SPTV.ID_TIPO_VALOR
  LEFT JOIN SHV_PARAM_MOTIVO SPM
  ON SVV.ID_MOTIVO = SPM.ID_MOTIVO
  INNER JOIN SHV_PARAM_SEGMENTO SPS
  ON SVV.ID_SEGMENTO = SPS.ID_SEGMENTO
  LEFT JOIN SHV_PARAM_ORIGEN SPO
  ON SVV.ID_ORIGEN = SPO.ID_ORIGEN
  LEFT JOIN SHV_PARAM_MOTIVO_SUSPENSION SPMS
  ON SVV.ID_MOTIVO_SUSPENSION = SPMS.ID_MOTIVO_SUSPENSION
  INNER JOIN SHV_PARAM_EMPRESA SPE
  ON SVV.ID_EMPRESA = SPE.ID_EMPRESA
  LEFT JOIN SHV_PARAM_TEAM_COMERCIAL SPTC
  ON SVV.ID_CLIENTE_LEGADO = SPTC.NRO_DE_CLIENTE
  );
  
  --------------------
  -- Cobro Grilla de transacciones sub vista 1
  --------------------
  CREATE OR REPLACE VIEW SHV_SOP_COBROS_DETALLE_FACTURA (ID_FACTURA, ID_TRANSACCION, ESTADO, SISTEMA_ORIGEN, ID_CLIENTE_LEGADO, TIPO_COMPROBANTE, SUBTIPO_DOCUMENTO, ORIGEN_DOCUMENTO, NUMERO_DOCUMENTO, NUMERO_REFERENCIA_MIC, FECHA_VENCIMIENTO, FECHA_SEGUNDO_VENCIMIENTO, MONEDA, FECHA_COBRO, IMPORTE_A_COBRAR, IMPORTE_ORIGINAL, SALDO_ACTUAL, TIPO_DE_CAMBIO_FECHA_COBRO, TIPO_DE_CAMBIO_FECHA_EMISION, IMPORTE_APLIC_FEC_EMIS_MON_ORI, MONTO_ACUMULADO_SIMULACION, FECHA_ACUMULADO_SIMULACION, TIPO_PAGO, QUE_HACER_CON_INTERESES, COBRADOR_INTERESES_GENERADOS, COBRADOR_INTERESES_TRASLADADOS, CHECK_TRASLADAR_INTERESES, CHECK_COBRAR_SEGUNDO_VENCIMIEN, PORCENTAJE_BONIF_INTERESES, IMPORTE_BONIF_INTERESES, ACUERDO_TRASLADO_CARGO, ESTADO_ACUERDO_TRASLADO_CARGO, ID_CLIENTE_ACUERDO_TRAS_CARGO, ACUERDO_TRASLADO_CARGO_ORIGNAL, TIPO_MENSAJE_ESTADO, MENSAJE_ESTADO)
AS
  (
  --
  -- Facturas Mic
  --
  SELECT
    -- Datos del documento
    scf.id_factura,
    scf.id_transaccion,
    scf.estado,
    scf.sistema_origen                             AS sistema_origen,
    scf.id_cliente_legado                          AS id_cliente_legado,
    scf.tipo_comprobante                           AS tipo_comprobante,
    NVL(TO_CHAR(scfm.tipo_factura), scfm.tipo_duc) AS subtipo_documento,
    NULL                                           AS origen_documento,
    DECODE (scf.clase_comprobante,'S','','D','', scf.clase_comprobante
    ||'-')
    ||lpad(scf.sucursal_comprobante, 4, '0')
    ||'-'
    ||lpad(scf.numero_comprobante, 8, '0') AS numero_documento,
    scfm.id_referencia_factura             AS numero_referencia_mic,
    scf.fecha_vencimiento                  AS fecha_vencimiento,
    scfm.fecha_segundo_vencimiento         AS fecha_segundo_vencimiento,
    'PES'                                  AS moneda, -- Los documentos de MIC son todos en Pesos, por lo que se presenta el valor 'PES' por defecto
    scf.fecha_valor                        AS fecha_cobro,
    scf.importe_cobrar                     AS importe_a_cobrar,
    scf.importe_original                   AS importe_original,
    scf.saldo_actual                       AS saldo_actual,
    NULL                                   AS tipo_de_cambio_fecha_cobro,
    NULL                                   AS tipo_de_cambio_fecha_emision,
    NULL                                   AS importe_aplic_fec_emis_mon_ori,
    scf.monto_acumulado_simulacion         AS monto_acumulado_simulacion,
    scf.fecha_acumulado_simulacion         AS fecha_acumulado_simulacion,
    -- Tipo de pago
    scf.tipo_pago AS tipo_pago,
    -- Gestion de intereses
    scf.que_hacer_con_intereses        AS que_hacer_con_intereses,
    scf.cobrador_intereses_generados   AS cobrador_intereses_generados,
    scf.cobrador_intereses_trasladados AS cobrador_intereses_trasladados,
    scf.check_trasladar_intereses      AS check_trasladar_intereses,
    scfm.cobrar_segundo_vencimiento    AS check_cobrar_segundo_vencimien,
    scf.porcentaje_bonif_intereses     AS porcentaje_bonif_intereses,
    scf.importe_bonif_intereses        AS importe_bonif_intereses,
    scf.acuerdo_traslado_cargo         AS acuerdo_traslado_cargo,
    scf.estado_acuerdo_traslado_cargo  AS estado_acuerdo_traslado_cargo,
    scf.id_cliente_acuerdo_tras_cargo  AS id_cliente_acuerdo_tras_cargo,
    scf.acuerdo_traslado_cargo_orignal AS acuerdo_traslado_cargo_orignal,
    -- Mensajes de apropiacion
    scf.tipo_mensaje_estado AS tipo_mensaje_estado,
    scf.mensaje_estado      AS mensaje_estado
  FROM shv_cob_factura scf,
    shv_cob_factura_mic scfm
  WHERE scfm.id_factura = scf.id_factura
  --
  UNION
  --
  -- Facturas Calipso
  --
  SELECT
    -- Datos del documento
    scf.id_factura,
    scf.id_transaccion,
    scf.estado,
    scf.sistema_origen    AS sistema_origen,
    scf.id_cliente_legado AS id_cliente_legado,
    scf.tipo_comprobante  AS tipo_comprobante,
    NULL                  AS subtipo_documento,
    scfc.origen_documento AS origen_documento,
    DECODE (scf.clase_comprobante,'S','','D','', scf.clase_comprobante
    ||'-')
    ||lpad(scf.sucursal_comprobante, 4, '0')
    ||'-'
    ||lpad(scf.numero_comprobante, 8, '0') AS numero_documento,
    NULL                                   AS numero_referencia_mic,
    scf.fecha_vencimiento                  AS fecha_vencimiento,
    NULL                                   AS fecha_segundo_vencimiento,
    scfc.moneda                            AS moneda,
    scf.fecha_valor                        AS fecha_cobro,
    scf.importe_cobrar                     AS importe_a_cobrar,
    scf.importe_original                   AS importe_original,
    scf.saldo_actual                       AS saldo_actual,
    scfc.tipo_de_cambio_fecha_cobro        AS tipo_de_cambio_fecha_cobro,
    scfc.tipo_de_cambio_fecha_emision      AS tipo_de_cambio_fecha_emision,
    scfc.importe_aplic_fec_emis_mon_ori    AS importe_aplic_fec_emis_mon_ori,
    scf.monto_acumulado_simulacion         AS monto_acumulado_simulacion,
    scf.fecha_acumulado_simulacion         AS fecha_acumulado_simulacion,
    -- Tipo de pago
    scf.tipo_pago AS tipo_pago,
    -- Gestion de intereses
    scf.que_hacer_con_intereses        AS que_hacer_con_intereses,
    scf.cobrador_intereses_generados   AS cobrador_intereses_generados,
    scf.cobrador_intereses_trasladados AS cobrador_intereses_trasladados,
    scf.check_trasladar_intereses      AS check_trasladar_intereses,
    NULL                               AS check_cobrar_segundo_vencimien,
    scf.porcentaje_bonif_intereses     AS porcentaje_bonif_intereses,
    scf.importe_bonif_intereses        AS importe_bonif_intereses,
    scf.acuerdo_traslado_cargo         AS acuerdo_traslado_cargo,
    scf.estado_acuerdo_traslado_cargo  AS estado_acuerdo_traslado_cargo,
    scf.id_cliente_acuerdo_tras_cargo  AS id_cliente_acuerdo_tras_cargo,
    scf.acuerdo_traslado_cargo_orignal AS acuerdo_traslado_cargo_orignal,
    -- Mensajes de apropiacion
    scf.tipo_mensaje_estado AS tipo_mensaje_estado,
    scf.mensaje_estado      AS mensaje_estado
  FROM shv_cob_factura scf,
    shv_cob_factura_calipso scfc
  WHERE scfc.id_factura = scf.id_factura
  );
  
  
  --------------------
  -- Cobro Grilla de transacciones sub vista 2
  --------------------
  CREATE OR REPLACE VIEW SHV_SOP_COBROS_DETALLE_MED_PAG (ID_MEDIO_PAGO, ID_TIPO_MEDIO_PAGO, DESCRIPCION_MEDIO_PAGO, SUBTIPO_MEDIO_PAGO, ORIGEN_DOCUMENTO, ID_TRANSACCION, ESTADO, IMPORTE, MONTO_ACUMULADO_SIMULACION, MIGRADO_DEIMOS, ESTADO_DEIMOS, FECHA_ACTUALIZACION_DEIMOS, TIPO_MENSAJE_ESTADO, MENSAJE_ESTADO, MONEDA, SISTEMA_ORIGEN, ID_CLIENTE_LEGADO, FECHA_VALOR, REFERENCIA, QUE_HACER_CON_INTERESES, COBRADOR_INTERESES_GENERADOS, CHECK_TRASLADAR_INTERESES, COBRADOR_INTERESES_TRASLADADOS, PORCENTAJE_BONIF_INTERESES, IMPORTE_BONIF_INTERESES, ACUERDO_TRASLADO_CARGO, ESTADO_ACUERDO_TRASLADO_CARGO, ID_CLIENTE_ACUERDO_TRAS_CARGO, ACUERDO_TRASLADO_CARGO_ORIGNAL)
AS
  (SELECT scmp.id_medio_pago,
    scmp.id_tipo_medio_pago,
    sptmp.descripcion descripcion_medio_pago,
    scmpd.subtipo_medio_pago,
    scmpd.origen_documento AS origen_documento,
    scmp.id_transaccion,
    scmp.estado,
    scmp.importe,
    scmp.monto_acumulado_simulacion,
    scmp.migrado_deimos,
    scmp.estado_deimos,
    scmp.fecha_actualizacion_deimos,
    scmp.tipo_mensaje_estado,
    scmp.mensaje_estado,
    scmp.moneda,
    scmp.sistema_origen,
    scmp.id_cliente_legado,
    scmpd.fecha_valor,
    scmpd.referencia,
    -- Gestion de intereses
    scmpd.que_hacer_con_intereses        AS que_hacer_con_intereses,
    scmpd.cobrador_intereses_generados   AS cobrador_intereses_generados,
    scmpd.check_trasladar_intereses      AS check_trasladar_intereses,
    scmpd.cobrador_intereses_trasladados AS cobrador_intereses_trasladados,
    scmpd.porcentaje_bonif_intereses     AS porcentaje_bonif_intereses,
    scmpd.importe_bonif_intereses        AS importe_bonif_intereses,
    scmpd.acuerdo_traslado_cargo         AS acuerdo_traslado_cargo,
    scmpd.estado_acuerdo_traslado_cargo  AS estado_acuerdo_traslado_cargo,
    scmpd.id_cliente_acuerdo_tras_cargo  AS id_cliente_acuerdo_tras_cargo,
    scmpd.acuerdo_traslado_cargo_orignal AS acuerdo_traslado_cargo_orignal
  FROM shv_param_tipo_medio_pago sptmp,
    shv_cob_med_pago scmp,
    (
    --
    -- Medio pago Shiva
    --
    SELECT id_medio_pago              AS id_medio_pago,
      referencia_valor                AS referencia,
      fecha_valor                     AS fecha_valor,
      svvr.id_tipo_retencion_impuesto AS subtipo_medio_pago,
      NULL                            AS origen_documento,
      -- Gestion de intereses
      NULL AS que_hacer_con_intereses,
      NULL AS cobrador_intereses_generados,
      NULL AS check_trasladar_intereses,
      NULL AS cobrador_intereses_trasladados,
      NULL AS porcentaje_bonif_intereses,
      NULL AS importe_bonif_intereses,
      NULL AS acuerdo_traslado_cargo,
      NULL AS estado_acuerdo_traslado_cargo,
      NULL AS id_cliente_acuerdo_tras_cargo,
      NULL AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_shiva scmps,
      shv_val_valor_retencion svvr
    WHERE scmps.id_valor = svvr.id_valor (+)
    UNION
    --
    -- Medio pago Compensacion
    --
    SELECT id_medio_pago,
      numero_compensacion AS refmediopago,
      fecha,
      NULL AS subtipo_medio_pago,
      NULL AS origen_documento,
      -- Gestion de intereses
      NULL AS que_hacer_con_intereses,
      NULL AS cobrador_intereses_generados,
      NULL AS check_trasladar_intereses,
      NULL AS cobrador_intereses_trasladados,
      NULL AS porcentaje_bonif_intereses,
      NULL AS importe_bonif_intereses,
      NULL AS acuerdo_traslado_cargo,
      NULL AS estado_acuerdo_traslado_cargo,
      NULL AS id_cliente_acuerdo_tras_cargo,
      NULL AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_compensacion
    UNION
    --
    -- Medio pago Compensacion Intercompany
    --
    SELECT id_medio_pago,
      numero_compensacion,
      fecha,
      NULL AS subtipo_medio_pago,
      NULL AS origen_documento,
      -- Gestion de intereses
      NULL AS que_hacer_con_intereses,
      NULL AS cobrador_intereses_generados,
      NULL AS check_trasladar_intereses,
      NULL AS cobrador_intereses_trasladados,
      NULL AS porcentaje_bonif_intereses,
      NULL AS importe_bonif_intereses,
      NULL AS acuerdo_traslado_cargo,
      NULL AS estado_acuerdo_traslado_cargo,
      NULL AS id_cliente_acuerdo_tras_cargo,
      NULL AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_comp_intercom
    UNION
    --
    -- Medio pago Compensacion Liquido Producto
    --
    SELECT id_medio_pago,
      numero_compensacion,
      fecha,
      NULL AS subtipo_medio_pago,
      NULL AS origen_documento,
      -- Gestion de intereses
      NULL AS que_hacer_con_intereses,
      NULL AS cobrador_intereses_generados,
      NULL AS check_trasladar_intereses,
      NULL AS cobrador_intereses_trasladados,
      NULL AS porcentaje_bonif_intereses,
      NULL AS importe_bonif_intereses,
      NULL AS acuerdo_traslado_cargo,
      NULL AS estado_acuerdo_traslado_cargo,
      NULL AS id_cliente_acuerdo_tras_cargo,
      NULL AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_comp_liquido
    UNION
    --
    -- Medio pago Desistimiento
    --
    SELECT id_medio_pago,
      numero_acta,
      fecha,
      NULL AS subtipo_medio_pago,
      NULL AS origen_documento,
      -- Gestion de intereses
      NULL AS que_hacer_con_intereses,
      NULL AS cobrador_intereses_generados,
      NULL AS check_trasladar_intereses,
      NULL AS cobrador_intereses_trasladados,
      NULL AS porcentaje_bonif_intereses,
      NULL AS importe_bonif_intereses,
      NULL AS acuerdo_traslado_cargo,
      NULL AS estado_acuerdo_traslado_cargo,
      NULL AS id_cliente_acuerdo_tras_cargo,
      NULL AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_desistimiento
    UNION
    --
    -- Medio de pago Plan de Pago
    --
    SELECT id_medio_pago,
      NULL,
      fecha,
      NULL AS subtipo_medio_pago,
      NULL AS origen_documento,
      -- Gestion de intereses
      NULL AS que_hacer_con_intereses,
      NULL AS cobrador_intereses_generados,
      NULL AS check_trasladar_intereses,
      NULL AS cobrador_intereses_trasladados,
      NULL AS porcentaje_bonif_intereses,
      NULL AS importe_bonif_intereses,
      NULL AS acuerdo_traslado_cargo,
      NULL AS estado_acuerdo_traslado_cargo,
      NULL AS id_cliente_acuerdo_tras_cargo,
      NULL AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_plan_pago
    UNION
    --
    -- Medio pago CTA
    --
    SELECT id_medio_pago,
      DECODE (clase_comprobante,'S','','D','', clase_comprobante
      ||'-')
      ||lpad(sucursal_comprobante, 4, '0')
      ||'-'
      ||lpad(numero_comprobante, 8, '0'),
      fecha_emision,
      NULL             AS subtipo_medio_pago,
      origen_documento AS origen_documento,
      -- Gestion de intereses
      NULL AS que_hacer_con_intereses,
      NULL AS cobrador_intereses_generados,
      NULL AS check_trasladar_intereses,
      NULL AS cobrador_intereses_trasladados,
      NULL AS porcentaje_bonif_intereses,
      NULL AS importe_bonif_intereses,
      NULL AS acuerdo_traslado_cargo,
      NULL AS estado_acuerdo_traslado_cargo,
      NULL AS id_cliente_acuerdo_tras_cargo,
      NULL AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_cta
    UNION
    --
    -- Medio pago Nota de Credito Calipso
    --
    SELECT id_medio_pago,
      DECODE (clase_comprobante,'S','','D','', clase_comprobante
      ||'-')
      ||lpad(sucursal_comprobante, 4, '0')
      ||'-'
      ||lpad(numero_comprobante, 8, '0'),
      fecha_emision,
      NULL             AS subtipo_medio_pago,
      origen_documento AS origen_documento,
      -- Gestion de intereses
      NULL AS que_hacer_con_intereses,
      NULL AS cobrador_intereses_generados,
      NULL AS check_trasladar_intereses,
      NULL AS cobrador_intereses_trasladados,
      NULL AS porcentaje_bonif_intereses,
      NULL AS importe_bonif_intereses,
      NULL AS acuerdo_traslado_cargo,
      NULL AS estado_acuerdo_traslado_cargo,
      NULL AS id_cliente_acuerdo_tras_cargo,
      NULL AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_nota_cred_clp
    UNION
    --
    -- Medio de pago Debito Proxima Factura Calipso
    --
    SELECT id_medio_pago,
      NULL,
      fecha,
      NULL AS subtipo_medio_pago,
      NULL AS origen_documento,
      -- Gestion de intereses
      que_hacer_con_intereses        AS que_hacer_con_intereses,
      cobrador_intereses_generados   AS cobrador_intereses_generados,
      check_trasladar_intereses      AS check_trasladar_intereses,
      cobrador_intereses_trasladados AS cobrador_intereses_trasladados,
      porcentaje_bonif_intereses     AS porcentaje_bonif_intereses,
      importe_bonif_intereses        AS importe_bonif_intereses,
      acuerdo_traslado_cargo         AS acuerdo_traslado_cargo,
      estado_acuerdo_traslado_cargo  AS estado_acuerdo_traslado_cargo,
      id_cliente_acuerdo_tras_cargo  AS id_cliente_acuerdo_tras_cargo,
      acuerdo_traslado_cargo_orignal AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_deb_prox_clp
    UNION
    --
    -- Medio pago Remanente
    --
    SELECT id_medio_pago,
      cuenta_remanente
      ||tipo_remanente,
      fecha_alta,
      tipo_remanente AS subtipo_medio_pago,
      NULL           AS origen_documento,
      -- Gestion de intereses
      NULL AS que_hacer_con_intereses,
      NULL AS cobrador_intereses_generados,
      NULL AS check_trasladar_intereses,
      NULL AS cobrador_intereses_trasladados,
      NULL AS porcentaje_bonif_intereses,
      NULL AS importe_bonif_intereses,
      NULL AS acuerdo_traslado_cargo,
      NULL AS estado_acuerdo_traslado_cargo,
      NULL AS id_cliente_acuerdo_tras_cargo,
      NULL AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_remanente
    UNION
    --
    -- Medio pago Nota de Credito Mic
    --
    SELECT id_medio_pago,
      DECODE (clase_comprobante,'S','','D','', clase_comprobante
      ||'-')
      ||lpad(sucursal_comprobante, 4, '0')
      ||'-'
      ||lpad(numero_comprobante, 8, '0'),
      fecha_emision,
      NULL AS subtipo_medio_pago,
      NULL AS origen_documento,
      -- Gestion de intereses
      NULL AS que_hacer_con_intereses,
      NULL AS cobrador_intereses_generados,
      NULL AS check_trasladar_intereses,
      NULL AS cobrador_intereses_trasladados,
      NULL AS porcentaje_bonif_intereses,
      NULL AS importe_bonif_intereses,
      NULL AS acuerdo_traslado_cargo,
      NULL AS estado_acuerdo_traslado_cargo,
      NULL AS id_cliente_acuerdo_tras_cargo,
      NULL AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_nota_cred_mic
    UNION
    --
    -- Medio de pago Debito Proxima Factura Mic
    --
    SELECT id_medio_pago,
      NULL,
      fecha,
      NULL AS subtipo_medio_pago,
      NULL AS origen_documento,
      -- Gestion de intereses
      que_hacer_con_intereses        AS que_hacer_con_intereses,
      cobrador_intereses_generados   AS cobrador_intereses_generados,
      check_trasladar_intereses      AS check_trasladar_intereses,
      cobrador_intereses_trasladados AS cobrador_intereses_trasladados,
      porcentaje_bonif_intereses     AS porcentaje_bonif_intereses,
      importe_bonif_intereses        AS importe_bonif_intereses,
      acuerdo_traslado_cargo         AS acuerdo_traslado_cargo,
      estado_acuerdo_traslado_cargo  AS estado_acuerdo_traslado_cargo,
      id_cliente_acuerdo_tras_cargo  AS id_cliente_acuerdo_tras_cargo,
      acuerdo_traslado_cargo_orignal AS acuerdo_traslado_cargo_orignal
    FROM shv_cob_med_pag_deb_prox_mic
    ) scmpd
  WHERE scmpd.id_medio_pago    = scmp.id_medio_pago
  AND sptmp.id_tipo_medio_pago = scmp.id_tipo_medio_pago
  );
  
  --------------------
  -- Cobro Grilla de transacciones
  --------------------
  CREATE OR REPLACE VIEW SHV_SOP_COBROS_GRILLA_TRANSAC (NUMERO_TRANSACCION_FORMATEADO, ESTADO_TRANSACCION, SISTEMA_ORIGEN_DOCUMENTO, ID_CLIENTE_LEGADO_DOCUMENTO, TIPO_COMPROBANTE, SUBTIPO_DOCUMENTO, NUMERO_DOCUMENTO, NUMERO_REFERENCIA_MIC, FECHA_VENCIMIENTO, FECHA_SEGUNDO_VENCIMIENTO, MONEDA, FECHA_COBRO, IMPORTE_A_COBRAR, IMPORTE_ORIGINAL, SALDO_ACTUAL, TIPO_DE_CAMBIO_FECHA_COBRO, TIPO_DE_CAMBIO_FECHA_EMISION, IMPORTE_APLIC_FEC_EMIS_MON_ORI, MONTO_ACUMULADO_SIMULACION_DEB, FECHA_ACUMULADO_SIMULACION_DEB, ORIGEN_DOCUMENTO, SISTEMA_ORIGEN_MEDIO_PAGO, ID_CLIENTE_LEGADO_MEDIO_PAGO, TIPO_MEDIO_PAGO, SUBTIPO_MEDIO_PAGO, REFERENCIA_MEDIO_PAGO, FECHA_MEDIO_PAGO, IMPORTE_MEDIO_PAGO, MONTO_ACUMULADO_SIMULACION_CRE, TIPO_PAGO, QUE_HACER_CON_INTERESES, INTERESES_GENERADOS, CHECK_TRASLADAR_INTERESES, COBRADOR_INTERESES_TRASLADADOS, CHECK_COBRAR_SEGUNDO_VENCIMIEN, PORCENTAJE_A_BONIFICAR, IMPORTE_A_BONIFICAR,
  ACUERDO_TRASLADO_CARGO, ESTADO_ACUERDO_TRASLADO_CARGO, ID_CLIENTE_ACUERDO_TRAS_CARGO, ACUERDO_TRASLADO_CARGO_ORIGNAL, TIPO_MENSAJE_ESTADO_TRANSACCIO, MENSAJE_ESTADO_TRANSACCION, TIPO_MENSAJE_ESTADO_DEBITO, MENSAJE_ESTADO_DEBITO, ESTADO_DEBITO, TIPO_MENSAJE_ESTADO_CREDITO, MENSAJE_ESTADO_CREDITO, ESTADO_CREDITO, ID_COBRO, ID_OPERACION, ID_TRANSACCION, NUMERO_TRANSACCION, NUMERO_TRANSACCION_PADRE, NUMERO_TRANSACCION_PADRE_FORMA, ID_FACTURA, ID_MEDIO_PAGO, ID_TRATAMIENTO_DIFERENCIA, ID_TRANSACCION_PADRE)
AS
  (
  --
  -- Datos de Facturas
  --
  SELECT
    -- Datos de la transaccion
    lpad(sct.id_operacion, 7, '0')
    ||'.'
    ||lpad(sct.numero_transaccion, 5, '0') AS numero_transaccion_formateado,
    sct.estado                             AS estado_transaccion,
    -- Datos del documento a cobrar
    sscdf.sistema_origen                 AS sistema_origen_documento,
    sscdf.id_cliente_legado              AS id_cliente_legado_documento,
    sscdf.tipo_comprobante               AS tipo_comprobante,
    sscdf.subtipo_documento              AS subtipo_documento,
    sscdf.numero_documento               AS numero_documento,
    sscdf.numero_referencia_mic          AS numero_referencia_mic,
    sscdf.fecha_vencimiento              AS fecha_vencimiento,
    sscdf.fecha_segundo_vencimiento      AS fecha_segundo_vencimiento,
    sscdf.moneda                         AS moneda,
    sscdf.fecha_cobro                    AS fecha_cobro,
    sscdf.importe_a_cobrar               AS importe_a_cobrar,
    sscdf.importe_original               AS importe_original,
    sscdf.saldo_actual                   AS saldo_actual,
    sscdf.tipo_de_cambio_fecha_cobro     AS tipo_de_cambio_fecha_cobro,
    sscdf.tipo_de_cambio_fecha_emision   AS tipo_de_cambio_fecha_emision,
    sscdf.importe_aplic_fec_emis_mon_ori AS importe_aplic_fec_emis_mon_ori,
    sscdf.monto_acumulado_simulacion     AS monto_acumulado_simulacion_deb,
    sscdf.fecha_acumulado_simulacion     AS fecha_acumulado_simulacion_deb,
    -- Datos comunes
    sscdf.origen_documento AS origen_documento,
    -- Datos de medios de pago
    NULL AS sistema_origen_medio_pago,
    NULL AS id_cliente_legado_medio_pago,
    NULL AS tipo_medio_pago,
    NULL AS subtipo_medio_pago,
    NULL AS referencia_medio_pago,
    NULL AS fecha_medio_pago,
    NULL AS importe_medio_pago,
    NULL AS monto_acumulado_simulacion_cre,
    -- Tipo de pago
    sscdf.tipo_pago AS tipo_pago,
    -- Gestion de intereses
    sscdf.que_hacer_con_intereses        AS que_hacer_con_intereses,
    sscdf.cobrador_intereses_generados   AS intereses_generados,
    sscdf.check_trasladar_intereses      AS check_trasladar_intereses,
    sscdf.cobrador_intereses_trasladados AS cobrador_intereses_trasladados,
    sscdf.check_cobrar_segundo_vencimien AS check_cobrar_segundo_vencimien,
    sscdf.porcentaje_bonif_intereses     AS porcentaje_a_bonificar,
    sscdf.importe_bonif_intereses        AS importe_a_bonificar,
    sscdf.acuerdo_traslado_cargo         AS acuerdo_traslado_cargo,
    sscdf.estado_acuerdo_traslado_cargo  AS estado_acuerdo_traslado_cargo,
    sscdf.id_cliente_acuerdo_tras_cargo  AS id_cliente_acuerdo_tras_cargo,
    sscdf.acuerdo_traslado_cargo_orignal AS acuerdo_traslado_cargo_orignal,
    -- Mensajes de apropiacion
    sct.tipo_mensaje_estado   AS tipo_mensaje_estado_transaccio,
    sct.mensaje_estado        AS mensaje_estado_transaccion,
    sscdf.tipo_mensaje_estado AS tipo_mensaje_estado_debito,
    sscdf.mensaje_estado      AS mensaje_estado_debito,
    sscdf.estado              AS estado_debito,
    NULL                      AS tipo_mensaje_estado_credito,
    NULL                      AS mensaje_estado_credito,
    NULL                      AS estado_credito,
    -- Datos ocultos del cobro / transaccion
    scc.id_cobro,
    sct.id_operacion,
    sct.id_transaccion,
    sct.numero_transaccion,
    sct.numero_transaccion_padre,
    lpad(sct.id_operacion, 7, '0')
    ||'.'
    ||lpad(sct.numero_transaccion_padre, 5, '0') AS numero_transaccion_padre_forma,
    sscdf.id_factura,
    0    AS id_medio_pago,
    NULL AS id_tratamiento_diferencia,
    NULL AS id_transaccion_padre
  FROM shv_cob_cobro scc,
    shv_cob_transaccion sct,
    shv_sop_cobros_detalle_factura sscdf
  WHERE sscdf.id_transaccion = sct.id_transaccion
  AND scc.id_operacion       = sct.id_operacion
  --
  UNION
  --
  -- Datos de medios de pago utilizados
  --
  SELECT
    -- Datos de la transaccion
    lpad(sct.id_operacion, 7, '0')
    ||'.'
    ||lpad(sct.numero_transaccion, 5, '0') AS numero_transaccion_formateado,
    sct.estado                             AS estado_transaccion,
    -- Datos del documento a cobrar
    NULL AS sistema_origen_documento,
    NULL AS id_cliente_legado_documento,
    NULL AS tipo_comprobante,
    NULL AS subtipo_documento,
    NULL AS numero_documento,
    NULL AS numero_referencia_mic,
    NULL AS fecha_vencimiento,
    NULL AS fecha_segundo_vencimiento,
    NULL AS moneda,
    NULL AS fecha_cobro,
    NULL AS importe_a_cobrar,
    NULL AS importe_original,
    NULL AS saldo_actual,
    NULL AS tipo_de_cambio_fecha_cobro,
    NULL AS tipo_de_cambio_fecha_emision,
    NULL AS importe_aplic_fec_emis_mon_ori,
    NULL AS monto_acumulado_simulacion,
    NULL AS fecha_acumulado_simulacion,
    -- Datos comunes
    sscdmp.origen_documento AS origen_documento,
    -- Datos de medios de pago
    sscdmp.sistema_origen             AS sistema_origen_medio_pago,
    sscdmp.id_cliente_legado          AS id_cliente_legado_medio_pago,
    sscdmp.descripcion_medio_pago     AS tipo_medio_pago,
    sscdmp.subtipo_medio_pago         AS subtipo_medio_pago,
    sscdmp.referencia                 AS referencia_medio_pago,
    sscdmp.fecha_valor                AS fecha_medio_pago,
    sscdmp.importe                    AS importe_medio_pago,
    sscdmp.monto_acumulado_simulacion AS monto_acumulado_simulacion_cre,
    -- Tipo de pago
    NULL AS tipo_pago,
    -- Gestion de intereses
    sscdmp.que_hacer_con_intereses        AS que_hacer_con_intereses,
    sscdmp.cobrador_intereses_generados   AS intereses_generados,
    sscdmp.check_trasladar_intereses      AS check_trasladar_intereses,
    sscdmp.cobrador_intereses_trasladados AS cobrador_intereses_trasladados,
    NULL                                  AS check_cobrar_segundo_vencimien,
    sscdmp.porcentaje_bonif_intereses     AS porcentaje_a_bonificar,
    sscdmp.importe_bonif_intereses        AS importe_a_bonificar,
    sscdmp.acuerdo_traslado_cargo         AS acuerdo_traslado_cargo,
    sscdmp.estado_acuerdo_traslado_cargo  AS estado_acuerdo_traslado_cargo,
    sscdmp.id_cliente_acuerdo_tras_cargo  AS id_cliente_acuerdo_tras_cargo,
    sscdmp.acuerdo_traslado_cargo_orignal AS acuerdo_traslado_cargo_orignal,
    -- Mensajes de apropiacion
    sct.tipo_mensaje_estado    AS tipo_mensaje_estado_transaccio,
    sct.mensaje_estado         AS mensaje_estado_transaccion,
    NULL                       AS tipo_mensaje_estado_debito,
    NULL                       AS mensaje_estado_debito,
    NULL                       AS estado_debito,
    sscdmp.tipo_mensaje_estado AS tipo_mensaje_estado_credito,
    sscdmp.mensaje_estado      AS mensaje_estado_credito,
    sscdmp.estado              AS estado_credito,
    -- Datos ocultos del cobro / transaccion
    scc.id_cobro,
    sct.id_operacion,
    sct.id_transaccion,
    sct.numero_transaccion,
    sct.numero_transaccion_padre,
    lpad(sct.id_operacion, 7, '0')
    ||'.'
    ||lpad(sct.numero_transaccion_padre, 5, '0') AS numero_transaccion_padre_forma,
    NULL                                         AS id_factura,
    sscdmp.id_medio_pago                         AS id_medio_pago,
    NULL                                         AS id_tratamiento_diferencia,
    NULL                                         AS id_transaccion_padre
  FROM shv_cob_cobro scc,
    shv_cob_transaccion sct,
    shv_sop_cobros_detalle_med_pag sscdmp
  WHERE sscdmp.id_transaccion = sct.id_transaccion
  AND scc.id_operacion        = sct.id_operacion
  AND sscdmp.estado          != 'NUEVO'
  --
  UNION
  --
  -- Datos de tratamiento de diferencia
  --
  SELECT
    -- Datos de la transaccion
    lpad(sct.id_operacion, 7, '0')
    ||'.'
    ||lpad(sct.numero_transaccion, 5, '0') AS numero_transaccion_formateado,
    sct.estado                             AS estado_transaccion,
    -- Datos del documento a cobrar
    sctd.sistema_origen                                                         AS sistema_origen_documento,
    NULL                                                                        AS id_cliente_legado_documento,
    DECODE(sctd.tipo_tratamiento_diferencia, 'ENVIO_A_GANANCIAS', 'GAN', 'REI') AS tipo_comprobante,
    sctd.tipo_tratamiento_diferencia                                            AS subtipo_documento,
    NULL                                                                        AS numero_documento,
    NULL                                                                        AS numero_referencia_mic,
    NULL                                                                        AS fecha_vencimiento,
    NULL                                                                        AS fecha_segundo_vencimiento,
    NULL                                                                        AS moneda,
    sctd.fecha_valor                                                            AS fecha_cobro,
    sctd.importe                                                                AS importe_a_cobrar,
    NULL                                                                        AS importe_original,
    NULL                                                                        AS saldo_actual,
    NULL                                                                        AS tipo_de_cambio_fecha_cobro,
    NULL                                                                        AS tipo_de_cambio_fecha_emision,
    NULL                                                                        AS importe_aplic_fec_emis_mon_ori,
    NULL                                                                        AS monto_acumulado_simulacion,
    NULL                                                                        AS fecha_acumulado_simulacion,
    -- Datos comunes
    NULL AS origen_documento,
    -- Datos de medios de pago
    NULL AS sistema_origen_medio_pago,
    NULL AS id_cliente_legado_medio_pago,
    NULL AS tipo_medio_pago,
    NULL AS subtipo_medio_pago,
    NULL AS referencia_medio_pago,
    NULL AS fecha_medio_pago,
    NULL AS importe_medio_pago,
    NULL AS monto_acumulado_simulacion_cre,
    -- Tipo de pago
    NULL AS tipo_pago,
    -- Gestion de intereses
    sctd.que_hacer_con_intereses        AS que_hacer_con_intereses,
    sctd.cobrador_intereses_generados   AS intereses,
    sctd.check_trasladar_intereses      AS check_trasladar_intereses,
    sctd.cobrador_intereses_trasladados AS cobrador_intereses_trasladados,
    NULL                                AS check_cobrar_segundo_vencimien,
    sctd.porcentaje_bonif_intereses     AS porcentaje_a_bonificar,
    sctd.importe_bonif_intereses        AS importe_a_bonificar,
    sctd.acuerdo_traslado_cargo         AS acuerdo_traslado_cargo,
    sctd.estado_acuerdo_traslado_cargo  AS estado_acuerdo_traslado_cargo,
    sctd.id_cliente_acuerdo_tras_cargo  AS id_cliente_acuerdo_tras_cargo,
    sctd.acuerdo_traslado_cargo_orignal AS acuerdo_traslado_cargo_orignal,
    -- Mensajes de apropiacion
    sct.tipo_mensaje_estado  AS tipo_mensaje_estado_transaccio,
    sct.mensaje_estado       AS mensaje_estado_transaccion,
    sctd.tipo_mensaje_estado AS tipo_mensaje_estado_debito,
    sctd.mensaje_estado      AS mensaje_estado_debito,
    sctd.estado              AS estado_debito,
    NULL                     AS tipo_mensaje_estado_credito,
    NULL                     AS mensaje_estado_credito,
    NULL                     AS estado_credito,
    -- Datos ocultos del cobro / transaccion
    scc.id_cobro,
    sct.id_operacion,
    sct.id_transaccion,
    sct.numero_transaccion,
    sct.numero_transaccion_padre,
    lpad(sct.id_operacion, 7, '0')
    ||'.'
    ||lpad(sct.numero_transaccion, 5, '0') AS numero_transaccion_padre_forma,
    NULL                                   AS id_factura,
    NULL                                   AS id_medio_pago,
    sctd.id_tratamiento_diferencia         AS id_tratamiento_diferencia,
    NULL                                   AS id_transaccion_padre
  FROM shv_cob_cobro scc,
    shv_cob_transaccion sct,
    shv_cob_tratamiento_diferencia sctd
  WHERE sctd.id_transaccion = sct.id_transaccion
  AND scc.id_operacion      = sct.id_operacion
  );
  

  
  
  
  Exit;