
ALTER TABLE SHV_COB_DESCOBRO
ADD CONSTRAINT DESCOBRO_COBRO_FK
FOREIGN KEY (ID_COBRO) REFERENCES SHV_COB_COBRO(ID_COBRO) ENABLE;


ALTER TABLE SHV_COB_COBRO
DROP CONSTRAINT COBRO_DESCOBRO_FK;


Exit;
