package ar.com.telecom.shiva.presentacion.wsdl.calipso.descobros;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:50.169-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:WSDL", name = "WebServiceReversionCobrosPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebServiceReversionCobrosPortType {

    /**
     * Metodo que nos devuelve los resultados
     * 				del proceso de
     * 				la reversion de cobros.
     * 			
     */
    @WebResult(name = "RespuestaConsulta", targetNamespace = "urn:WSDL", partName = "RespuestaConsulta")
    @WebMethod(operationName = "Reversion", action = "urn:WebServiceReversionCobrosAction")
    public RespuestaReversion reversion(
        @WebParam(partName = "idOperacionShiva", name = "idOperacionShiva")
        java.lang.String idOperacionShiva,
        @WebParam(partName = "idTransaccionShiva", name = "idTransaccionShiva")
        java.lang.String idTransaccionShiva,
        @WebParam(partName = "usuarioCobrador", name = "usuarioCobrador")
        java.lang.String usuarioCobrador,
        @WebParam(partName = "tipoOperacion", name = "tipoOperacion")
        java.lang.String tipoOperacion,
        @WebParam(partName = "modoOperacion", name = "modoOperacion")
        java.lang.String modoOperacion,
        @WebParam(partName = "detalleFactura", name = "detalleFactura")
        Detallefacturas detalleFactura,
        @WebParam(partName = "detalleCargos", name = "detalleCargos")
        Detallecargo detalleCargos,
        @WebParam(partName = "listaCtaCre", name = "listaCtaCre")
        ListaCtaCrereversiones listaCtaCre,
        @WebParam(partName = "detalleContracargoFac", name = "detalleContracargoFac")
        Detallecontracargofac detalleContracargoFac,
        @WebParam(partName = "detalleContracargoCar", name = "detalleContracargoCar")
        Detallecontracargocar detalleContracargoCar
    );
}
