CREATE TABLE SHV_PARAM_MOTIVO_DESCOBRO(	
	ID_MOTIVO_DESCOBRO NUMBER NOT NULL, 
	DESCRIPCION VARCHAR2(50 BYTE), 
	AUD_REQUERIMIENTO_ORIGEN VARCHAR2(15 BYTE),
	USO_OPERACION_MASIVA VARCHAR2(2 BYTE),
	CONSTRAINT SHV_PARAM_MOTIVO_DESCOBRO_PK PRIMARY KEY (ID_MOTIVO_DESCOBRO)  ENABLE
) TABLESPACE "SHIVATS";


--
-- nueva tabla que relaciona los descobros/reversiones con las operaciones posteriores (anidamiento de operaciones parciales)
--

CREATE TABLE SHV_COB_DESCOBRO_OPERAC_RELAC
  (
    "ID_OPERACION_RELACIONADA"   				NUMBER NOT NULL ENABLE,
	"ID_DESCOBRO"   							NUMBER NOT NULL ENABLE,
	"SISTEMA"				       				VARCHAR2(7 BYTE) NOT NULL ENABLE,
	"ID_OPERACION"	           					NUMBER,
    "NRO_TRANSACCION" 			   				NUMBER,
	"ID_COBRANZA" 			   					NUMBER,
	"ID_CLIENTE_LEGADO"          				NUMBER(20,0),
	"IMPORTE_COBRADO"            				NUMBER(17,4),
    "FECHA_COBRANZA" 			   				TIMESTAMP(6),
    "TIPO_COMPROBANTE"           				VARCHAR2(3 BYTE),
    "CLASE_COMPROBANTE"          				VARCHAR2(1 BYTE),
    "SUCURSAL_COMPROBANTE"       				VARCHAR2(4 BYTE),
    "NUMERO_COMPROBANTE"         				VARCHAR2(8 BYTE),
    "ID_DOCUMENTO_CUENTAS_COBRANZA"             NUMBER(20,0),
	"NUMERO_REFERENCIA_MIC"       			    NUMBER(15,0),
	"ID_OPERACION_PADRE"       					NUMBER,
    "NRO_TRANSACCION_PADRE" 			   		NUMBER,
    CONSTRAINT "OPERACION_RELACIONADA_PK" PRIMARY KEY ("ID_OPERACION_RELACIONADA") ENABLE,
    CONSTRAINT "DESCOBRO_OP_REL_DESCOBRO_FK" FOREIGN KEY ("ID_DESCOBRO") REFERENCES "SHV_COB_DESCOBRO" ("ID_DESCOBRO") ENABLE
  ) TABLESPACE "SHIVATS";

CREATE SEQUENCE SEQ_SHV_COB_DESCOBRO_OP_REL INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999999 MINVALUE 1 CACHE 20;

CREATE TABLE "SHV_COB_DESCOBRO_ADJUNTO"
  (
    "ID_ADJUNTO"  NUMBER NOT NULL ENABLE,
    "ID_DESCOBRO" NUMBER NOT NULL ENABLE,
    CONSTRAINT "DESCOB_ADJUNTO_ID_ADJUNTO_FK" FOREIGN KEY ("ID_ADJUNTO") REFERENCES "SHV_DOC_DOCUMENTO_ADJUNTO" ("ID_ADJUNTO") ENABLE,
    CONSTRAINT "DESCOB_ADJUNTO_ID_DESCOBRO_FK" FOREIGN KEY ("ID_DESCOBRO") REFERENCES "SHV_COB_DESCOBRO" ("ID_DESCOBRO") ENABLE
  ) TABLESPACE "SHIVATS";
  
  
  CREATE TABLE SHV_WF_TAREA_DESCOBRO
  (
    ID_TAREA             NUMBER NOT NULL ENABLE,
    ID_DESCOBRO          NUMBER NOT NULL ENABLE,
    IMPORTE              NUMBER(15,2),
    ID_CLIENTE_LEGADO    NUMBER,
    RAZON_SOCIAL_CLIENTE VARCHAR2(200 BYTE),
    ID_OPERACION         NUMBER,
    CONSTRAINT TAREA_DESCOBRO_PK PRIMARY KEY (ID_TAREA) ENABLE,
    CONSTRAINT TAREA_DESCOBRO_TAREA_FK FOREIGN KEY (ID_TAREA) REFERENCES SHV_WF_TAREA (ID_TAREA) ENABLE,
    CONSTRAINT TAREA_DESCOBRO_COB_DESCOBRO_FK FOREIGN KEY (ID_DESCOBRO) REFERENCES SHV_COB_DESCOBRO (ID_DESCOBRO) ENABLE
  ) TABLESPACE "SHIVATS";
  
  CREATE TABLE SHV_COB_DESCOBRO_DOC_RELAC
  (
    ID_DOCUMENTO_RELACIONADO   				NUMBER NOT NULL ENABLE,
    ID_DESCOBRO   							NUMBER NOT NULL ENABLE,
    ID_OPERACION	           				NUMBER,
    NRO_TRANSACCION 			   			NUMBER,
    ID_COBRANZA_GEN 			   			NUMBER,
    IMPORTE_GEN            					NUMBER(17,4),
    IMPORTE_CAPITAL_GEN            			NUMBER(17,4),
    IMPORTE_IMPUESTOS_GEN            		NUMBER(17,4),    
    TIPO_COMPROBANTE_GEN           			VARCHAR2(3 BYTE),
    CLASE_COMPROBANTE_GEN          			VARCHAR2(1 BYTE),
    SUCURSAL_COMPROBANTE_GEN       			VARCHAR2(4 BYTE),
    NUMERO_COMPROBANTE_GEN         			VARCHAR2(8 BYTE),
    ID_DOC_CUENTAS_COBRANZA_GEN             NUMBER(20,0),
    FECHA_VENCIMIENTO_GEN 			   		DATE,
    IMPORTE_APLICADO_GEN            		NUMBER(17,4),    
    ORIGEN_DOCUMENTO_GEN           			VARCHAR2(3 BYTE),
    TIPO_COMPROBANTE_ORI           			VARCHAR2(3 BYTE),
    CLASE_COMPROBANTE_ORI          			VARCHAR2(1 BYTE),
    SUCURSAL_COMPROBANTE_ORI       			VARCHAR2(4 BYTE),
    NUMERO_COMPROBANTE_ORI         			VARCHAR2(8 BYTE),
    ID_DOC_CUENTAS_COBRANZA_ORI             NUMBER(20,0),
    CONSTRAINT DOCUMENTO_RELACIONADO_PK PRIMARY KEY (ID_DOCUMENTO_RELACIONADO) ENABLE,
    CONSTRAINT DESCOBRO_DOC_REL_DESCOBRO_FK FOREIGN KEY (ID_DESCOBRO) REFERENCES SHV_COB_DESCOBRO (ID_DESCOBRO) ENABLE
  ) TABLESPACE "SHIVATS";
  
  CREATE SEQUENCE SEQ_SHV_COB_DESCOBRO_DOC_REL INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999999 MINVALUE 1 CACHE 20;
  
  ---------------------------------------------------------
  -- CREACION DE VISTAS VACIAS
  ---------------------------------------------------------
  
	CREATE VIEW SHV_SOP_DESCOBROS_HISTORIAL AS SELECT 1 AS VISTA FROM DUAL;
		
	CREATE VIEW SHV_SOP_DESCOBROS_GRILLA_TRANS AS SELECT 1 AS VISTA FROM DUAL;
	
	CREATE VIEW SHV_SOP_DESCOBROS_DET_FACTURA AS SELECT 1 AS VISTA FROM DUAL;
	
	CREATE VIEW SHV_SOP_DESCOBROS_DET_MED_PAG AS SELECT 1 AS VISTA FROM DUAL;
	
	CREATE VIEW SHV_SOP_DESCOBROS_OPER_RELAC AS SELECT 1 AS VISTA FROM DUAL;

	Exit;