--Grant para funcion loguearse con el usuario que no es owner del schema	
	CREATE OR REPLACE SYNONYM SEQ_SHV_COB_DESCOBRO_OP_REL FOR A001033.SEQ_SHV_COB_DESCOBRO_OP_REL;
	
	CREATE OR REPLACE SYNONYM SHV_COB_DESCOBRO_OPERAC_RELAC FOR A001033.SHV_COB_DESCOBRO_OPERAC_RELAC;
	
	CREATE OR REPLACE SYNONYM SHV_SOP_DESCOBROS_OPER_RELAC FOR A001033.SHV_SOP_DESCOBROS_OPER_RELAC;
	
	CREATE OR REPLACE SYNONYM SHV_WF_TAREA_DESCOBRO FOR A001033.SHV_WF_TAREA_DESCOBRO;

	CREATE OR REPLACE SYNONYM SEQ_SHV_COB_DESCOBRO_DOC_REL FOR A001033.SEQ_SHV_COB_DESCOBRO_DOC_REL;
  
    CREATE OR REPLACE SYNONYM SHV_COB_DESCOBRO_DOC_RELAC FOR A001033.SHV_COB_DESCOBRO_DOC_RELAC;
    
   
        
    CREATE OR REPLACE SYNONYM SHV_PARAM_MOTIVO_DESCOBRO FOR A001033.SHV_PARAM_MOTIVO_DESCOBRO;
    
    CREATE OR REPLACE SYNONYM SHV_COB_DESCOBRO_ADJUNTO FOR A001033.SHV_COB_DESCOBRO_ADJUNTO;
    
    CREATE OR REPLACE SYNONYM SHV_SOP_DESCOBROS_HISTORIAL FOR A001033.SHV_SOP_DESCOBROS_HISTORIAL;
    
    CREATE OR REPLACE SYNONYM SHV_SOP_DESCOBROS_GRILLA_TRANS FOR A001033.SHV_SOP_DESCOBROS_GRILLA_TRANS;
    
    CREATE OR REPLACE SYNONYM SHV_SOP_DESCOBROS_DET_FACTURA FOR A001033.SHV_SOP_DESCOBROS_DET_FACTURA;
    
    CREATE OR REPLACE SYNONYM SHV_SOP_DESCOBROS_DET_MED_PAG FOR A001033.SHV_SOP_DESCOBROS_DET_MED_PAG;
   
    
    Exit;