
INSERT INTO SHV_PARAM_MOTIVO_DESCOBRO (ID_MOTIVO_DESCOBRO,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN,USO_OPERACION_MASIVA) VALUES (1,'Cheque Rechazado','FASE 2 SPRINT 7','NO');
INSERT INTO SHV_PARAM_MOTIVO_DESCOBRO (ID_MOTIVO_DESCOBRO,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN,USO_OPERACION_MASIVA) VALUES (2,'Valor Duplicado','FASE 2 SPRINT 7','NO');
INSERT INTO SHV_PARAM_MOTIVO_DESCOBRO (ID_MOTIVO_DESCOBRO,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN,USO_OPERACION_MASIVA) VALUES (3,'Error En Importe Aplicado','FASE 2 SPRINT 7','NO');
INSERT INTO SHV_PARAM_MOTIVO_DESCOBRO (ID_MOTIVO_DESCOBRO,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN,USO_OPERACION_MASIVA) VALUES (4,'Error En Imputación','FASE 2 SPRINT 7','NO');
INSERT INTO SHV_PARAM_MOTIVO_DESCOBRO (ID_MOTIVO_DESCOBRO,DESCRIPCION,AUD_REQUERIMIENTO_ORIGEN,USO_OPERACION_MASIVA) VALUES (5,'Reversión Relacionada','FASE 2 SPRINT 7','NO');

INSERT INTO SHV_MNU_MENU (ID_MENU,DESCRIPCION,URL_ACCESO,ORDEN,MENU_ID_MENU) VALUES (25,'Búsqueda de Reversiones','descobro-busqueda',3,22);

INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (192,24,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (193,26,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (194,27,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (195,28,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (196,29,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (197,30,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (198,31,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (199,32,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (200,33,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (201,34,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (202,35,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (203,37,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (204,38,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (205,39,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (206,40,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (207,41,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (208,42,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (209,43,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (210,44,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (211,45,25);
INSERT INTO SHV_MNU_MENU_PERFIL (ID_MENU_PERFIL,ID_PERFIL,ID_MENU) VALUES (212,46,25);

commit;

Exit;