--
-- Crear la tabla SHV_PARAM_COTIZACION)
--
CREATE table SHV_PARAM_COTIZACION
(
    ID_COTIZACION		NUMBER NOT NULL ENABLE,
    FECHA               DATE NOT NULL,
	MONEDA              VARCHAR2(3 BYTE) NOT NULL,
    TIPO_CAMBIO 		NUMBER(29,12),
    AUD_REQUERIMIENTO_ORIGEN VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CONSTRAINT SHV_PARAM_COTIZACION_PK PRIMARY KEY (ID_COTIZACION) ENABLE,
    CONSTRAINT FECHA_MONEDA_UNICO UNIQUE (FECHA,MONEDA) ENABLE
  )
  TABLESPACE SHIVATS;

 --  
--  creacion de la secuencia para SHV_PARAM_COTIZACION
--  
  CREATE SEQUENCE SEQ_SHV_PARAM_COTIZACION INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999999 MINVALUE 1 CACHE 20;

 --
--  creacion de index por moneda y fecha para SHV_PARAM_COTIZACION
--  
  CREATE INDEX IDX_SHV_PARAM_COTIZACION ON SHV_PARAM_COTIZACION (MONEDA,FECHA);
  

Exit;