-- Creacion de la vista sql SHV_SOP_TAGETIK
--
CREATE table SHV_COB_MED_PAG_COMP_CES_CRED
  (
    ID_MEDIO_PAGO       NUMBER NOT NULL ENABLE,
    NUMERO_COMPENSACION VARCHAR2(25 BYTE) NOT NULL ENABLE,
    FECHA  DATE,
	CONSTRAINT SHV_COB_MEDIO_PAG_CES_CRED_PK PRIMARY KEY (ID_MEDIO_PAGO) ENABLE,
    CONSTRAINT MP_COMP_CES_CRED_MP_USUARIO_FK FOREIGN KEY (ID_MEDIO_PAGO) REFERENCES SHV_COB_MED_PAG_USUARIO (ID_MEDIO_PAGO) ENABLE
  )
  TABLESPACE SHIVATS;

Exit;


