ALTER TABLE SHV_COB_ED_OTROS_MEDIO_PAGO ADD ID_PROVINCIA VARCHAR2(2 BYTE) NULL ENABLE;

ALTER TABLE SHV_COB_ED_OTROS_MEDIO_PAGO ADD CONSTRAINT ED_OTROS_MP_JURISDICCION_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES SHV_PARAM_JURISDICCION (ID_JURISDICCION) ENABLE;
    
exit;