--ami me tiro que ED_OTROS_MP_JURISDICCION_FK no existia--

alter table Shv_param_Provincia  MODIFY ID_PROVINCIA VARCHAR2(1 BYTE);
alter table SHV_COB_MED_PAG_COMP_IIBB MODIFY ID_PROVINCIA VARCHAR2(1 BYTE);
alter table SHV_COB_ED_OTROS_MEDIO_PAGO  MODIFY ID_PROVINCIA VARCHAR2(1 BYTE);
alter table SHV_COB_MED_PAG_COMP_IIBB  ADD CONSTRAINT ED_COMP_IBB_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES SHV_PARAM_PROVINCIA(ID_PROVINCIA);
alter table SHV_COB_ED_OTROS_MEDIO_PAGO ADD CONSTRAINT ED_OTROS_MP_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES SHV_PARAM_PROVINCIA(ID_PROVINCIA); 

alter table SHV_COB_ED_OTROS_MEDIO_PAGO DROP CONSTRAINT ED_OTROS_MP_JURISDICCION_FK;

Exit;