CREATE table SHV_PARAM_PROVINCIA
(
	ID_PROVINCIA		VARCHAR2(3 BYTE) NOT NULL ENABLE,
    DESCRIPCION              VARCHAR2(50 BYTE) NOT NULL ENABLE,
    AUD_REQUERIMIENTO_ORIGEN VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CONSTRAINT SHV_PARAM_PROVINCIA_PK PRIMARY KEY (ID_PROVINCIA) ENABLE
  )
  TABLESPACE SHIVATS;
Exit;