ALTER TABLE SHV_COB_MED_PAG_OTRAS_COMPEN RENAME TO SHV_COB_MED_PAG_COMP_OTRAS;

ALTER TABLE SHV_COB_MED_PAG_COMP_OTRAS RENAME CONSTRAINT MP_OTRAS_COMPEN_MP_USUARIO_FK TO MP_COMP_OTRAS_MP_USUARIO_FK;
ALTER TABLE SHV_COB_MED_PAG_COMP_OTRAS RENAME CONSTRAINT SHV_COB_MEDIO_PAG_OTRAS_COM_PK TO SHV_COB_MEDIO_PAG_COMP_OTRA_PK;

ALTER INDEX SHV_COB_MEDIO_PAG_OTRAS_COM_PK RENAME TO SHV_COB_MEDIO_PAG_COMP_OTRA_PK;

Exit;