ALTER TABLE SHV_COB_MED_PAG_OTRAS_COMPEN RENAME CONSTRAINT MP_COMPENSACION_MP_USUARIO_FK TO MP_OTRAS_COMPEN_MP_USUARIO_FK;
ALTER TABLE SHV_COB_MED_PAG_OTRAS_COMPEN RENAME CONSTRAINT SHV_COB_MEDIO_PAG_COMPENS_PK TO SHV_COB_MEDIO_PAG_OTRAS_COM_PK;

ALTER INDEX SHV_COB_MEDIO_PAG_COMPENS_PK RENAME TO SHV_COB_MEDIO_PAG_OTRAS_COM_PK;
commit;

Exit;