package ar.com.telecom.shiva.presentacion.wsdl.delta;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:48.666-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "TeamComercialClienteSOAPQSService", 
                  wsdlLocation = "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/delta/WebServiceTeamComercialCliente.wsdl",
                  targetNamespace = "http://www.openuri.org/TeamComercialCliente/") 
public class TeamComercialClienteSOAPQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.openuri.org/TeamComercialCliente/", "TeamComercialClienteSOAPQSService");
    public final static QName TeamComercialClienteSOAPQSPort = new QName("http://www.openuri.org/TeamComercialCliente/", "TeamComercialClienteSOAPQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/delta/WebServiceTeamComercialCliente.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TeamComercialClienteSOAPQSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/delta/WebServiceTeamComercialCliente.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TeamComercialClienteSOAPQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TeamComercialClienteSOAPQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TeamComercialClienteSOAPQSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TeamComercialClienteSOAPQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TeamComercialClienteSOAPQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TeamComercialClienteSOAPQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TeamComercialCliente
     */
    @WebEndpoint(name = "TeamComercialClienteSOAPQSPort")
    public TeamComercialCliente getTeamComercialClienteSOAPQSPort() {
        return super.getPort(TeamComercialClienteSOAPQSPort, TeamComercialCliente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TeamComercialCliente
     */
    @WebEndpoint(name = "TeamComercialClienteSOAPQSPort")
    public TeamComercialCliente getTeamComercialClienteSOAPQSPort(WebServiceFeature... features) {
        return super.getPort(TeamComercialClienteSOAPQSPort, TeamComercialCliente.class, features);
    }

}
