package ar.com.telecom.shiva.presentacion.wsdl.sap.s4.consultaProveedores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * 
 * 		
 *
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:50.372-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:rfc:functions", name = "ZFI_SHIVA_VENDOR_FIND_WS")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFISHIVAVENDORFINDWS {

    @RequestWrapper(localName = "ZFI_SHIVA_VENDOR_FIND", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "ar.com.telecom.shiva.presentacion.wsdl.sap.s4.consultaProveedores.ZFISHIVAVENDORFIND")
    @WebMethod(operationName = "ZFI_SHIVA_VENDOR_FIND", action = "urn:sap-com:document:sap:rfc:functions:ZFI_SHIVA_VENDOR_FIND_WS:ZFI_SHIVA_VENDOR_FINDRequest")
    @ResponseWrapper(localName = "ZFI_SHIVA_VENDOR_FINDResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "ar.com.telecom.shiva.presentacion.wsdl.sap.s4.consultaProveedores.ZFISHIVAVENDORFINDResponse")
    public void zfiSHIVAVENDORFIND(
        @WebParam(name = "IMP_VENDOR_DATA", targetNamespace = "")
        ar.com.telecom.shiva.presentacion.wsdl.sap.s4.consultaProveedores.ZFITTSH001I impVENDORDATA,
        @WebParam(name = "I_COMPANYCODE", targetNamespace = "")
        java.lang.String iCOMPANYCODE,
        @WebParam(mode = WebParam.Mode.OUT, name = "EXP_VENDOR_DATA", targetNamespace = "")
        javax.xml.ws.Holder<ZFITTSH001> expVENDORDATA,
        @WebParam(mode = WebParam.Mode.OUT, name = "ST_RETURN", targetNamespace = "")
        javax.xml.ws.Holder<ZSRETURN> stRETURN,
        @WebParam(mode = WebParam.Mode.OUT, name = "T_RETURN", targetNamespace = "")
        javax.xml.ws.Holder<ZTTRETURN> tRETURN
    );
}
