ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA MODIFY DEB_TAG_TIPO_CLIENTE VARCHAR2(3 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO MODIFY DEB_TAG_TIPO_CLI VARCHAR2(3 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_REINTEGRO MODIFY CUENTA NUMBER NULL;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA MODIFY CUENTA NUMBER NULL;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA add CRED_MED_PAG_COD_CLI NUMBER;

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA MODIFY CRED_TIPO_REMANENTE VARCHAR2(50 BYTE);

exit;