package ar.com.telecom.shiva.presentacion.wsdl.calipso.consultaAcuerdo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:49.375-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:WSDL", name = "WebServiceCalipsoConsultaAcuerdoPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebServiceCalipsoConsultaAcuerdoPortType {

    /**
     * Metodo que nos devuelve los resultados
     * 				del proceso de la consulta de un acuerdo
     * 			
     */
    @WebResult(name = "RespuestaConsulta", targetNamespace = "urn:WSDL", partName = "RespuestaConsulta")
    @WebMethod(operationName = "ConsultarAcuerdosCalipso", action = "urn:WebServiceCalipsoConsultaAcuerdoAction")
    public ResultadoAcuerdo consultarAcuerdosCalipso(
        @WebParam(partName = "Acuerdo", name = "Acuerdo")
        java.math.BigInteger acuerdo
    );
}
