package ar.com.telecom.shiva.presentacion.wsdl.siebel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:48.008-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.openuri.org/", name = "ClienteConsultarSoap")
@XmlSeeAlso({ar.com.telecom.shiva.presentacion.wsdl.siebel.header.response.ObjectFactory.class, ar.com.telecom.shiva.presentacion.wsdl.siebel.diccionario.cliente.ObjectFactory.class, ObjectFactory.class, ar.com.telecom.shiva.presentacion.wsdl.siebel.header.request.ObjectFactory.class, ar.com.telecom.shiva.presentacion.wsdl.siebel.diccionario.commons.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClienteConsultarSoap {

    @WebResult(name = "clientResponse", targetNamespace = "http://www.openuri.org/", partName = "parameters")
    @WebMethod(action = "http://www.openuri.org/clientRequest")
    public ClientResponse clientRequest(
        @WebParam(partName = "parameters", name = "clientRequest", targetNamespace = "http://www.openuri.org/")
        ClientRequest parameters
    );
}
