package ar.com.telecom.shiva.presentacion.wsdl.siebel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:48.083-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "ClienteConsultar", 
                  wsdlLocation = "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/siebel/ClienteConsultarContract.wsdl",
                  targetNamespace = "http://www.openuri.org/") 
public class ClienteConsultar extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.openuri.org/", "ClienteConsultar");
    public final static QName ClienteConsultarSoap = new QName("http://www.openuri.org/", "ClienteConsultarSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/siebel/ClienteConsultarContract.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ClienteConsultar.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/siebel/ClienteConsultarContract.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ClienteConsultar(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClienteConsultar(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteConsultar() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClienteConsultar(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClienteConsultar(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClienteConsultar(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ClienteConsultarSoap
     */
    @WebEndpoint(name = "ClienteConsultarSoap")
    public ClienteConsultarSoap getClienteConsultarSoap() {
        return super.getPort(ClienteConsultarSoap, ClienteConsultarSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteConsultarSoap
     */
    @WebEndpoint(name = "ClienteConsultarSoap")
    public ClienteConsultarSoap getClienteConsultarSoap(WebServiceFeature... features) {
        return super.getPort(ClienteConsultarSoap, ClienteConsultarSoap.class, features);
    }

}
