package ar.com.telecom.shiva.presentacion.wsdl.sap.imputacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * 
 * 		
 *
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:51.204-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:rfc:functions", name = "ZFI_SHIVA_POST_COMPENSACION_WS")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFISHIVAPOSTCOMPENSACIONWS {

    @RequestWrapper(localName = "ZFI_SHIVA_POST_COMPENSACION", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "ar.com.telecom.shiva.presentacion.wsdl.sap.imputacion.ZFISHIVAPOSTCOMPENSACION")
    @WebMethod(operationName = "ZFI_SHIVA_POST_COMPENSACION", action = "urn:sap-com:document:sap:rfc:functions:ZFI_SHIVA_POST_COMPENSACION_WS:ZFI_SHIVA_POST_COMPENSACIONRequest")
    @ResponseWrapper(localName = "ZFI_SHIVA_POST_COMPENSACIONResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "ar.com.telecom.shiva.presentacion.wsdl.sap.imputacion.ZFISHIVAPOSTCOMPENSACIONResponse")
    public void zfiSHIVAPOSTCOMPENSACION(
        @WebParam(name = "I_IDOPERACIONSHIVA", targetNamespace = "")
        java.lang.String iIDOPERACIONSHIVA,
        @WebParam(name = "PDF_FILE", targetNamespace = "")
        byte[] pdfFILE,
        @WebParam(name = "T_LINEITEMS", targetNamespace = "")
        ar.com.telecom.shiva.presentacion.wsdl.sap.imputacion.ZFITTSH005 tLINEITEMS,
        @WebParam(mode = WebParam.Mode.OUT, name = "E_COMPENSACION", targetNamespace = "")
        javax.xml.ws.Holder<ZFISSH008> eCOMPENSACION,
        @WebParam(mode = WebParam.Mode.OUT, name = "E_IDOPERACIONSHIVA", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eIDOPERACIONSHIVA,
        @WebParam(mode = WebParam.Mode.OUT, name = "ST_RETURN", targetNamespace = "")
        javax.xml.ws.Holder<ZSRETURN> stRETURN,
        @WebParam(mode = WebParam.Mode.OUT, name = "T_RETURN", targetNamespace = "")
        javax.xml.ws.Holder<ZTTRETURN> tRETURN
    );
}
