package ar.com.telecom.shiva.presentacion.wsdl.sap.imputacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:51.210-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "zfi_shiva_post_compensacion_srv", 
                  wsdlLocation = "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/sap/ZFI_SHIVA_POST_COMPENSACION_WS.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:rfc:functions") 
public class ZfiShivaPostCompensacionSrv extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:rfc:functions", "zfi_shiva_post_compensacion_srv");
    public final static QName ZfiShivaPostCompensacionBND = new QName("urn:sap-com:document:sap:rfc:functions", "zfi_shiva_post_compensacion_BND");
    public final static QName ZfiShivaPostCompensacionBNDSoap12 = new QName("urn:sap-com:document:sap:rfc:functions", "zfi_shiva_post_compensacion_BND_soap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/sap/ZFI_SHIVA_POST_COMPENSACION_WS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZfiShivaPostCompensacionSrv.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/sap/ZFI_SHIVA_POST_COMPENSACION_WS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZfiShivaPostCompensacionSrv(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZfiShivaPostCompensacionSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZfiShivaPostCompensacionSrv() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZfiShivaPostCompensacionSrv(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZfiShivaPostCompensacionSrv(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZfiShivaPostCompensacionSrv(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ZFISHIVAPOSTCOMPENSACIONWS
     */
    @WebEndpoint(name = "zfi_shiva_post_compensacion_BND")
    public ZFISHIVAPOSTCOMPENSACIONWS getZfiShivaPostCompensacionBND() {
        return super.getPort(ZfiShivaPostCompensacionBND, ZFISHIVAPOSTCOMPENSACIONWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFISHIVAPOSTCOMPENSACIONWS
     */
    @WebEndpoint(name = "zfi_shiva_post_compensacion_BND")
    public ZFISHIVAPOSTCOMPENSACIONWS getZfiShivaPostCompensacionBND(WebServiceFeature... features) {
        return super.getPort(ZfiShivaPostCompensacionBND, ZFISHIVAPOSTCOMPENSACIONWS.class, features);
    }
    /**
     *
     * @return
     *     returns ZFISHIVAPOSTCOMPENSACIONWS
     */
    @WebEndpoint(name = "zfi_shiva_post_compensacion_BND_soap12")
    public ZFISHIVAPOSTCOMPENSACIONWS getZfiShivaPostCompensacionBNDSoap12() {
        return super.getPort(ZfiShivaPostCompensacionBNDSoap12, ZFISHIVAPOSTCOMPENSACIONWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFISHIVAPOSTCOMPENSACIONWS
     */
    @WebEndpoint(name = "zfi_shiva_post_compensacion_BND_soap12")
    public ZFISHIVAPOSTCOMPENSACIONWS getZfiShivaPostCompensacionBNDSoap12(WebServiceFeature... features) {
        return super.getPort(ZfiShivaPostCompensacionBNDSoap12, ZFISHIVAPOSTCOMPENSACIONWS.class, features);
    }

}
