/*ALTER TABLES SHV_MAS_REGISTRO*/
ALTER TABLE SHV_MAS_REGISTRO add ID_OPERACION NUMBER;
ALTER TABLE SHV_MAS_REGISTRO add NOMBRE_ARCHIVO_SALIDA VARCHAR2(150 BYTE);
ALTER TABLE SHV_MAS_REGISTRO add FECHA_SALIDA DATE;
ALTER TABLE SHV_MAS_REGISTRO add NOMBRE_ARCHIVO_ENTRADA VARCHAR2(150 BYTE);
ALTER TABLE SHV_MAS_REGISTRO add FECHA_ENTRADA DATE;
ALTER TABLE SHV_MAS_REGISTRO add IMPORTE NUMBER(15,2);
ALTER TABLE SHV_MAS_REGISTRO RENAME COLUMN FECHA_MODIFICAION TO FECHA_MODIFICACION;


/*ALTER TABLES SHV_MAS_REGISTRO_APLICAR_DEUDA*/

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD ACCION_SOBRE_INTERESES VARCHAR2(2 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD ACUERDO_FACTURACION_DESTINO NUMBER;
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD CREDITO_MIGRADO VARCHAR2(2 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD 	DEB_IMPU_GRAL_MARCA_CYQ VARCHAR2(50 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD DEB_IMPU_GRAL_MARCA_RECLAMO VARCHAR2(50 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD DESTRANSFERIR_TERCEROS VARCHAR2(2 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD IMPORTE_BONIFICACION_INTERESES NUMBER;
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD MEDIO_PAGO_CODIGO_CLIENTE NUMBER;
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD NUMERO_REFERENCIA_FACTURA VARCHAR2(15 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD PORCENTAJE_BONIF_INTERESES NUMBER;

/*ELIMINA COLUMNAS INCORRECTAS DE SHV_MAS_REGISTRO_APLICAR_DEUDA*/

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA DROP COLUMN TERCEROS;
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA DROP COLUMN ID_REFERENCIA_FACTURA;
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA DROP COLUMN FECHA_VALOR;

/*MODIFICA EL NOMBRE DE LA COLUMNA DE SHV_MAS_REGISTRO_APLICAR_DEUDA*/

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA RENAME COLUMN NRO_REFERENCIA_NC TO NUMERO_REFERENCIA_NC;

/*SETEA UN CAMPO DE SHV_MAS_REGISTRO_APLICAR_DEUDA PARA QUE SEA NULLEABLE*/

ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA MODIFY CRED_GRAL_IMPORTE NULL;


/*ALTER TABLES SHV_MAS_REGISTRO_DESESTIMIENTO*/

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO ADD DEB_IMPU_GRAL_CUOTA	NUMBER(15,2);
ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO ADD DEB_IMPU_GRAL_NUM_CONV	NUMBER(3,0);
ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO ADD DEB_IMPU_GRAL_POS_DEST 	VARCHAR2(2 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO ADD DEB_IMPUTADO_GRAL_TIPO_DOC	VARCHAR2(8 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO ADD FECHA_ACTA_DESISTIMIENTO	DATE;
ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO ADD NUMERO_ACTA_DESISTIMIENTO	VARCHAR2(25 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO ADD NUMERO_REFERENCIA_FACTURA	VARCHAR2(15 BYTE);

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO MODIFY NUMERO_REFERENCIA_FACTURA VARCHAR2(15 BYTE) NOT NULL;


/*ELIMINA COLUMNAS INCORRECTAS DE SHV_MAS_REGISTRO_DESESTIMIENTO*/

ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO DROP COLUMN ID_REFERENCIA_FACTURA;
ALTER TABLE SHV_MAS_REGISTRO_DESESTIMIENTO DROP COLUMN IMPORTE;



/*ALTER TABLES SHV_MAS_REGISTRO_GANANCIAS*/

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS ADD CREDITO_MIGRADO VARCHAR2(2 BYTE);
ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS ADD TIPO_REMANENTE VARCHAR2(3 BYTE);


/*ELIMINA COLUMNAS INCORRECTAS DE SHV_MAS_REGISTRO_GANANCIAS*/

ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS DROP COLUMN TIPO_ORIGEN;

Exit;