package ar.com.telecom.shiva.presentacion.wsdl.sap.verificacionPartidas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:50.690-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "ZFI_SHIVA_VERIF_PARTIDAS_SRV", 
                  wsdlLocation = "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/sap/ZFI_SHIVA_VERIF_PARTIDAS_WS.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:rfc:functions") 
public class ZFISHIVAVERIFPARTIDASSRV extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:rfc:functions", "ZFI_SHIVA_VERIF_PARTIDAS_SRV");
    public final static QName ZFISHIVAVERIFPARTIDASBND = new QName("urn:sap-com:document:sap:rfc:functions", "ZFI_SHIVA_VERIF_PARTIDAS_BND");
    public final static QName ZFISHIVAVERIFPARTIDASBNDSoap12 = new QName("urn:sap-com:document:sap:rfc:functions", "ZFI_SHIVA_VERIF_PARTIDAS_BND_soap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/sap/ZFI_SHIVA_VERIF_PARTIDAS_WS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZFISHIVAVERIFPARTIDASSRV.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Desarrollo/Workspace/ShivaProd/src/main/resources/wsdl/sap/ZFI_SHIVA_VERIF_PARTIDAS_WS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZFISHIVAVERIFPARTIDASSRV(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZFISHIVAVERIFPARTIDASSRV(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZFISHIVAVERIFPARTIDASSRV() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZFISHIVAVERIFPARTIDASSRV(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZFISHIVAVERIFPARTIDASSRV(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZFISHIVAVERIFPARTIDASSRV(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ZFISHIVAVERIFPARTIDASWS
     */
    @WebEndpoint(name = "ZFI_SHIVA_VERIF_PARTIDAS_BND")
    public ZFISHIVAVERIFPARTIDASWS getZFISHIVAVERIFPARTIDASBND() {
        return super.getPort(ZFISHIVAVERIFPARTIDASBND, ZFISHIVAVERIFPARTIDASWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFISHIVAVERIFPARTIDASWS
     */
    @WebEndpoint(name = "ZFI_SHIVA_VERIF_PARTIDAS_BND")
    public ZFISHIVAVERIFPARTIDASWS getZFISHIVAVERIFPARTIDASBND(WebServiceFeature... features) {
        return super.getPort(ZFISHIVAVERIFPARTIDASBND, ZFISHIVAVERIFPARTIDASWS.class, features);
    }
    /**
     *
     * @return
     *     returns ZFISHIVAVERIFPARTIDASWS
     */
    @WebEndpoint(name = "ZFI_SHIVA_VERIF_PARTIDAS_BND_soap12")
    public ZFISHIVAVERIFPARTIDASWS getZFISHIVAVERIFPARTIDASBNDSoap12() {
        return super.getPort(ZFISHIVAVERIFPARTIDASBNDSoap12, ZFISHIVAVERIFPARTIDASWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFISHIVAVERIFPARTIDASWS
     */
    @WebEndpoint(name = "ZFI_SHIVA_VERIF_PARTIDAS_BND_soap12")
    public ZFISHIVAVERIFPARTIDASWS getZFISHIVAVERIFPARTIDASBNDSoap12(WebServiceFeature... features) {
        return super.getPort(ZFISHIVAVERIFPARTIDASBNDSoap12, ZFISHIVAVERIFPARTIDASWS.class, features);
    }

}
