package ar.com.telecom.shiva.presentacion.wsdl.sap.verificacionPartidas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * 
 * 		
 *
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:50.677-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:rfc:functions", name = "ZFI_SHIVA_VERIF_PARTIDAS_WS")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFISHIVAVERIFPARTIDASWS {

    @RequestWrapper(localName = "ZFI_SHIVA_VERIFICAR_PARTIDAS", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "ar.com.telecom.shiva.presentacion.wsdl.sap.verificacionPartidas.ZFISHIVAVERIFICARPARTIDAS")
    @WebMethod(operationName = "ZFI_SHIVA_VERIFICAR_PARTIDAS", action = "urn:sap-com:document:sap:rfc:functions:ZFI_SHIVA_VERIF_PARTIDAS_WS:ZFI_SHIVA_VERIFICAR_PARTIDASRequest")
    @ResponseWrapper(localName = "ZFI_SHIVA_VERIFICAR_PARTIDASResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "ar.com.telecom.shiva.presentacion.wsdl.sap.verificacionPartidas.ZFISHIVAVERIFICARPARTIDASResponse")
    public void zfiSHIVAVERIFICARPARTIDAS(
        @WebParam(name = "I_IDOPERACIONSHIVA", targetNamespace = "")
        java.lang.String iIDOPERACIONSHIVA,
        @WebParam(name = "T_LINEITEMS", targetNamespace = "")
        ar.com.telecom.shiva.presentacion.wsdl.sap.verificacionPartidas.ZFITTSH002 tLINEITEMS,
        @WebParam(mode = WebParam.Mode.OUT, name = "E_IDOPERACIONSHIVA", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eIDOPERACIONSHIVA,
        @WebParam(mode = WebParam.Mode.OUT, name = "ST_RETURN", targetNamespace = "")
        javax.xml.ws.Holder<ZSRETURN> stRETURN,
        @WebParam(mode = WebParam.Mode.OUT, name = "T_RETURN", targetNamespace = "")
        javax.xml.ws.Holder<ZTTRETURN> tRETURN
    );
}
