LOAD DATA
CHARACTERSET WE8ISO8859P1
INSERT
INTO TABLE SHV_MIG_VALOR_TRANSFERENCIA
 FIELDS TERMINATED BY '|'
 TRAILING NULLCOLS
(
 ID_SEGMENTO CHAR TERMINATED BY '|',
 ID_CLIENTE_LEGADO INTEGER EXTERNAL,
 ID_ANALISTA CHAR TERMINATED BY '|',
 ID_COPROPIETARIO CHAR TERMINATED BY '|',
 NUMERO_ACUERDO INTEGER EXTERNAL,
 IMPORTE DECIMAL EXTERNAL,
 SALDO_DISPONIBLE DECIMAL EXTERNAL,
 OBSERVACIONES CHAR TERMINATED BY '|',
 NUMERO_PARTIDA_CONTABLE INTEGER EXTERNAL,
 OPERACION_ASOCIADA INTEGER EXTERNAL,
 ID_MOTIVO INTEGER EXTERNAL,
 FECHA_ALTA DATE "DD/MM/YYYY HH24:MI:SS",
 USUARIO_AUTORIZACION CHAR TERMINATED BY '|',
 USUARIO_EJECUTIVO CHAR TERMINATED BY '|',
 USUARIO_ASISTENTE CHAR TERMINATED BY '|',
 ID_ORIGEN INTEGER EXTERNAL,
 NUMERO_REFERENCIA INTEGER EXTERNAL,
 ID_BANCO_ORIGEN CHAR TERMINATED BY '|',
 FECHA_TRANSFERENCIA DATE "DD/MM/YYYY HH24:MI:SS", 
 ID "SEQ_SHV_MIG_ID.NEXTVAL"
)

