ALTER TABLE SHV_COB_ED_COBRO ADD MONEDA_OPERACION VARCHAR2(3);

ALTER TABLE SHV_COB_COBRO ADD MONEDA_OPERACION VARCHAR2(3);

ALTER TABLE SHV_COB_DESCOBRO ADD MONEDA_OPERACION VARCHAR2(3);

ALTER TABLE SHV_COB_OPERACION ADD MONEDA_OPERACION VARCHAR2(3);

ALTER TABLE SHV_COB_FACTURA ADD MONEDA_IMPORTE_COBRAR VARCHAR2(3);

ALTER TABLE SHV_COB_MED_PAGO ADD MONEDA_IMPORTE VARCHAR2(3);

ALTER TABLE SHV_COB_ED_DEBITO ADD MONEDA_IMPORTE_A_COBRAR VARCHAR2(3);

ALTER TABLE SHV_COB_ED_DEBITO ADD HABILITAR_EDICION_SIN_DIF_CBIO VARCHAR2(2);

ALTER TABLE SHV_COB_ED_CREDITO ADD MONEDA_IMPORTE_A_UTILIZAR VARCHAR2(3);

ALTER TABLE SHV_COB_ED_OTROS_MEDIO_PAGO ADD MONEDA_IMPORTE_A_UTILIZAR VARCHAR2(3);

ALTER TABLE SHV_WF_TAREA_COBRO ADD MONEDA_IMPORTE VARCHAR2(3);

ALTER TABLE SHV_WF_TAREA_DESCOBRO ADD MONEDA_IMPORTE VARCHAR2(3);


Exit;
