CREATE TABLE SHV_COB_PROC_HILOS_COBROS
  (
    ID_PROC_HILOS   	NUMBER NOT NULL ENABLE,
    ID_OPERACION    	NUMBER NOT NULL ENABLE,
    ID_COBRO    		NUMBER NOT NULL ENABLE,
    FECHA_INICIO    	TIMESTAMP(6) NOT NULL ENABLE,
    FECHA_FIN       	TIMESTAMP(6),
    ESTADO   			VARCHAR2(50 BYTE), 
    CANT_TRANSACCIONES  NUMBER,

    CONSTRAINT ID_PROC_HILOS_PK PRIMARY KEY (ID_PROC_HILOS) ENABLE,
    CONSTRAINT PROC_HILOS_COBROS_FK FOREIGN KEY (ID_COBRO) REFERENCES SHV_COB_COBRO (ID_COBRO) ENABLE
    )
  TABLESPACE SHIVATS;
  
  CREATE SEQUENCE SEQ_SHV_COB_PROC_HILOS MINVALUE 0 MAXVALUE 99999999999999999999999 INCREMENT BY 1 START WITH 1;