UPDATE SHV_MAS_REGISTRO_APLICAR_DEUDA SET TIPO_OPERACION = 'PAGO_TOTAL' WHERE TIPO_OPERACION='0';
UPDATE SHV_MAS_REGISTRO_APLICAR_DEUDA SET TIPO_OPERACION = 'PAGO_PARCIAL' WHERE TIPO_OPERACION='1';

UPDATE SHV_MAS_REGISTRO_APLICAR_DEUDA SET CREDITO_MIGRADO = 'SI' WHERE CREDITO_MIGRADO='0';
UPDATE SHV_MAS_REGISTRO_APLICAR_DEUDA SET CREDITO_MIGRADO = 'NO' WHERE CREDITO_MIGRADO='1';

UPDATE SHV_MAS_REGISTRO_REINTEGRO SET CREDITO_MIGRADO = 'SI' WHERE CREDITO_MIGRADO='0';
UPDATE SHV_MAS_REGISTRO_REINTEGRO SET CREDITO_MIGRADO = 'NO' WHERE CREDITO_MIGRADO='1';

commit;

exit;