ALTER TABLE SHV_MAS_OPER_MASIVA_ARCH
ADD FECHA_DERIVACION DATE;

ALTER TABLE SHV_MAS_OPER_MASIVA_ARCH
ADD FECHA_AUTORIZACION DATE;

ALTER TABLE SHV_MAS_OPER_MASIVA_ARCH
ADD FECHA_PROCESO DATE;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD TIPO_OPERACION VARCHAR2(10);
--deberia ser no nullable
ALTER TABLE SHV_MAS_OPER_MASIVA
ADD FECHA_CREACION DATE;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD FECHA_MODIFICACION DATE;

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD USUARIO_MODIFICACION VARCHAR2(9);

ALTER TABLE SHV_MAS_OPER_MASIVA
ADD OBSERVACION VARCHAR2(250);


exit;