ALTER TABLE SHV_COB_FACTURA ADD ACUERDO_TRASLADO_CARGO_ORIGNAL Varchar2(20);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_CLP ADD ACUERDO_TRASLADO_CARGO_ORIGNAL Varchar2(20);
ALTER TABLE SHV_COB_MED_PAG_DEB_PROX_MIC ADD ACUERDO_TRASLADO_CARGO_ORIGNAL Varchar2(20);
ALTER TABLE SHV_COB_TRATAMIENTO_DIFERENCIA ADD ACUERDO_TRASLADO_CARGO_ORIGNAL Varchar2(20);
/
Exit;