LOAD DATA
CHARACTERSET WE8ISO8859P1
INSERT
INTO TABLE SHV_MIG_REG_AVC_TRANSFERENCIA
 FIELDS TERMINATED BY '|'
 TRAILING NULLCOLS
(
 ID_ARCHIVO INTEGER EXTERNAL,
 IMPORTE DECIMAL EXTERNAL,
 NUMERO_ACUERDO	INTEGER EXTERNAL,
 CODIGO_CLIENTE	INTEGER EXTERNAL,
 FECHA_INGRESO DATE "DD/MM/YYYY HH24:MI:SS",
 SUCURSAL INTEGER EXTERNAL,
 REFERENCIA INTEGER EXTERNAL,
 CODIGO	INTEGER EXTERNAL,
 OBSERVACIONES CHAR TERMINATED BY '|',
 ID "SEQ_SHV_MIG_ID.NEXTVAL"
 )

