/*ALTER TABLES SHV_MAS_REGISTRO_DESESTIMIENTO*/
ALTER TABLE SHV_MAS_REGISTRO_APLICAR_DEUDA ADD MEDIO_PAGO_CODIGO_CLIENTE NUMBER;

/*ALTER TABLES SHV_MAS_REGISTRO_GANANCIAS*/
ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS MODIFY CUENTA_ORIGEN	NUMBER;
ALTER TABLE SHV_MAS_REGISTRO_GANANCIAS MODIFY NRO_REFERENCIA_NC	NUMBER;

Exit;