package ar.com.telecom.shiva.presentacion.wsdl.calipso.consultadeudaycredito;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-05-21T12:28:49.742-03:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:WSDL", name = "WebServiceConsultasOnlinePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebServiceConsultasOnlinePortType {

    /**
     * Metodo que nos devuelve los resultados
     * 				de la consulta
     * 				de deuda del cliente
     * 			
     */
    @WebResult(name = "ListaDebitosSalida", targetNamespace = "urn:WSDL", partName = "ListaDebitosSalida")
    @WebMethod(operationName = "ConsultaDeudaFiltroCalipso", action = "urn:WebServiceConsultasOnlineAction")
    public ListaDebitosresultado consultaDeudaFiltroCalipso(
        @WebParam(partName = "ListaClientes", name = "ListaClientes")
        Detclientes listaClientes,
        @WebParam(partName = "IdDocumento", name = "IdDocumento")
        IdDocumentoAgru idDocumento,
        @WebParam(partName = "FechaVencimientoDesde", name = "FechaVencimientoDesde")
        java.lang.String fechaVencimientoDesde,
        @WebParam(partName = "FechaVencimientoHasta", name = "FechaVencimientoHasta")
        java.lang.String fechaVencimientoHasta,
        @WebParam(partName = "FechaCotizacion", name = "FechaCotizacion")
        java.lang.String fechaCotizacion,
        @WebParam(partName = "Acuerdo", name = "Acuerdo")
        java.math.BigInteger acuerdo,
        @WebParam(partName = "Moneda", name = "Moneda")
        java.lang.String moneda,
        @WebParam(partName = "CantidadRegistrosARetornar", name = "CantidadRegistrosARetornar")
        java.math.BigInteger cantidadRegistrosARetornar,
        @WebParam(partName = "UltimoIdDocCtasCob", name = "UltimoIdDocCtasCob")
        java.math.BigInteger ultimoIdDocCtasCob,
        @WebParam(partName = "UltimaFechaDocumento", name = "UltimaFechaDocumento")
        java.lang.String ultimaFechaDocumento,
        @WebParam(partName = "UltimoClienteDocumento", name = "UltimoClienteDocumento")
        java.lang.String ultimoClienteDocumento
    );

    /**
     * Metodo que nos devuelve los resultados
     * 				de la consulta
     * 				de creditos del cliente
     * 			
     */
    @WebResult(name = "ListaCreditosSalida", targetNamespace = "urn:WSDL", partName = "ListaCreditosSalida")
    @WebMethod(operationName = "ConsultaCreditoFiltroCalipso", action = "urn:WebServiceConsultasOnlineAction")
    public ListaCreditosresultado consultaCreditoFiltroCalipso(
        @WebParam(partName = "ListaClientes", name = "ListaClientes")
        DetCREclientes listaClientes,
        @WebParam(partName = "TipoMedioPago", name = "TipoMedioPago")
        java.lang.String tipoMedioPago,
        @WebParam(partName = "FechaDesde", name = "FechaDesde")
        java.lang.String fechaDesde,
        @WebParam(partName = "FechaHasta", name = "FechaHasta")
        java.lang.String fechaHasta,
        @WebParam(partName = "Acuerdo", name = "Acuerdo")
        java.math.BigInteger acuerdo,
        @WebParam(partName = "Moneda", name = "Moneda")
        java.lang.String moneda,
        @WebParam(partName = "CantidadRegistrosARetornar", name = "CantidadRegistrosARetornar")
        java.math.BigInteger cantidadRegistrosARetornar,
        @WebParam(partName = "UltimoIdDocCuentasCobranzaCTA", name = "UltimoIdDocCuentasCobranzaCTA")
        java.math.BigInteger ultimoIdDocCuentasCobranzaCTA,
        @WebParam(partName = "UltimaFechaCTA", name = "UltimaFechaCTA")
        java.lang.String ultimaFechaCTA,
        @WebParam(partName = "UltimoClienteCTA", name = "UltimoClienteCTA")
        java.lang.String ultimoClienteCTA,
        @WebParam(partName = "UltimoIdDocCuentasCobranzaNC", name = "UltimoIdDocCuentasCobranzaNC")
        java.math.BigInteger ultimoIdDocCuentasCobranzaNC,
        @WebParam(partName = "UltimaFechaNC", name = "UltimaFechaNC")
        java.lang.String ultimaFechaNC,
        @WebParam(partName = "UltimaClienteNC", name = "UltimaClienteNC")
        java.lang.String ultimaClienteNC
    );
}
