ALTER TABLE SHV_COB_ED_DEBITO RENAME COLUMN SUBTIPO TO SUBTIPO_DOCUMENTO;
ALTER TABLE SHV_COB_ED_DEBITO ADD SUBTIPO VARCHAR2(3 BYTE);

ALTER TABLE SHV_COB_ED_CREDITO ADD ID_CREDITO_REFERENCIA VARCHAR2(100 BYTE);
ALTER TABLE SHV_COB_ED_DEBITO ADD ID_DEBITO_REFERENCIA VARCHAR2(100 BYTE);

ALTER TABLE SHV_COB_ED_DEBITO MODIFY ESTADO_CONCEPTO_TERCEROS VARCHAR2(25 BYTE);
UPDATE SHV_COB_ED_DEBITO SET ESTADO_CONCEPTO_TERCEROS = 'NO_TRANSFERIDOS' WHERE ESTADO_CONCEPTO_TERCEROS = 'NO';
UPDATE SHV_COB_ED_DEBITO SET ESTADO_CONCEPTO_TERCEROS = 'PARCIALMENTE_TRANSFERIDOS' WHERE ESTADO_CONCEPTO_TERCEROS = 'SI';
COMMIT;

ALTER TABLE SHV_COB_FACTURA_MIC MODIFY ESTADO_CONCEPTO_TERCEROS VARCHAR2(25 BYTE);
UPDATE SHV_COB_FACTURA_MIC SET ESTADO_CONCEPTO_TERCEROS = 'NO_TRANSFERIDOS' WHERE ESTADO_CONCEPTO_TERCEROS = 'NO';
UPDATE SHV_COB_FACTURA_MIC SET ESTADO_CONCEPTO_TERCEROS = 'PARCIALMENTE_TRANSFERIDOS' WHERE ESTADO_CONCEPTO_TERCEROS = 'SI';
COMMIT;

/
Exit;