-- Creacion de la vista sql SHV_SOP_TAGETIK
--
CREATE table SHV_COB_MED_PAG_COMP_IIBB
(
    ID_MEDIO_PAGO       NUMBER NOT NULL ENABLE,
    NUMERO_COMPENSACION VARCHAR2(25 BYTE) NOT NULL ENABLE,
    FECHA               DATE,
    ID_PROVINCIA       NUMBER NOT NULL ENABLE,
    TIPO_CAMBIO NUMBER(29,12),
    CONSTRAINT SHV_COB_MEDIO_PAG_COMP_IIBB_PK PRIMARY KEY (ID_MEDIO_PAGO) ENABLE,
    CONSTRAINT MP_COMP_IIBB_MP_USUARIO_FK FOREIGN KEY (ID_MEDIO_PAGO) REFERENCES SHV_COB_MED_PAG_USUARIO (ID_MEDIO_PAGO) ENABLE
  )
  TABLESPACE SHIVATS;

Exit;


