package ar.com.telecom.shiva.base.enumeradores;

public enum TrazaEnum {
	IMPUTACION_COBROS,
	IMPUTACION_DESCOBROS,
	IMPUTACION_RESPUESTA,
	IMPUTACION_RECEPCION,
	RECEPCION_1ER_MSG,
	RECEPCION_2DO_MSG,
	IMPUTACION_MANUAL_COBROS;
}
